search filter SimpleName SimpleType SingleVariableDeclaration SimpleName search filter
search filter SimpleName MethodInvocation SimpleName get params
call api SimpleName MethodInvocation SimpleName get entities
call api SimpleName MethodInvocation TypeLiteral SimpleType QualifiedName atlas entityatlas entities
call api SimpleName MethodInvocation MethodInvocation SimpleName search filter
call api SimpleName MethodInvocation MethodInvocation SimpleName get params
get entities SimpleName MethodInvocation TypeLiteral SimpleType QualifiedName atlas entityatlas entities
get entities SimpleName MethodInvocation MethodInvocation SimpleName search filter
get entities SimpleName MethodInvocation MethodInvocation SimpleName get params
public Modifier MethodDeclaration SimpleType QualifiedName atlas entityatlas entities
public Modifier MethodDeclaration SimpleName search entities
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName search filter
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName search filter
public Modifier MethodDeclaration SimpleType SimpleName atlas service exception
atlas entityatlas entities QualifiedName SimpleType MethodDeclaration SimpleName search entities
atlas entityatlas entities QualifiedName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName search filter
atlas entityatlas entities QualifiedName SimpleType MethodDeclaration SimpleType SimpleName atlas service exception
search entities SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName search filter
search entities SimpleName MethodDeclaration SingleVariableDeclaration SimpleName search filter
search entities SimpleName MethodDeclaration SimpleType SimpleName atlas service exception
search filter SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType QualifiedName atlas entityatlas entities
public Modifier TypeDeclaration MethodDeclaration SimpleName search entities
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName search filter
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType QualifiedName atlas entityatlas entities
test SimpleName TypeDeclaration MethodDeclaration SimpleName search entities
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName search filter
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
