set SimpleName SimpleType ParameterizedType SimpleType SimpleName resource
request SimpleName SimpleType SingleVariableDeclaration SimpleName request
predicate SimpleName SimpleType SingleVariableDeclaration SimpleName predicate
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleName get resources
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName request
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName predicate
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName set
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName resource
public Modifier MethodDeclaration SimpleName get resources
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName request
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName request
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName predicate
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName predicate
set SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get resources
resource SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get resources
get resources SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName request
get resources SimpleName MethodDeclaration SingleVariableDeclaration SimpleName request
get resources SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName predicate
get resources SimpleName MethodDeclaration SingleVariableDeclaration SimpleName predicate
request SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName predicate
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleName get resources
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName request
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName predicate
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleName get resources
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName request
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName predicate
