public Modifier MethodDeclaration SimpleType SimpleName state
public Modifier MethodDeclaration SimpleName get desired state
state SimpleName SimpleType MethodDeclaration SimpleName get desired state
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName state
public Modifier TypeDeclaration MethodDeclaration SimpleName get desired state
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName state
test SimpleName TypeDeclaration MethodDeclaration SimpleName get desired state
