string SimpleName SimpleType SingleVariableDeclaration SimpleName cluster name
cluster name SimpleName FieldAccess Assignment SimpleName cluster name
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set cluster name
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName cluster name
void PrimitiveType MethodDeclaration SimpleName set cluster name
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName cluster name
set cluster name SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
set cluster name SimpleName MethodDeclaration SingleVariableDeclaration SimpleName cluster name
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set cluster name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cluster name
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set cluster name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cluster name
