public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName get cluster name
public Modifier MethodDeclaration Block ReturnStatement SimpleName cluster name
string SimpleName SimpleType MethodDeclaration SimpleName get cluster name
get cluster name SimpleName MethodDeclaration Block ReturnStatement SimpleName cluster name
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName get cluster name
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName get cluster name
