atlas enum type SimpleName SimpleType SingleVariableDeclaration SimpleName enum type
export context SimpleName SimpleType SingleVariableDeclaration SimpleName context
enum type SimpleName MethodInvocation SimpleName get type name
contextenum types QualifiedName MethodInvocation SimpleName contains
contextenum types QualifiedName MethodInvocation MethodInvocation SimpleName enum type
contextenum types QualifiedName MethodInvocation MethodInvocation SimpleName get type name
contains SimpleName MethodInvocation MethodInvocation SimpleName enum type
contains SimpleName MethodInvocation MethodInvocation SimpleName get type name
enum type SimpleName MethodInvocation SimpleName get type name
contextenum types QualifiedName MethodInvocation SimpleName add
contextenum types QualifiedName MethodInvocation MethodInvocation SimpleName enum type
contextenum types QualifiedName MethodInvocation MethodInvocation SimpleName get type name
add SimpleName MethodInvocation MethodInvocation SimpleName enum type
add SimpleName MethodInvocation MethodInvocation SimpleName get type name
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName add enum type
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas enum type
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName enum type
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName export context
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName context
void PrimitiveType MethodDeclaration SimpleName add enum type
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas enum type
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName enum type
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName export context
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName context
add enum type SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas enum type
add enum type SimpleName MethodDeclaration SingleVariableDeclaration SimpleName enum type
add enum type SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName export context
add enum type SimpleName MethodDeclaration SingleVariableDeclaration SimpleName context
enum type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName context
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName add enum type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName enum type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName context
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName add enum type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName enum type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName context
