byte PrimitiveType ArrayType SingleVariableDeclaration SimpleName old string
byte PrimitiveType SingleVariableDeclaration SimpleName new string
length SimpleName VariableDeclarationFragment QualifiedName old stringlength
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName length
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment QualifiedName old stringlength
length SimpleName InfixExpression NumberLiteral empty
byte PrimitiveType ArrayType ArrayCreation InfixExpression SimpleName length
byte PrimitiveType ArrayType ArrayCreation InfixExpression NumberLiteral empty
string SimpleName VariableDeclarationFragment ArrayCreation ArrayType PrimitiveType byte
string SimpleName VariableDeclarationFragment ArrayCreation InfixExpression SimpleName length
string SimpleName VariableDeclarationFragment ArrayCreation InfixExpression NumberLiteral empty
byte PrimitiveType ArrayType VariableDeclarationStatement VariableDeclarationFragment SimpleName string
system SimpleName MethodInvocation SimpleName arraycopy
system SimpleName MethodInvocation SimpleName old string
system SimpleName MethodInvocation NumberLiteral empty
system SimpleName MethodInvocation SimpleName string
system SimpleName MethodInvocation NumberLiteral empty
arraycopy SimpleName MethodInvocation SimpleName old string
arraycopy SimpleName MethodInvocation NumberLiteral empty
arraycopy SimpleName MethodInvocation SimpleName string
arraycopy SimpleName MethodInvocation NumberLiteral empty
arraycopy SimpleName MethodInvocation SimpleName length
old string SimpleName MethodInvocation NumberLiteral empty
old string SimpleName MethodInvocation SimpleName string
old string SimpleName MethodInvocation NumberLiteral empty
old string SimpleName MethodInvocation SimpleName length
empty NumberLiteral MethodInvocation SimpleName string
empty NumberLiteral MethodInvocation NumberLiteral empty
empty NumberLiteral MethodInvocation SimpleName length
string SimpleName MethodInvocation NumberLiteral empty
string SimpleName MethodInvocation SimpleName length
empty NumberLiteral MethodInvocation SimpleName length
string SimpleName ArrayAccess SimpleName length
string SimpleName ArrayAccess Assignment SimpleName new string
length SimpleName ArrayAccess Assignment SimpleName new string
int PrimitiveType VariableDeclarationStatement Block ReturnStatement SimpleName string
public Modifier MethodDeclaration ArrayType PrimitiveType byte
public Modifier MethodDeclaration SimpleName compose string
public Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName old string
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType byte
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName new string
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block ReturnStatement SimpleName string
byte PrimitiveType ArrayType MethodDeclaration SimpleName compose string
byte PrimitiveType ArrayType MethodDeclaration SingleVariableDeclaration SimpleName old string
byte PrimitiveType ArrayType MethodDeclaration SingleVariableDeclaration PrimitiveType byte
byte PrimitiveType ArrayType MethodDeclaration SingleVariableDeclaration SimpleName new string
compose string SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
compose string SimpleName MethodDeclaration SingleVariableDeclaration SimpleName old string
compose string SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType byte
compose string SimpleName MethodDeclaration SingleVariableDeclaration SimpleName new string
compose string SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
compose string SimpleName MethodDeclaration Block ReturnStatement SimpleName string
old string SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType byte
old string SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new string
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration ArrayType PrimitiveType byte
public Modifier TypeDeclaration MethodDeclaration SimpleName compose string
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName old string
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType byte
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new string
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration ArrayType PrimitiveType byte
test SimpleName TypeDeclaration MethodDeclaration SimpleName compose string
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName old string
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType byte
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new string
