byte PrimitiveType ArrayType SingleVariableDeclaration SimpleName curr
byte PrimitiveType ArrayType SingleVariableDeclaration SimpleName prev
int PrimitiveType SingleVariableDeclaration SimpleName count
int PrimitiveType SingleVariableDeclaration SimpleName bpp
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName raw
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName prior pixel
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row pixel
raw SimpleName VariableDeclarationFragment VariableDeclarationStatement VariableDeclarationFragment SimpleName prior pixel
raw SimpleName VariableDeclarationFragment VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row
raw SimpleName VariableDeclarationFragment VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row pixel
prior pixel SimpleName VariableDeclarationFragment VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row
prior pixel SimpleName VariableDeclarationFragment VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row pixel
prior row SimpleName VariableDeclarationFragment VariableDeclarationStatement VariableDeclarationFragment SimpleName prior row pixel
i SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName i
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment NumberLiteral empty
i SimpleName InfixExpression SimpleName bpp
curr SimpleName ArrayAccess SimpleName i
curr SimpleName ArrayAccess InfixExpression NumberLiteral xff
i SimpleName ArrayAccess InfixExpression NumberLiteral xff
raw SimpleName Assignment InfixExpression ArrayAccess SimpleName curr
raw SimpleName Assignment InfixExpression ArrayAccess SimpleName i
raw SimpleName Assignment InfixExpression NumberLiteral xff
prev SimpleName ArrayAccess SimpleName i
prev SimpleName ArrayAccess InfixExpression NumberLiteral xff
i SimpleName ArrayAccess InfixExpression NumberLiteral xff
prior row SimpleName Assignment InfixExpression ArrayAccess SimpleName prev
prior row SimpleName Assignment InfixExpression ArrayAccess SimpleName i
prior row SimpleName Assignment InfixExpression NumberLiteral xff
curr SimpleName ArrayAccess SimpleName i
raw SimpleName InfixExpression SimpleName prior row
byte PrimitiveType CastExpression ParenthesizedExpression InfixExpression SimpleName raw
byte PrimitiveType CastExpression ParenthesizedExpression InfixExpression SimpleName prior row
curr SimpleName ArrayAccess Assignment CastExpression PrimitiveType byte
i SimpleName ArrayAccess Assignment CastExpression PrimitiveType byte
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName i
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName bpp
int PrimitiveType VariableDeclarationExpression ForStatement PostfixExpression SimpleName i
i SimpleName InfixExpression ForStatement PostfixExpression SimpleName i
bpp SimpleName InfixExpression ForStatement PostfixExpression SimpleName i
i SimpleName VariableDeclarationFragment SimpleName bpp
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName i
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName bpp
i SimpleName InfixExpression SimpleName count
curr SimpleName ArrayAccess SimpleName i
curr SimpleName ArrayAccess InfixExpression NumberLiteral xff
i SimpleName ArrayAccess InfixExpression NumberLiteral xff
raw SimpleName Assignment InfixExpression ArrayAccess SimpleName curr
raw SimpleName Assignment InfixExpression ArrayAccess SimpleName i
raw SimpleName Assignment InfixExpression NumberLiteral xff
i SimpleName InfixExpression SimpleName bpp
curr SimpleName ArrayAccess InfixExpression SimpleName i
curr SimpleName ArrayAccess InfixExpression SimpleName bpp
curr SimpleName ArrayAccess InfixExpression NumberLiteral xff
i SimpleName InfixExpression ArrayAccess InfixExpression NumberLiteral xff
bpp SimpleName InfixExpression ArrayAccess InfixExpression NumberLiteral xff
prior pixel SimpleName Assignment InfixExpression ArrayAccess SimpleName curr
prior pixel SimpleName Assignment InfixExpression NumberLiteral xff
prev SimpleName ArrayAccess SimpleName i
prev SimpleName ArrayAccess InfixExpression NumberLiteral xff
i SimpleName ArrayAccess InfixExpression NumberLiteral xff
prior row SimpleName Assignment InfixExpression ArrayAccess SimpleName prev
prior row SimpleName Assignment InfixExpression ArrayAccess SimpleName i
prior row SimpleName Assignment InfixExpression NumberLiteral xff
i SimpleName InfixExpression SimpleName bpp
prev SimpleName ArrayAccess InfixExpression SimpleName i
prev SimpleName ArrayAccess InfixExpression SimpleName bpp
prev SimpleName ArrayAccess InfixExpression NumberLiteral xff
i SimpleName InfixExpression ArrayAccess InfixExpression NumberLiteral xff
bpp SimpleName InfixExpression ArrayAccess InfixExpression NumberLiteral xff
prior row pixel SimpleName Assignment InfixExpression ArrayAccess SimpleName prev
prior row pixel SimpleName Assignment InfixExpression NumberLiteral xff
curr SimpleName ArrayAccess SimpleName i
paeth predictor SimpleName MethodInvocation SimpleName prior pixel
paeth predictor SimpleName MethodInvocation SimpleName prior row
paeth predictor SimpleName MethodInvocation SimpleName prior row pixel
prior pixel SimpleName MethodInvocation SimpleName prior row
prior pixel SimpleName MethodInvocation SimpleName prior row pixel
prior row SimpleName MethodInvocation SimpleName prior row pixel
raw SimpleName InfixExpression MethodInvocation SimpleName paeth predictor
raw SimpleName InfixExpression MethodInvocation SimpleName prior pixel
raw SimpleName InfixExpression MethodInvocation SimpleName prior row
raw SimpleName InfixExpression MethodInvocation SimpleName prior row pixel
byte PrimitiveType CastExpression ParenthesizedExpression InfixExpression SimpleName raw
curr SimpleName ArrayAccess Assignment CastExpression PrimitiveType byte
i SimpleName ArrayAccess Assignment CastExpression PrimitiveType byte
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName i
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName count
int PrimitiveType VariableDeclarationExpression ForStatement PostfixExpression SimpleName i
i SimpleName InfixExpression ForStatement PostfixExpression SimpleName i
count SimpleName InfixExpression ForStatement PostfixExpression SimpleName i
private Modifier MethodDeclaration Modifier static
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName decode paeth filter
private Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName curr
private Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName prev
static Modifier MethodDeclaration PrimitiveType void
static Modifier MethodDeclaration SimpleName decode paeth filter
static Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName curr
static Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName prev
static Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName count
void PrimitiveType MethodDeclaration SimpleName decode paeth filter
void PrimitiveType MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName curr
void PrimitiveType MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName prev
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName count
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName bpp
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration SimpleName curr
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration SimpleName prev
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration SimpleName count
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
decode paeth filter SimpleName MethodDeclaration SingleVariableDeclaration SimpleName bpp
decode paeth filter SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName count
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName bpp
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName count
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName bpp
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName bpp
count SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
count SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName bpp
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName decode paeth filter
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName count
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName bpp
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName decode paeth filter
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName count
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName bpp
