ch SimpleName VariableDeclarationFragment MethodInvocation SimpleName read
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName ch
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName read
ch SimpleName InfixExpression NumberLiteral empty
ch SimpleName InfixExpression NumberLiteral empty
public Modifier MethodDeclaration Modifier final
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName read boolean
public Modifier MethodDeclaration SimpleType SimpleName io exception
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
final Modifier MethodDeclaration PrimitiveType boolean
final Modifier MethodDeclaration SimpleName read boolean
final Modifier MethodDeclaration SimpleType SimpleName io exception
final Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
boolean PrimitiveType MethodDeclaration SimpleName read boolean
boolean PrimitiveType MethodDeclaration SimpleType SimpleName io exception
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
read boolean SimpleName MethodDeclaration SimpleType SimpleName io exception
read boolean SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName read boolean
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName read boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
