double PrimitiveType ArrayType SingleVariableDeclaration SimpleName prev
int PrimitiveType SingleVariableDeclaration SimpleName prev seg type
double PrimitiveType ArrayType SingleVariableDeclaration SimpleName curr
int PrimitiveType SingleVariableDeclaration SimpleName curr seg type
double PrimitiveType ArrayType SingleVariableDeclaration SimpleName next
int PrimitiveType SingleVariableDeclaration SimpleName next seg type
get segment terminating point SimpleName MethodInvocation SimpleName curr
get segment terminating point SimpleName MethodInvocation SimpleName curr seg type
curr SimpleName MethodInvocation SimpleName curr seg type
marker position SimpleName VariableDeclarationFragment MethodInvocation SimpleName get segment terminating point
marker position SimpleName VariableDeclarationFragment MethodInvocation SimpleName curr
marker position SimpleName VariableDeclarationFragment MethodInvocation SimpleName curr seg type
point d SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName marker position
middle marker SimpleName MethodInvocation SimpleName get orient
rotation SimpleName VariableDeclarationFragment MethodInvocation SimpleName middle marker
rotation SimpleName VariableDeclarationFragment MethodInvocation SimpleName get orient
double PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName rotation
double PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName middle marker
double PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get orient
double SimpleName MethodInvocation SimpleName is na n
double SimpleName MethodInvocation SimpleName rotation
is na n SimpleName MethodInvocation SimpleName rotation
compute rotation SimpleName MethodInvocation SimpleName prev
compute rotation SimpleName MethodInvocation SimpleName prev seg type
compute rotation SimpleName MethodInvocation SimpleName curr
compute rotation SimpleName MethodInvocation SimpleName curr seg type
compute rotation SimpleName MethodInvocation SimpleName next
prev SimpleName MethodInvocation SimpleName prev seg type
prev SimpleName MethodInvocation SimpleName curr
prev SimpleName MethodInvocation SimpleName curr seg type
prev SimpleName MethodInvocation SimpleName next
prev SimpleName MethodInvocation SimpleName next seg type
prev seg type SimpleName MethodInvocation SimpleName curr
prev seg type SimpleName MethodInvocation SimpleName curr seg type
prev seg type SimpleName MethodInvocation SimpleName next
prev seg type SimpleName MethodInvocation SimpleName next seg type
curr SimpleName MethodInvocation SimpleName curr seg type
curr SimpleName MethodInvocation SimpleName next
curr SimpleName MethodInvocation SimpleName next seg type
curr seg type SimpleName MethodInvocation SimpleName next
curr seg type SimpleName MethodInvocation SimpleName next seg type
next SimpleName MethodInvocation SimpleName next seg type
rotation SimpleName Assignment MethodInvocation SimpleName compute rotation
rotation SimpleName Assignment MethodInvocation SimpleName prev
rotation SimpleName Assignment MethodInvocation SimpleName prev seg type
rotation SimpleName Assignment MethodInvocation SimpleName curr
rotation SimpleName Assignment MethodInvocation SimpleName curr seg type
rotation SimpleName Assignment MethodInvocation SimpleName next
rotation SimpleName Assignment MethodInvocation SimpleName next seg type
compute marker transform SimpleName MethodInvocation SimpleName middle marker
compute marker transform SimpleName MethodInvocation SimpleName marker position
compute marker transform SimpleName MethodInvocation SimpleName rotation
middle marker SimpleName MethodInvocation SimpleName marker position
middle marker SimpleName MethodInvocation SimpleName rotation
marker position SimpleName MethodInvocation SimpleName rotation
marker txf SimpleName VariableDeclarationFragment MethodInvocation SimpleName compute marker transform
marker txf SimpleName VariableDeclarationFragment MethodInvocation SimpleName middle marker
marker txf SimpleName VariableDeclarationFragment MethodInvocation SimpleName marker position
marker txf SimpleName VariableDeclarationFragment MethodInvocation SimpleName rotation
affine transform SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName marker txf
gn SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName proxy graphics node
proxy graphics node SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName gn
middle marker SimpleName MethodInvocation SimpleName get marker node
gn SimpleName MethodInvocation SimpleName set source
gn SimpleName MethodInvocation MethodInvocation SimpleName middle marker
gn SimpleName MethodInvocation MethodInvocation SimpleName get marker node
set source SimpleName MethodInvocation MethodInvocation SimpleName middle marker
set source SimpleName MethodInvocation MethodInvocation SimpleName get marker node
gn SimpleName MethodInvocation SimpleName set transform
gn SimpleName MethodInvocation SimpleName marker txf
set transform SimpleName MethodInvocation SimpleName marker txf
private Modifier MethodDeclaration SimpleType SimpleName proxy graphics node
private Modifier MethodDeclaration SimpleName create middle marker
private Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType double
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName prev
private Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName prev seg type
private Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType double
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName curr
proxy graphics node SimpleName SimpleType MethodDeclaration SimpleName create middle marker
proxy graphics node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName prev
proxy graphics node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
proxy graphics node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName prev seg type
proxy graphics node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName curr
proxy graphics node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
proxy graphics node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType double
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration SimpleName prev
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration SimpleName prev seg type
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType double
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration SimpleName curr
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType double
create middle marker SimpleName MethodDeclaration SingleVariableDeclaration SimpleName next
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev seg type
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
prev seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
prev seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
prev seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
prev seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
prev seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
curr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
curr seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
curr seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
curr seg type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
next SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
next SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName proxy graphics node
public Modifier TypeDeclaration MethodDeclaration SimpleName create middle marker
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev seg type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName proxy graphics node
test SimpleName TypeDeclaration MethodDeclaration SimpleName create middle marker
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prev seg type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName curr seg type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName next seg type
