float PrimitiveType SingleVariableDeclaration SimpleName x
float PrimitiveType SingleVariableDeclaration SimpleName y
last abs SimpleName MethodInvocation SimpleName get path seg type
last abs SimpleName MethodInvocation InfixExpression QualifiedName svg path segpathseg curveto quadratic abs
get path seg type SimpleName MethodInvocation InfixExpression QualifiedName svg path segpathseg curveto quadratic abs
last abs SimpleName MethodInvocation SimpleName get x
last abs SimpleName MethodInvocation SimpleName get x
last abs SimpleName MethodInvocation SimpleName get x
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName last abs
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get x
get x SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName last abs
get x SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get x
last abs SimpleName MethodInvocation SimpleName get y
last abs SimpleName MethodInvocation SimpleName get y
last abs SimpleName MethodInvocation SimpleName get y
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName last abs
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get y
get y SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName last abs
get y SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get y
curveto quadratic abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName last abs
curveto quadratic abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get x
curveto quadratic abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName last abs
curveto quadratic abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get y
curveto quadratic abs SimpleName MethodInvocation SimpleName x
curveto quadratic abs SimpleName MethodInvocation SimpleName y
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName x
get x SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName x
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName y
get x SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName y
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName x
get y SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName x
last abs SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName y
get y SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName y
x SimpleName MethodInvocation SimpleName y
last abs SimpleName MethodInvocation SimpleName get x
last abs SimpleName MethodInvocation SimpleName get y
curveto quadratic abs SimpleName MethodInvocation MethodInvocation SimpleName last abs
curveto quadratic abs SimpleName MethodInvocation MethodInvocation SimpleName get x
curveto quadratic abs SimpleName MethodInvocation MethodInvocation SimpleName last abs
curveto quadratic abs SimpleName MethodInvocation MethodInvocation SimpleName get y
curveto quadratic abs SimpleName MethodInvocation SimpleName x
curveto quadratic abs SimpleName MethodInvocation SimpleName y
last abs SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName last abs
last abs SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get y
get x SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName last abs
get x SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get y
last abs SimpleName MethodInvocation MethodInvocation SimpleName x
get x SimpleName MethodInvocation MethodInvocation SimpleName x
last abs SimpleName MethodInvocation MethodInvocation SimpleName y
get x SimpleName MethodInvocation MethodInvocation SimpleName y
last abs SimpleName MethodInvocation MethodInvocation SimpleName x
get y SimpleName MethodInvocation MethodInvocation SimpleName x
last abs SimpleName MethodInvocation MethodInvocation SimpleName y
get y SimpleName MethodInvocation MethodInvocation SimpleName y
x SimpleName MethodInvocation SimpleName y
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName curveto quadratic smooth abs
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName x
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName y
public Modifier MethodDeclaration SimpleType SimpleName parse exception
void PrimitiveType MethodDeclaration SimpleName curveto quadratic smooth abs
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType float
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName x
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType float
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName y
void PrimitiveType MethodDeclaration SimpleType SimpleName parse exception
curveto quadratic smooth abs SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType float
curveto quadratic smooth abs SimpleName MethodDeclaration SingleVariableDeclaration SimpleName x
curveto quadratic smooth abs SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType float
curveto quadratic smooth abs SimpleName MethodDeclaration SingleVariableDeclaration SimpleName y
curveto quadratic smooth abs SimpleName MethodDeclaration SimpleType SimpleName parse exception
float PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
float PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName y
x SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
x SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName y
float PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName parse exception
x SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName parse exception
float PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName parse exception
y SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName parse exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName curveto quadratic smooth abs
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName x
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName y
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName parse exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName curveto quadratic smooth abs
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName x
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName y
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName parse exception
