string SimpleName SimpleType SingleVariableDeclaration SimpleName attr name
date SimpleName SimpleType SingleVariableDeclaration SimpleName val
void PrimitiveType MethodDeclaration SimpleName set date
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName attr name
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName date
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName val
void PrimitiveType MethodDeclaration SimpleType SimpleName metadata exception
set date SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
set date SimpleName MethodDeclaration SingleVariableDeclaration SimpleName attr name
set date SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName date
set date SimpleName MethodDeclaration SingleVariableDeclaration SimpleName val
set date SimpleName MethodDeclaration SimpleType SimpleName metadata exception
attr name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
attr name SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName metadata exception
val SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName metadata exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set date
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attr name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName metadata exception
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set date
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attr name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName metadata exception
