suppress warnings SimpleName SingleMemberAnnotation StringLiteral syntheticaccess
writes SimpleName MethodInvocation SimpleName peek
future SimpleName VariableDeclarationFragment MethodInvocation SimpleName writes
future SimpleName VariableDeclarationFragment MethodInvocation SimpleName peek
final Modifier VariableDeclarationStatement SimpleType SimpleName nio default io write future
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName future
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName writes
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName peek
nio default io write future SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName future
current write SimpleName MethodInvocation SimpleName compare and set
current write SimpleName MethodInvocation SimpleName future
compare and set SimpleName MethodInvocation SimpleName future
future SimpleName MethodInvocation SimpleName get buffer
buffer SimpleName VariableDeclarationFragment MethodInvocation SimpleName future
buffer SimpleName VariableDeclarationFragment MethodInvocation SimpleName get buffer
final Modifier VariableDeclarationStatement SimpleType SimpleName byte buffer
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName buffer
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName future
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get buffer
byte buffer SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName buffer
nio completion handler SimpleName SimpleType ParameterizedType SimpleType SimpleName integer
nio completion handler SimpleName SimpleType ParameterizedType SimpleType SimpleName object
integer SimpleName SimpleType ParameterizedType SimpleType SimpleName object
integer SimpleName SimpleType SingleVariableDeclaration SimpleName result
object SimpleName SimpleType SingleVariableDeclaration SimpleName attachment
buffer SimpleName MethodInvocation SimpleName has remaining
socket SimpleName MethodInvocation SimpleName write
socket SimpleName MethodInvocation SimpleName buffer
write SimpleName MethodInvocation SimpleName buffer
throwable SimpleName SimpleType SingleVariableDeclaration SimpleName t
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral exception caught while writing
log SimpleName MethodInvocation SimpleName t
debug SimpleName MethodInvocation StringLiteral exception caught while writing
debug SimpleName MethodInvocation SimpleName t
exception caught while writing StringLiteral MethodInvocation SimpleName t
future SimpleName MethodInvocation SimpleName set written
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral finished writing
debug SimpleName MethodInvocation StringLiteral finished writing
future SimpleName MethodInvocation SimpleName set written
override SimpleName MarkerAnnotation MethodDeclaration Modifier protected
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName on completed
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName result
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName attachment
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName on completed
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName integer
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName result
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName attachment
void PrimitiveType MethodDeclaration SimpleName on completed
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName integer
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName result
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName attachment
on completed SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName integer
on completed SimpleName MethodDeclaration SingleVariableDeclaration SimpleName result
on completed SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
on completed SimpleName MethodDeclaration SingleVariableDeclaration SimpleName attachment
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attachment
throwable SimpleName SimpleType SingleVariableDeclaration SimpleName exc
object SimpleName SimpleType SingleVariableDeclaration SimpleName attachment
future SimpleName MethodInvocation SimpleName set exception
future SimpleName MethodInvocation SimpleName exc
set exception SimpleName MethodInvocation SimpleName exc
exception caught SimpleName MethodInvocation SimpleName exc
override SimpleName MarkerAnnotation MethodDeclaration Modifier protected
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName on failed
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName exc
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName attachment
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName on failed
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName throwable
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName exc
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName attachment
void PrimitiveType MethodDeclaration SimpleName on failed
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName throwable
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName exc
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName attachment
on failed SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName throwable
on failed SimpleName MethodDeclaration SingleVariableDeclaration SimpleName exc
on failed SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
on failed SimpleName MethodDeclaration SingleVariableDeclaration SimpleName attachment
exc SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attachment
writes SimpleName MethodInvocation SimpleName remove
writes SimpleName MethodInvocation SimpleName future
remove SimpleName MethodInvocation SimpleName future
current write SimpleName MethodInvocation SimpleName compare and set
current write SimpleName MethodInvocation SimpleName future
compare and set SimpleName MethodInvocation SimpleName future
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName finish write
void PrimitiveType MethodDeclaration SimpleName finish write
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier protected
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName on failed
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier protected
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName on failed
on completed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier protected
on completed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
on completed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName on failed
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier private
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName finish write
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier private
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName finish write
on completed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier private
on completed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
on completed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName finish write
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier private
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName finish write
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier private
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
void PrimitiveType MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName finish write
on failed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration Modifier private
on failed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration PrimitiveType void
on failed SimpleName MethodDeclaration AnonymousClassDeclaration MethodDeclaration SimpleName finish write
socket SimpleName MethodInvocation SimpleName write
socket SimpleName MethodInvocation SimpleName buffer
write SimpleName MethodInvocation SimpleName buffer
runtime exception SimpleName SimpleType SingleVariableDeclaration SimpleName e
future SimpleName MethodInvocation SimpleName set written
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration Modifier private
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration Modifier private
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration PrimitiveType void
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration PrimitiveType void
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration SimpleName start writing
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration SimpleName start writing
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName start writing
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
void PrimitiveType MethodDeclaration SimpleName start writing
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement Modifier final
start writing SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName start writing
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName start writing
