string SimpleName SimpleType SingleVariableDeclaration SimpleName attr name
int PrimitiveType SingleVariableDeclaration SimpleName val
field mappingfields QualifiedName MethodInvocation SimpleName get
field mappingfields QualifiedName MethodInvocation SimpleName attr name
get SimpleName MethodInvocation SimpleName attr name
i SimpleName VariableDeclarationFragment MethodInvocation QualifiedName field mappingfields
i SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
i SimpleName VariableDeclarationFragment MethodInvocation SimpleName attr name
attribute info SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName i
string SimpleName MethodInvocation SimpleName format
string SimpleName MethodInvocation StringLiteral unknown field s for struct s
string SimpleName MethodInvocation SimpleName attr name
string SimpleName MethodInvocation MethodInvocation SimpleName get type name
format SimpleName MethodInvocation StringLiteral unknown field s for struct s
format SimpleName MethodInvocation SimpleName attr name
format SimpleName MethodInvocation MethodInvocation SimpleName get type name
unknown field s for struct s StringLiteral MethodInvocation SimpleName attr name
unknown field s for struct s StringLiteral MethodInvocation MethodInvocation SimpleName get type name
attr name SimpleName MethodInvocation MethodInvocation SimpleName get type name
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName string
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName format
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation StringLiteral unknown field s for struct s
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName attr name
i SimpleName MethodInvocation SimpleName data type
i SimpleName MethodInvocation InfixExpression QualifiedName data typesint type
data type SimpleName MethodInvocation InfixExpression QualifiedName data typesint type
i SimpleName MethodInvocation SimpleName data type
i SimpleName MethodInvocation InstanceofExpression SimpleType SimpleName enum type
data type SimpleName MethodInvocation InstanceofExpression SimpleType SimpleName enum type
data typesint type QualifiedName MethodInvocation SimpleName get name
string SimpleName MethodInvocation SimpleName format
string SimpleName MethodInvocation StringLiteral field s for struct s is not a s call generic set method
string SimpleName MethodInvocation SimpleName attr name
string SimpleName MethodInvocation MethodInvocation SimpleName get type name
string SimpleName MethodInvocation MethodInvocation QualifiedName data typesint type
string SimpleName MethodInvocation MethodInvocation SimpleName get name
format SimpleName MethodInvocation StringLiteral field s for struct s is not a s call generic set method
format SimpleName MethodInvocation SimpleName attr name
format SimpleName MethodInvocation MethodInvocation SimpleName get type name
format SimpleName MethodInvocation MethodInvocation QualifiedName data typesint type
format SimpleName MethodInvocation MethodInvocation SimpleName get name
field s for struct s is not a s call generic set method StringLiteral MethodInvocation SimpleName attr name
field s for struct s is not a s call generic set method StringLiteral MethodInvocation MethodInvocation SimpleName get type name
field s for struct s is not a s call generic set method StringLiteral MethodInvocation MethodInvocation QualifiedName data typesint type
field s for struct s is not a s call generic set method StringLiteral MethodInvocation MethodInvocation SimpleName get name
attr name SimpleName MethodInvocation MethodInvocation SimpleName get type name
attr name SimpleName MethodInvocation MethodInvocation QualifiedName data typesint type
attr name SimpleName MethodInvocation MethodInvocation SimpleName get name
get type name SimpleName MethodInvocation MethodInvocation MethodInvocation QualifiedName data typesint type
get type name SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName string
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName format
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation StringLiteral field s for struct s is not a s call generic set method
atlas exception SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName attr name
field mappingfield pos QualifiedName MethodInvocation SimpleName get
field mappingfield pos QualifiedName MethodInvocation SimpleName attr name
get SimpleName MethodInvocation SimpleName attr name
pos SimpleName VariableDeclarationFragment MethodInvocation QualifiedName field mappingfield pos
pos SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
pos SimpleName VariableDeclarationFragment MethodInvocation SimpleName attr name
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName pos
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation QualifiedName field mappingfield pos
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName attr name
field mappingfield null pos QualifiedName MethodInvocation SimpleName get
field mappingfield null pos QualifiedName MethodInvocation SimpleName attr name
get SimpleName MethodInvocation SimpleName attr name
null pos SimpleName VariableDeclarationFragment MethodInvocation QualifiedName field mappingfield null pos
null pos SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
null pos SimpleName VariableDeclarationFragment MethodInvocation SimpleName attr name
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName null pos
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation QualifiedName field mappingfield null pos
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName attr name
null flags SimpleName ArrayAccess SimpleName null pos
null flags SimpleName ArrayAccess Assignment BooleanLiteral false
null pos SimpleName ArrayAccess Assignment BooleanLiteral false
ints SimpleName ArrayAccess SimpleName pos
ints SimpleName ArrayAccess Assignment SimpleName val
pos SimpleName ArrayAccess Assignment SimpleName val
explicit sets SimpleName ArrayAccess SimpleName null pos
explicit sets SimpleName ArrayAccess Assignment BooleanLiteral true
null pos SimpleName ArrayAccess Assignment BooleanLiteral true
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName attr name
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName val
public Modifier MethodDeclaration SimpleType SimpleName atlas exception
void PrimitiveType MethodDeclaration SimpleName set int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName attr name
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName val
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas exception
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
set int SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
set int SimpleName MethodDeclaration SingleVariableDeclaration SimpleName attr name
set int SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
set int SimpleName MethodDeclaration SingleVariableDeclaration SimpleName val
set int SimpleName MethodDeclaration SimpleType SimpleName atlas exception
set int SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
set int SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
attr name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
attr name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
attr name SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
val SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attr name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attr name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
