groovy expression SimpleName SimpleType SingleVariableDeclaration SimpleName parent
graph persistence strategies SimpleName SimpleType SingleVariableDeclaration SimpleName s
i data type SimpleName SimpleType SingleVariableDeclaration SimpleName data type
groovy expression SimpleName SimpleType SingleVariableDeclaration SimpleName loop expr
string SimpleName SimpleType SingleVariableDeclaration SimpleName alias
integer SimpleName SimpleType SingleVariableDeclaration SimpleName times
generate loop emit expression SimpleName MethodInvocation SimpleName s
generate loop emit expression SimpleName MethodInvocation SimpleName data type
s SimpleName MethodInvocation SimpleName data type
emit expr SimpleName VariableDeclarationFragment MethodInvocation SimpleName generate loop emit expression
emit expr SimpleName VariableDeclarationFragment MethodInvocation SimpleName s
emit expr SimpleName VariableDeclarationFragment MethodInvocation SimpleName data type
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName emit expr
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName while function
field expression SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName get it variable
field expression SimpleName SimpleType ClassInstanceCreation SimpleName loop count field
get it variable SimpleName MethodInvocation ClassInstanceCreation SimpleName loop count field
loops expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName field expression
loops expr SimpleName VariableDeclarationFragment ClassInstanceCreation MethodInvocation SimpleName get it variable
loops expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName loop count field
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName loops expr
literal expression SimpleName SimpleType ClassInstanceCreation SimpleName times
times expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName literal expression
times expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName times
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName times expr
comparison expression SimpleName SimpleType ClassInstanceCreation SimpleName loops expr
comparison expression SimpleName SimpleType ClassInstanceCreation QualifiedName comparison operatorless than
comparison expression SimpleName SimpleType ClassInstanceCreation SimpleName times expr
loops expr SimpleName ClassInstanceCreation QualifiedName comparison operatorless than
loops expr SimpleName ClassInstanceCreation SimpleName times expr
comparison operatorless than QualifiedName ClassInstanceCreation SimpleName times expr
closure expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation SimpleName loops expr
closure expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation QualifiedName comparison operatorless than
closure expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation SimpleName times expr
while function SimpleName Assignment ClassInstanceCreation SimpleType SimpleName closure expression
while function SimpleName Assignment ClassInstanceCreation ClassInstanceCreation SimpleName loops expr
while function SimpleName Assignment ClassInstanceCreation ClassInstanceCreation QualifiedName comparison operatorless than
while function SimpleName Assignment ClassInstanceCreation ClassInstanceCreation SimpleName times expr
field expression SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName get it variable
field expression SimpleName SimpleType ClassInstanceCreation SimpleName path field
get it variable SimpleName MethodInvocation ClassInstanceCreation SimpleName path field
path expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName field expression
path expr SimpleName VariableDeclarationFragment ClassInstanceCreation MethodInvocation SimpleName get it variable
path expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName path field
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName path expr
it object expr SimpleName VariableDeclarationFragment MethodInvocation SimpleName get current object expression
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName it object expr
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName path expr
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName contains
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName it object expr
path expr SimpleName ClassInstanceCreation SimpleName contains
path expr SimpleName ClassInstanceCreation SimpleName it object expr
contains SimpleName ClassInstanceCreation SimpleName it object expr
path contains expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName function call expression
path contains expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName path expr
path contains expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName contains
path contains expr SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName it object expr
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName path contains expr
ternary operator expression SimpleName SimpleType ClassInstanceCreation SimpleName path contains expr
ternary operator expression SimpleName SimpleType ClassInstanceCreation QualifiedName literal expressionfalse
ternary operator expression SimpleName SimpleType ClassInstanceCreation QualifiedName literal expressiontrue
path contains expr SimpleName ClassInstanceCreation QualifiedName literal expressionfalse
path contains expr SimpleName ClassInstanceCreation QualifiedName literal expressiontrue
literal expressionfalse QualifiedName ClassInstanceCreation QualifiedName literal expressiontrue
closure expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation SimpleName path contains expr
closure expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation QualifiedName literal expressionfalse
closure expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation QualifiedName literal expressiontrue
while function SimpleName Assignment ClassInstanceCreation SimpleType SimpleName closure expression
while function SimpleName Assignment ClassInstanceCreation ClassInstanceCreation SimpleName path contains expr
while function SimpleName Assignment ClassInstanceCreation ClassInstanceCreation QualifiedName literal expressionfalse
while function SimpleName Assignment ClassInstanceCreation ClassInstanceCreation QualifiedName literal expressiontrue
closure expression SimpleName SimpleType ClassInstanceCreation SimpleName emit expr
emit function SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName closure expression
emit function SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName emit expr
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName emit function
literal expression SimpleName SimpleType ClassInstanceCreation SimpleName alias
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName loop expr
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName loop method
function call expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation SimpleName alias
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName while function
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName emit function
loop expr SimpleName ClassInstanceCreation SimpleName loop method
loop expr SimpleName ClassInstanceCreation ClassInstanceCreation SimpleType SimpleName literal expression
loop expr SimpleName ClassInstanceCreation ClassInstanceCreation SimpleName alias
loop expr SimpleName ClassInstanceCreation SimpleName while function
loop expr SimpleName ClassInstanceCreation SimpleName emit function
loop method SimpleName ClassInstanceCreation ClassInstanceCreation SimpleType SimpleName literal expression
loop method SimpleName ClassInstanceCreation ClassInstanceCreation SimpleName alias
loop method SimpleName ClassInstanceCreation SimpleName while function
loop method SimpleName ClassInstanceCreation SimpleName emit function
literal expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation SimpleName while function
alias SimpleName ClassInstanceCreation ClassInstanceCreation SimpleName while function
literal expression SimpleName SimpleType ClassInstanceCreation ClassInstanceCreation SimpleName emit function
alias SimpleName ClassInstanceCreation ClassInstanceCreation SimpleName emit function
while function SimpleName ClassInstanceCreation SimpleName emit function
loop call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName function call expression
loop call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName loop expr
loop call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName loop method
loop call SimpleName VariableDeclarationFragment ClassInstanceCreation ClassInstanceCreation SimpleName alias
loop call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName while function
loop call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName emit function
groovy expression SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName loop call
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName loop call
function call expression SimpleName SimpleType ClassInstanceCreation SimpleName enable path method
loop call SimpleName ClassInstanceCreation SimpleName enable path method
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName groovy expression
override SimpleName MarkerAnnotation MethodDeclaration SimpleName generate loop expression
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName parent
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier MethodDeclaration SimpleType SimpleName groovy expression
public Modifier MethodDeclaration SimpleName generate loop expression
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName groovy expression
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName parent
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName graph persistence strategies
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i data type
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName data type
groovy expression SimpleName SimpleType MethodDeclaration SimpleName generate loop expression
groovy expression SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName parent
groovy expression SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName s
groovy expression SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName data type
groovy expression SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName loop expr
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName groovy expression
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleName parent
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName graph persistence strategies
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleName s
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i data type
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleName data type
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName groovy expression
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleName loop expr
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
generate loop expression SimpleName MethodDeclaration SingleVariableDeclaration SimpleName alias
parent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
parent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data type
parent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName loop expr
parent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName alias
parent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data type
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName loop expr
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName alias
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
data type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName loop expr
data type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName alias
data type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
loop expr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName alias
loop expr SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
alias SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName groovy expression
public Modifier TypeDeclaration MethodDeclaration SimpleName generate loop expression
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName parent
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName loop expr
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName alias
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName groovy expression
test SimpleName TypeDeclaration MethodDeclaration SimpleName generate loop expression
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName parent
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName loop expr
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName alias
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName times
