string SimpleName SimpleType SingleVariableDeclaration SimpleName s
s SimpleName MethodInvocation SimpleName trim
public Modifier MethodDeclaration Modifier static
public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName trim to empty
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName s
static Modifier MethodDeclaration SimpleType SimpleName string
static Modifier MethodDeclaration SimpleName trim to empty
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName s
string SimpleName SimpleType MethodDeclaration SimpleName trim to empty
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName s
trim to empty SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
trim to empty SimpleName MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName trim to empty
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName trim to empty
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
