shape SimpleName SimpleType MethodDeclaration SimpleName get shape
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName shape
public Modifier TypeDeclaration MethodDeclaration SimpleName get shape
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName shape
test SimpleName TypeDeclaration MethodDeclaration SimpleName get shape
