public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName get font stretch
string SimpleName SimpleType MethodDeclaration SimpleName get font stretch
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName get font stretch
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName get font stretch
