int PrimitiveType SingleVariableDeclaration SimpleName seed
seed SimpleName InfixExpression SimpleName rand q
rand a SimpleName InfixExpression ParenthesizedExpression InfixExpression SimpleName seed
rand a SimpleName InfixExpression ParenthesizedExpression InfixExpression SimpleName rand q
seed SimpleName InfixExpression SimpleName rand q
rand r SimpleName InfixExpression ParenthesizedExpression InfixExpression SimpleName seed
rand r SimpleName InfixExpression ParenthesizedExpression InfixExpression SimpleName rand q
rand a SimpleName InfixExpression InfixExpression InfixExpression SimpleName rand r
result SimpleName VariableDeclarationFragment InfixExpression InfixExpression SimpleName rand a
result SimpleName VariableDeclarationFragment InfixExpression InfixExpression SimpleName rand r
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName result
result SimpleName InfixExpression NumberLiteral empty
result SimpleName Assignment SimpleName rand m
int PrimitiveType VariableDeclarationStatement Block ReturnStatement SimpleName result
public Modifier MethodDeclaration Modifier final
public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName random
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName seed
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block ReturnStatement SimpleName result
final Modifier MethodDeclaration PrimitiveType int
final Modifier MethodDeclaration SimpleName random
final Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
final Modifier MethodDeclaration SingleVariableDeclaration SimpleName seed
final Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
final Modifier MethodDeclaration Block ReturnStatement SimpleName result
int PrimitiveType MethodDeclaration SimpleName random
int PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName seed
int PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType MethodDeclaration Block ReturnStatement SimpleName result
random SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
random SimpleName MethodDeclaration SingleVariableDeclaration SimpleName seed
random SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
random SimpleName MethodDeclaration Block ReturnStatement SimpleName result
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName random
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName seed
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName random
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName seed
