last ret SimpleName InfixExpression PrefixExpression NumberLiteral empty
concrete composite graphics node SimpleName ThisExpression MethodInvocation SimpleName remove
concrete composite graphics node SimpleName ThisExpression MethodInvocation SimpleName last ret
remove SimpleName MethodInvocation SimpleName last ret
last ret SimpleName InfixExpression SimpleName cursor
last ret SimpleName Assignment PrefixExpression NumberLiteral empty
expected mod count SimpleName Assignment SimpleName mod count
index out of bounds exception SimpleName SimpleType SingleVariableDeclaration SimpleName e
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName remove
void PrimitiveType MethodDeclaration SimpleName remove
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName remove
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName remove
