get parent selector SimpleName MethodInvocation InfixExpression StringLiteral +
get parent selector SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get simple selector
+ StringLiteral InfixExpression MethodInvocation SimpleName get simple selector
public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName to string
string SimpleName SimpleType MethodDeclaration SimpleName to string
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName to string
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName to string
