element SimpleName SimpleType SingleVariableDeclaration SimpleName element
list SimpleName SimpleType MethodDeclaration SimpleName get style reference list
list SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName element
get style reference list SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName element
get style reference list SimpleName MethodDeclaration SingleVariableDeclaration SimpleName element
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName list
public Modifier TypeDeclaration MethodDeclaration SimpleName get style reference list
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName element
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName list
test SimpleName TypeDeclaration MethodDeclaration SimpleName get style reference list
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName element
