composite shape painter SimpleName SimpleType MethodDeclaration SimpleName create composite shape painter
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName composite shape painter
public Modifier TypeDeclaration MethodDeclaration SimpleName create composite shape painter
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName composite shape painter
test SimpleName TypeDeclaration MethodDeclaration SimpleName create composite shape painter
