int PrimitiveType SingleVariableDeclaration SimpleName src index
rectangle SimpleName SimpleType SingleVariableDeclaration SimpleName output rgn
public Modifier MethodDeclaration SimpleType SimpleName shape
public Modifier MethodDeclaration SimpleName get dependency region
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName src index
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName rectangle
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName output rgn
shape SimpleName SimpleType MethodDeclaration SimpleName get dependency region
shape SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
shape SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName src index
shape SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName output rgn
get dependency region SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
get dependency region SimpleName MethodDeclaration SingleVariableDeclaration SimpleName src index
get dependency region SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName rectangle
get dependency region SimpleName MethodDeclaration SingleVariableDeclaration SimpleName output rgn
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output rgn
src index SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output rgn
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName shape
public Modifier TypeDeclaration MethodDeclaration SimpleName get dependency region
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName src index
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output rgn
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName shape
test SimpleName TypeDeclaration MethodDeclaration SimpleName get dependency region
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName src index
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output rgn
