attribute modifier SimpleName SimpleType SingleVariableDeclaration SimpleName am
attribute modifier SimpleName Assignment SimpleName am
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set attribute modifier
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName attribute modifier
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName am
void PrimitiveType MethodDeclaration SimpleName set attribute modifier
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName attribute modifier
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName am
set attribute modifier SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName attribute modifier
set attribute modifier SimpleName MethodDeclaration SingleVariableDeclaration SimpleName am
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set attribute modifier
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName am
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set attribute modifier
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName am
