buffer size SimpleName Assignment NumberLiteral empty
current SimpleName InfixExpression PrefixExpression NumberLiteral empty
report error SimpleName MethodInvocation StringLiteral endofstream
current SimpleName SwitchStatement SwitchCase NumberLiteral x
current SimpleName SwitchStatement SwitchCase NumberLiteral x
current SimpleName SwitchStatement SwitchCase NumberLiteral x d
current SimpleName SwitchStatement SwitchCase NumberLiteral x a
current SimpleName SwitchStatement SwitchCase CharacterLiteral empty
x NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral x
x NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral x d
x NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral x a
x NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral empty
x NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral )
x NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral x d
x NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral x a
x NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral empty
x NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral )
x d NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral x a
x d NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral empty
x d NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral )
x a NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral empty
x a NumberLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral )
empty CharacterLiteral SwitchCase SwitchStatement SwitchCase CharacterLiteral )
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName read number
protected Modifier MethodDeclaration SimpleType SimpleName parse exception
void PrimitiveType MethodDeclaration SimpleName read number
void PrimitiveType MethodDeclaration SimpleType SimpleName parse exception
read number SimpleName MethodDeclaration SimpleType SimpleName parse exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName read number
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName parse exception
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName read number
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName parse exception
