titan graph SimpleName SimpleType SingleVariableDeclaration SimpleName graph
vertex SimpleName SimpleType SingleVariableDeclaration SimpleName source
titan vertex SimpleName SimpleType ClassInstanceCreation SimpleName graph
titan vertex SimpleName SimpleType ClassInstanceCreation SimpleName source
graph SimpleName ClassInstanceCreation SimpleName source
public Modifier MethodDeclaration Modifier static
public Modifier MethodDeclaration SimpleType SimpleName titan vertex
public Modifier MethodDeclaration SimpleName create vertex
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName titan graph
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName graph
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName vertex
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName source
static Modifier MethodDeclaration SimpleType SimpleName titan vertex
static Modifier MethodDeclaration SimpleName create vertex
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName titan graph
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName graph
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName vertex
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName source
titan vertex SimpleName SimpleType MethodDeclaration SimpleName create vertex
titan vertex SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName graph
titan vertex SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName source
create vertex SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName titan graph
create vertex SimpleName MethodDeclaration SingleVariableDeclaration SimpleName graph
create vertex SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName vertex
create vertex SimpleName MethodDeclaration SingleVariableDeclaration SimpleName source
graph SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName source
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName titan vertex
public Modifier TypeDeclaration MethodDeclaration SimpleName create vertex
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName graph
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName source
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName titan vertex
test SimpleName TypeDeclaration MethodDeclaration SimpleName create vertex
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName graph
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName source
