string SimpleName SimpleType SingleVariableDeclaration SimpleName namespace uri arg
string SimpleName SimpleType SingleVariableDeclaration SimpleName event type arg
boolean PrimitiveType SingleVariableDeclaration SimpleName can bubble arg
boolean PrimitiveType SingleVariableDeclaration SimpleName cancelable arg
namespace uri SimpleName Assignment SimpleName namespace uri arg
type SimpleName Assignment SimpleName event type arg
is bubbling SimpleName Assignment SimpleName can bubble arg
cancelable SimpleName Assignment SimpleName cancelable arg
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName init event ns
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName namespace uri arg
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName event type arg
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
void PrimitiveType MethodDeclaration SimpleName init event ns
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName namespace uri arg
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName event type arg
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
init event ns SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
init event ns SimpleName MethodDeclaration SingleVariableDeclaration SimpleName namespace uri arg
init event ns SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
init event ns SimpleName MethodDeclaration SingleVariableDeclaration SimpleName event type arg
init event ns SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
init event ns SimpleName MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
init event ns SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
init event ns SimpleName MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
namespace uri arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName event type arg
namespace uri arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
namespace uri arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
namespace uri arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
namespace uri arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
event type arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
event type arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
event type arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
event type arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
can bubble arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
can bubble arg SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName init event ns
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace uri arg
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName event type arg
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName init event ns
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace uri arg
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName event type arg
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName can bubble arg
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cancelable arg
