expected SimpleName MethodInvocation SimpleName get algorithm
algorithm SimpleName VariableDeclarationFragment MethodInvocation SimpleName expected
algorithm SimpleName VariableDeclarationFragment MethodInvocation SimpleName get algorithm
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName algorithm
index SimpleName VariableDeclarationFragment NumberLiteral empty
algorithm SimpleName MethodInvocation SimpleName length
count SimpleName VariableDeclarationFragment MethodInvocation SimpleName algorithm
count SimpleName VariableDeclarationFragment MethodInvocation SimpleName length
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName index
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName count
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment MethodInvocation SimpleName algorithm
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment MethodInvocation SimpleName length
index SimpleName VariableDeclarationFragment VariableDeclarationExpression VariableDeclarationFragment SimpleName count
empty NumberLiteral VariableDeclarationFragment VariableDeclarationExpression VariableDeclarationFragment SimpleName count
index SimpleName InfixExpression SimpleName count
builtin identities SimpleName MethodInvocation SimpleName from algorithm
builtin identities SimpleName MethodInvocation SimpleName algorithm
from algorithm SimpleName MethodInvocation SimpleName algorithm
assert same SimpleName MethodInvocation SimpleName algorithm
assert same SimpleName MethodInvocation SimpleName expected
assert same SimpleName MethodInvocation MethodInvocation SimpleName builtin identities
assert same SimpleName MethodInvocation MethodInvocation SimpleName from algorithm
assert same SimpleName MethodInvocation MethodInvocation SimpleName algorithm
algorithm SimpleName MethodInvocation SimpleName expected
algorithm SimpleName MethodInvocation MethodInvocation SimpleName builtin identities
algorithm SimpleName MethodInvocation MethodInvocation SimpleName from algorithm
algorithm SimpleName MethodInvocation MethodInvocation SimpleName algorithm
expected SimpleName MethodInvocation MethodInvocation SimpleName builtin identities
expected SimpleName MethodInvocation MethodInvocation SimpleName from algorithm
expected SimpleName MethodInvocation MethodInvocation SimpleName algorithm
shuffle case SimpleName MethodInvocation SimpleName algorithm
algorithm SimpleName Assignment MethodInvocation SimpleName shuffle case
algorithm SimpleName Assignment MethodInvocation SimpleName algorithm
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName index
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName count
int PrimitiveType VariableDeclarationExpression ForStatement PostfixExpression SimpleName index
index SimpleName InfixExpression ForStatement PostfixExpression SimpleName index
count SimpleName InfixExpression ForStatement PostfixExpression SimpleName index
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test from algorithm
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test from algorithm
void PrimitiveType MethodDeclaration SimpleName test from algorithm
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test from algorithm
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test from algorithm
