signal listener SimpleName SimpleType SingleVariableDeclaration SimpleName listener
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName remove signal listener
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName signal listener
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName listener
void PrimitiveType MethodDeclaration SimpleName remove signal listener
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName signal listener
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName listener
remove signal listener SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName signal listener
remove signal listener SimpleName MethodDeclaration SingleVariableDeclaration SimpleName listener
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName remove signal listener
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName listener
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName remove signal listener
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName listener
