i typed referenceable instance SimpleName SimpleType SingleVariableDeclaration SimpleName typed instance
set SimpleName SimpleType ParameterizedType SimpleType SimpleName string
set SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName super type names
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName super type names
typed instance SimpleName MethodInvocation SimpleName get type name
typed instance SimpleName MethodInvocation SimpleName get id
create vertex without identity SimpleName MethodInvocation MethodInvocation SimpleName typed instance
create vertex without identity SimpleName MethodInvocation MethodInvocation SimpleName get type name
create vertex without identity SimpleName MethodInvocation MethodInvocation SimpleName typed instance
create vertex without identity SimpleName MethodInvocation MethodInvocation SimpleName get id
create vertex without identity SimpleName MethodInvocation SimpleName super type names
typed instance SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName typed instance
typed instance SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
get type name SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName typed instance
get type name SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
typed instance SimpleName MethodInvocation MethodInvocation SimpleName super type names
get type name SimpleName MethodInvocation MethodInvocation SimpleName super type names
typed instance SimpleName MethodInvocation MethodInvocation SimpleName super type names
get id SimpleName MethodInvocation MethodInvocation SimpleName super type names
vertex with identity SimpleName VariableDeclarationFragment MethodInvocation SimpleName create vertex without identity
vertex with identity SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName typed instance
vertex with identity SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get type name
vertex with identity SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName typed instance
vertex with identity SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get id
vertex with identity SimpleName VariableDeclarationFragment MethodInvocation SimpleName super type names
final Modifier VariableDeclarationStatement SimpleType SimpleName vertex
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName vertex with identity
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName create vertex without identity
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName super type names
vertex SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName vertex with identity
uuid SimpleName MethodInvocation SimpleName random uuid
uuid SimpleName MethodInvocation MethodInvocation SimpleName to string
random uuid SimpleName MethodInvocation MethodInvocation SimpleName to string
guid SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName uuid
guid SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName random uuid
guid SimpleName VariableDeclarationFragment MethodInvocation SimpleName to string
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
final Modifier VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName to string
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
set property SimpleName MethodInvocation SimpleName vertex with identity
set property SimpleName MethodInvocation QualifiedName constantsguid property key
set property SimpleName MethodInvocation SimpleName guid
vertex with identity SimpleName MethodInvocation QualifiedName constantsguid property key
vertex with identity SimpleName MethodInvocation SimpleName guid
constantsguid property key QualifiedName MethodInvocation SimpleName guid
typed instance SimpleName MethodInvocation SimpleName get id
typed instance SimpleName MethodInvocation FieldAccess SimpleName version
get id SimpleName MethodInvocation FieldAccess SimpleName version
set property SimpleName MethodInvocation SimpleName vertex with identity
set property SimpleName MethodInvocation QualifiedName constantsversion property key
set property SimpleName MethodInvocation FieldAccess MethodInvocation SimpleName typed instance
set property SimpleName MethodInvocation FieldAccess MethodInvocation SimpleName get id
set property SimpleName MethodInvocation FieldAccess SimpleName version
vertex with identity SimpleName MethodInvocation QualifiedName constantsversion property key
vertex with identity SimpleName MethodInvocation FieldAccess MethodInvocation SimpleName typed instance
vertex with identity SimpleName MethodInvocation FieldAccess MethodInvocation SimpleName get id
vertex with identity SimpleName MethodInvocation FieldAccess SimpleName version
constantsversion property key QualifiedName MethodInvocation FieldAccess MethodInvocation SimpleName typed instance
constantsversion property key QualifiedName MethodInvocation FieldAccess MethodInvocation SimpleName get id
constantsversion property key QualifiedName MethodInvocation FieldAccess SimpleName version
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName vertex with identity
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName vertex with identity
public Modifier MethodDeclaration SimpleType SimpleName vertex
public Modifier MethodDeclaration SimpleName create vertex with identity
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i typed referenceable instance
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName typed instance
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName super type names
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier MethodDeclaration Block ReturnStatement SimpleName vertex with identity
vertex SimpleName SimpleType MethodDeclaration SimpleName create vertex with identity
vertex SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName typed instance
vertex SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName super type names
create vertex with identity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i typed referenceable instance
create vertex with identity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName typed instance
create vertex with identity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName super type names
create vertex with identity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
create vertex with identity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
create vertex with identity SimpleName MethodDeclaration Block ReturnStatement SimpleName vertex with identity
typed instance SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName super type names
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName vertex
public Modifier TypeDeclaration MethodDeclaration SimpleName create vertex with identity
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName typed instance
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName super type names
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName vertex
test SimpleName TypeDeclaration MethodDeclaration SimpleName create vertex with identity
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName typed instance
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName super type names
