i struct SimpleName SimpleType SingleVariableDeclaration SimpleName s
appendable SimpleName SimpleType SingleVariableDeclaration SimpleName buf
string SimpleName SimpleType SingleVariableDeclaration SimpleName prefix
type utils SimpleName MethodInvocation SimpleName output val
type utils SimpleName MethodInvocation StringLiteral {
type utils SimpleName MethodInvocation SimpleName buf
type utils SimpleName MethodInvocation SimpleName prefix
output val SimpleName MethodInvocation StringLiteral {
output val SimpleName MethodInvocation SimpleName buf
output val SimpleName MethodInvocation SimpleName prefix
{ StringLiteral MethodInvocation SimpleName buf
{ StringLiteral MethodInvocation SimpleName prefix
buf SimpleName MethodInvocation SimpleName prefix
type utils SimpleName MethodInvocation SimpleName output val
type utils SimpleName MethodInvocation StringLiteral null
type utils SimpleName MethodInvocation SimpleName buf
type utils SimpleName MethodInvocation StringLiteral empty
output val SimpleName MethodInvocation StringLiteral null
output val SimpleName MethodInvocation SimpleName buf
output val SimpleName MethodInvocation StringLiteral empty
null StringLiteral MethodInvocation SimpleName buf
null StringLiteral MethodInvocation StringLiteral empty
buf SimpleName MethodInvocation StringLiteral empty
type utils SimpleName MethodInvocation SimpleName output val
type utils SimpleName MethodInvocation StringLiteral empty
type utils SimpleName MethodInvocation SimpleName buf
type utils SimpleName MethodInvocation StringLiteral empty
output val SimpleName MethodInvocation StringLiteral empty
output val SimpleName MethodInvocation SimpleName buf
output val SimpleName MethodInvocation StringLiteral empty
empty StringLiteral MethodInvocation SimpleName buf
empty StringLiteral MethodInvocation StringLiteral empty
buf SimpleName MethodInvocation StringLiteral empty
prefix SimpleName InfixExpression StringLiteral t
field prefix SimpleName VariableDeclarationFragment InfixExpression SimpleName prefix
field prefix SimpleName VariableDeclarationFragment InfixExpression StringLiteral t
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName field prefix
mapentry QualifiedName SimpleType ParameterizedType SimpleType SimpleName string
mapentry QualifiedName SimpleType ParameterizedType SimpleType SimpleName attribute info
string SimpleName SimpleType ParameterizedType SimpleType SimpleName attribute info
mapentry QualifiedName SimpleType ParameterizedType SingleVariableDeclaration SimpleName e
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName e
attribute info SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName e
field mappingfields QualifiedName MethodInvocation SimpleName entry set
e SimpleName MethodInvocation SimpleName get key
attr name SimpleName VariableDeclarationFragment MethodInvocation SimpleName e
attr name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get key
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attr name
e SimpleName MethodInvocation SimpleName get value
i SimpleName VariableDeclarationFragment MethodInvocation SimpleName e
i SimpleName VariableDeclarationFragment MethodInvocation SimpleName get value
attribute info SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName i
s SimpleName MethodInvocation SimpleName get
s SimpleName MethodInvocation SimpleName attr name
get SimpleName MethodInvocation SimpleName attr name
a val SimpleName VariableDeclarationFragment MethodInvocation SimpleName s
a val SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
a val SimpleName VariableDeclarationFragment MethodInvocation SimpleName attr name
object SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName a val
attr name SimpleName InfixExpression StringLiteral :
type utils SimpleName MethodInvocation SimpleName output val
type utils SimpleName MethodInvocation InfixExpression SimpleName attr name
type utils SimpleName MethodInvocation InfixExpression StringLiteral :
type utils SimpleName MethodInvocation SimpleName buf
type utils SimpleName MethodInvocation SimpleName field prefix
output val SimpleName MethodInvocation InfixExpression SimpleName attr name
output val SimpleName MethodInvocation InfixExpression StringLiteral :
output val SimpleName MethodInvocation SimpleName buf
output val SimpleName MethodInvocation SimpleName field prefix
attr name SimpleName InfixExpression MethodInvocation SimpleName buf
: StringLiteral InfixExpression MethodInvocation SimpleName buf
attr name SimpleName InfixExpression MethodInvocation SimpleName field prefix
: StringLiteral InfixExpression MethodInvocation SimpleName field prefix
buf SimpleName MethodInvocation SimpleName field prefix
i SimpleName MethodInvocation SimpleName data type
i SimpleName MethodInvocation MethodInvocation SimpleName output
data type SimpleName MethodInvocation MethodInvocation SimpleName output
i SimpleName MethodInvocation MethodInvocation SimpleName a val
data type SimpleName MethodInvocation MethodInvocation SimpleName a val
i SimpleName MethodInvocation MethodInvocation SimpleName buf
data type SimpleName MethodInvocation MethodInvocation SimpleName buf
i SimpleName MethodInvocation MethodInvocation StringLiteral empty
data type SimpleName MethodInvocation MethodInvocation StringLiteral empty
output SimpleName MethodInvocation SimpleName a val
output SimpleName MethodInvocation SimpleName buf
output SimpleName MethodInvocation StringLiteral empty
a val SimpleName MethodInvocation SimpleName buf
a val SimpleName MethodInvocation StringLiteral empty
buf SimpleName MethodInvocation StringLiteral empty
type utils SimpleName MethodInvocation SimpleName output val
type utils SimpleName MethodInvocation StringLiteral empty
type utils SimpleName MethodInvocation SimpleName buf
type utils SimpleName MethodInvocation StringLiteral empty
output val SimpleName MethodInvocation StringLiteral empty
output val SimpleName MethodInvocation SimpleName buf
output val SimpleName MethodInvocation StringLiteral empty
empty StringLiteral MethodInvocation SimpleName buf
empty StringLiteral MethodInvocation StringLiteral empty
buf SimpleName MethodInvocation StringLiteral empty
e SimpleName SingleVariableDeclaration EnhancedForStatement MethodInvocation QualifiedName field mappingfields
e SimpleName SingleVariableDeclaration EnhancedForStatement MethodInvocation SimpleName entry set
type utils SimpleName MethodInvocation SimpleName output val
type utils SimpleName MethodInvocation StringLiteral }
type utils SimpleName MethodInvocation SimpleName buf
type utils SimpleName MethodInvocation StringLiteral empty
output val SimpleName MethodInvocation StringLiteral }
output val SimpleName MethodInvocation SimpleName buf
output val SimpleName MethodInvocation StringLiteral empty
} StringLiteral MethodInvocation SimpleName buf
} StringLiteral MethodInvocation StringLiteral empty
buf SimpleName MethodInvocation StringLiteral empty
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName output
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i struct
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName appendable
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName buf
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName prefix
void PrimitiveType MethodDeclaration SimpleName output
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i struct
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName s
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName appendable
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName buf
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName prefix
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas exception
output SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName i struct
output SimpleName MethodDeclaration SingleVariableDeclaration SimpleName s
output SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName appendable
output SimpleName MethodDeclaration SingleVariableDeclaration SimpleName buf
output SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
output SimpleName MethodDeclaration SingleVariableDeclaration SimpleName prefix
output SimpleName MethodDeclaration SimpleType SimpleName atlas exception
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buf
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prefix
s SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
buf SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prefix
buf SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
prefix SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName output
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buf
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prefix
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName output
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buf
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName prefix
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
