i data type SimpleName SimpleType ParameterizedType WildcardType ?
i data type SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName data type
? WildcardType ParameterizedType SingleVariableDeclaration SimpleName data type
attribute info SimpleName SimpleType SingleVariableDeclaration SimpleName a info
graph helper SimpleName MethodInvocation SimpleName get edge label
graph helper SimpleName MethodInvocation SimpleName data type
graph helper SimpleName MethodInvocation SimpleName a info
get edge label SimpleName MethodInvocation SimpleName data type
get edge label SimpleName MethodInvocation SimpleName a info
data type SimpleName MethodInvocation SimpleName a info
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName string
override SimpleName MarkerAnnotation MethodDeclaration SimpleName get edge label
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName data type
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName a info
public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName get edge label
public Modifier MethodDeclaration SingleVariableDeclaration ParameterizedType WildcardType ?
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName data type
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName attribute info
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName a info
public Modifier MethodDeclaration SimpleType SimpleName atlas exception
string SimpleName SimpleType MethodDeclaration SimpleName get edge label
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName data type
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName a info
string SimpleName SimpleType MethodDeclaration SimpleType SimpleName atlas exception
get edge label SimpleName MethodDeclaration SingleVariableDeclaration ParameterizedType WildcardType ?
get edge label SimpleName MethodDeclaration SingleVariableDeclaration SimpleName data type
get edge label SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName attribute info
get edge label SimpleName MethodDeclaration SingleVariableDeclaration SimpleName a info
get edge label SimpleName MethodDeclaration SimpleType SimpleName atlas exception
data type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName a info
data type SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
a info SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName get edge label
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName a info
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName get edge label
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName a info
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
