string SimpleName SimpleType SingleVariableDeclaration SimpleName message json
deserialize SimpleName SuperMethodInvocation SimpleName message json
ret SimpleName VariableDeclarationFragment SuperMethodInvocation SimpleName deserialize
ret SimpleName VariableDeclarationFragment SuperMethodInvocation SimpleName message json
final Modifier VariableDeclarationStatement SimpleType SimpleName entity notification
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName ret
final Modifier VariableDeclarationStatement VariableDeclarationFragment SuperMethodInvocation SimpleName deserialize
final Modifier VariableDeclarationStatement VariableDeclarationFragment SuperMethodInvocation SimpleName message json
entity notification SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName ret
ret SimpleName MethodInvocation SimpleName normalize
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName ret
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName entity notification
override SimpleName MarkerAnnotation MethodDeclaration SimpleName deserialize
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName message json
public Modifier MethodDeclaration SimpleType SimpleName entity notification
public Modifier MethodDeclaration SimpleName deserialize
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName message json
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier MethodDeclaration Block ReturnStatement SimpleName ret
entity notification SimpleName SimpleType MethodDeclaration SimpleName deserialize
entity notification SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName message json
deserialize SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
deserialize SimpleName MethodDeclaration SingleVariableDeclaration SimpleName message json
deserialize SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
deserialize SimpleName MethodDeclaration Block ReturnStatement SimpleName ret
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity notification
public Modifier TypeDeclaration MethodDeclaration SimpleName deserialize
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName message json
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity notification
test SimpleName TypeDeclaration MethodDeclaration SimpleName deserialize
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName message json
