public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName get upper
public Modifier MethodDeclaration Block ReturnStatement SimpleName upper
int PrimitiveType MethodDeclaration SimpleName get upper
int PrimitiveType MethodDeclaration Block ReturnStatement SimpleName upper
get upper SimpleName MethodDeclaration Block ReturnStatement SimpleName upper
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName get upper
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName get upper
