atlas vertex SimpleName SimpleType SingleVariableDeclaration SimpleName instance vertex
list SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas edge
get all classification edges SimpleName MethodInvocation SimpleName instance vertex
classification edges SimpleName VariableDeclarationFragment MethodInvocation SimpleName get all classification edges
classification edges SimpleName VariableDeclarationFragment MethodInvocation SimpleName instance vertex
atlas edge SimpleName SimpleType SingleVariableDeclaration SimpleName edge
edge SimpleName MethodInvocation SimpleName get in vertex
classification vertex SimpleName VariableDeclarationFragment MethodInvocation SimpleName edge
classification vertex SimpleName VariableDeclarationFragment MethodInvocation SimpleName get in vertex
atlas vertex SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName classification vertex
is classification edge SimpleName MethodInvocation SimpleName edge
is classification edge SimpleName VariableDeclarationFragment MethodInvocation SimpleName is classification edge
is classification edge SimpleName VariableDeclarationFragment MethodInvocation SimpleName edge
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName is classification edge
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName is classification edge
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName edge
get remove propagations SimpleName MethodInvocation SimpleName classification vertex
remove propagations SimpleName VariableDeclarationFragment MethodInvocation SimpleName get remove propagations
remove propagations SimpleName VariableDeclarationFragment MethodInvocation SimpleName classification vertex
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName remove propagations
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get remove propagations
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName classification vertex
is classification edge SimpleName InfixExpression SimpleName remove propagations
remove tag propagation SimpleName MethodInvocation SimpleName classification vertex
delete edge reference SimpleName MethodInvocation SimpleName edge
delete edge reference SimpleName MethodInvocation SimpleName classification
delete edge reference SimpleName MethodInvocation BooleanLiteral false
delete edge reference SimpleName MethodInvocation BooleanLiteral false
delete edge reference SimpleName MethodInvocation SimpleName instance vertex
edge SimpleName MethodInvocation SimpleName classification
edge SimpleName MethodInvocation BooleanLiteral false
edge SimpleName MethodInvocation BooleanLiteral false
edge SimpleName MethodInvocation SimpleName instance vertex
classification SimpleName MethodInvocation BooleanLiteral false
classification SimpleName MethodInvocation BooleanLiteral false
classification SimpleName MethodInvocation SimpleName instance vertex
false BooleanLiteral MethodInvocation BooleanLiteral false
false BooleanLiteral MethodInvocation SimpleName instance vertex
false BooleanLiteral MethodInvocation SimpleName instance vertex
boolean PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType boolean
atlas edge SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName classification edges
edge SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName classification edges
classification edges SimpleName EnhancedForStatement Block VariableDeclarationStatement PrimitiveType boolean
classification edges SimpleName EnhancedForStatement Block VariableDeclarationStatement PrimitiveType boolean
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName delete all classifications
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
private Modifier MethodDeclaration SimpleType SimpleName atlas base exception
private Modifier MethodDeclaration Block EnhancedForStatement SimpleName classification edges
void PrimitiveType MethodDeclaration SimpleName delete all classifications
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas base exception
void PrimitiveType MethodDeclaration Block EnhancedForStatement SimpleName classification edges
delete all classifications SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
delete all classifications SimpleName MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
delete all classifications SimpleName MethodDeclaration SimpleType SimpleName atlas base exception
delete all classifications SimpleName MethodDeclaration Block EnhancedForStatement SimpleName classification edges
instance vertex SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName delete all classifications
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName delete all classifications
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
