atlas vertex SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas janus vertex
atlas vertex SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas janus edge
atlas janus vertex SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas janus edge
source SimpleName MethodInvocation SimpleName get element
graph db object factory SimpleName MethodInvocation SimpleName create vertex
graph db object factory SimpleName MethodInvocation SimpleName graph
graph db object factory SimpleName MethodInvocation MethodInvocation SimpleName source
graph db object factory SimpleName MethodInvocation MethodInvocation SimpleName get element
create vertex SimpleName MethodInvocation SimpleName graph
create vertex SimpleName MethodInvocation MethodInvocation SimpleName source
create vertex SimpleName MethodInvocation MethodInvocation SimpleName get element
graph SimpleName MethodInvocation MethodInvocation SimpleName source
graph SimpleName MethodInvocation MethodInvocation SimpleName get element
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleName get vertex
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName atlas vertex
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName atlas janus vertex
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName atlas janus edge
public Modifier MethodDeclaration SimpleName get vertex
atlas vertex SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get vertex
atlas janus vertex SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get vertex
atlas janus edge SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get vertex
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleName get vertex
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleName get vertex
