session SimpleName MethodInvocation SimpleName is connected
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName is closed
boolean PrimitiveType MethodDeclaration SimpleName is closed
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName is closed
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName is closed
