attribute store SimpleName MethodInvocation SimpleName resolve attribute
attribute store SimpleName MethodInvocation CastExpression SimpleType SimpleName session
attribute store SimpleName MethodInvocation SimpleName key
resolve attribute SimpleName MethodInvocation CastExpression SimpleType SimpleName session
resolve attribute SimpleName MethodInvocation SimpleName key
session SimpleName SimpleType CastExpression MethodInvocation SimpleName key
assert null SimpleName MethodInvocation StringLiteral unexpected null session value
assert null SimpleName MethodInvocation MethodInvocation SimpleName attribute store
assert null SimpleName MethodInvocation MethodInvocation SimpleName resolve attribute
assert null SimpleName MethodInvocation MethodInvocation SimpleName key
unexpected null session value StringLiteral MethodInvocation MethodInvocation SimpleName attribute store
unexpected null session value StringLiteral MethodInvocation MethodInvocation SimpleName resolve attribute
unexpected null session value StringLiteral MethodInvocation MethodInvocation SimpleName key
mockito SimpleName MethodInvocation SimpleName mock
mockito SimpleName MethodInvocation TypeLiteral SimpleType SimpleName session
mock SimpleName MethodInvocation TypeLiteral SimpleType SimpleName session
session SimpleName VariableDeclarationFragment MethodInvocation SimpleName mockito
session SimpleName VariableDeclarationFragment MethodInvocation SimpleName mock
session SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName session
atomic integer SimpleName SimpleType ClassInstanceCreation NumberLiteral empty
manager count SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName atomic integer
manager count SimpleName VariableDeclarationFragment ClassInstanceCreation NumberLiteral empty
final Modifier VariableDeclarationStatement SimpleType SimpleName atomic integer
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName manager count
final Modifier VariableDeclarationStatement VariableDeclarationFragment ClassInstanceCreation NumberLiteral empty
atomic integer SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName manager count
session SimpleName MethodInvocation SimpleName get factory manager
mockito SimpleName MethodInvocation SimpleName when
mockito SimpleName MethodInvocation MethodInvocation SimpleName session
mockito SimpleName MethodInvocation MethodInvocation SimpleName get factory manager
when SimpleName MethodInvocation MethodInvocation SimpleName session
when SimpleName MethodInvocation MethodInvocation SimpleName get factory manager
manager count SimpleName MethodInvocation SimpleName increment and get
mockito SimpleName MethodInvocation MethodInvocation SimpleName then
when SimpleName MethodInvocation MethodInvocation SimpleName then
session SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName then
get factory manager SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName then
then SimpleName MethodInvocation LambdaExpression VariableDeclarationFragment SimpleName invocation
set attribute value SimpleName MethodInvocation SimpleName session
attribute store SimpleName MethodInvocation SimpleName resolve attribute
attribute store SimpleName MethodInvocation SimpleName session
attribute store SimpleName MethodInvocation SimpleName key
resolve attribute SimpleName MethodInvocation SimpleName session
resolve attribute SimpleName MethodInvocation SimpleName key
session SimpleName MethodInvocation SimpleName key
assert null SimpleName MethodInvocation StringLiteral unexpected success for empty attribute
assert null SimpleName MethodInvocation MethodInvocation SimpleName attribute store
assert null SimpleName MethodInvocation MethodInvocation SimpleName resolve attribute
assert null SimpleName MethodInvocation MethodInvocation SimpleName session
assert null SimpleName MethodInvocation MethodInvocation SimpleName key
unexpected success for empty attribute StringLiteral MethodInvocation MethodInvocation SimpleName attribute store
unexpected success for empty attribute StringLiteral MethodInvocation MethodInvocation SimpleName resolve attribute
unexpected success for empty attribute StringLiteral MethodInvocation MethodInvocation SimpleName session
unexpected success for empty attribute StringLiteral MethodInvocation MethodInvocation SimpleName key
manager count SimpleName MethodInvocation SimpleName get and set
manager count SimpleName MethodInvocation NumberLiteral empty
get and set SimpleName MethodInvocation NumberLiteral empty
assert equals SimpleName MethodInvocation StringLiteral factory manager not requested
assert equals SimpleName MethodInvocation NumberLiteral empty
assert equals SimpleName MethodInvocation MethodInvocation SimpleName manager count
assert equals SimpleName MethodInvocation MethodInvocation SimpleName get and set
assert equals SimpleName MethodInvocation MethodInvocation NumberLiteral empty
factory manager not requested StringLiteral MethodInvocation NumberLiteral empty
factory manager not requested StringLiteral MethodInvocation MethodInvocation SimpleName manager count
factory manager not requested StringLiteral MethodInvocation MethodInvocation SimpleName get and set
factory manager not requested StringLiteral MethodInvocation MethodInvocation NumberLiteral empty
empty NumberLiteral MethodInvocation MethodInvocation SimpleName manager count
empty NumberLiteral MethodInvocation MethodInvocation SimpleName get and set
empty NumberLiteral MethodInvocation MethodInvocation NumberLiteral empty
set attribute value SimpleName MethodInvocation SimpleName session
set attribute value SimpleName MethodInvocation MethodInvocation SimpleName get current test name
session SimpleName MethodInvocation MethodInvocation SimpleName get current test name
expected SimpleName VariableDeclarationFragment MethodInvocation SimpleName set attribute value
expected SimpleName VariableDeclarationFragment MethodInvocation SimpleName session
expected SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get current test name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName expected
attribute store SimpleName MethodInvocation SimpleName resolve attribute
attribute store SimpleName MethodInvocation SimpleName session
attribute store SimpleName MethodInvocation SimpleName key
resolve attribute SimpleName MethodInvocation SimpleName session
resolve attribute SimpleName MethodInvocation SimpleName key
session SimpleName MethodInvocation SimpleName key
assert same SimpleName MethodInvocation StringLiteral mismatched attribute value
assert same SimpleName MethodInvocation SimpleName expected
assert same SimpleName MethodInvocation MethodInvocation SimpleName attribute store
assert same SimpleName MethodInvocation MethodInvocation SimpleName resolve attribute
assert same SimpleName MethodInvocation MethodInvocation SimpleName session
assert same SimpleName MethodInvocation MethodInvocation SimpleName key
mismatched attribute value StringLiteral MethodInvocation SimpleName expected
mismatched attribute value StringLiteral MethodInvocation MethodInvocation SimpleName attribute store
mismatched attribute value StringLiteral MethodInvocation MethodInvocation SimpleName resolve attribute
mismatched attribute value StringLiteral MethodInvocation MethodInvocation SimpleName session
mismatched attribute value StringLiteral MethodInvocation MethodInvocation SimpleName key
expected SimpleName MethodInvocation MethodInvocation SimpleName attribute store
expected SimpleName MethodInvocation MethodInvocation SimpleName resolve attribute
expected SimpleName MethodInvocation MethodInvocation SimpleName session
expected SimpleName MethodInvocation MethodInvocation SimpleName key
manager count SimpleName MethodInvocation SimpleName get
assert equals SimpleName MethodInvocation StringLiteral unexpected manager request
assert equals SimpleName MethodInvocation NumberLiteral empty
assert equals SimpleName MethodInvocation MethodInvocation SimpleName manager count
assert equals SimpleName MethodInvocation MethodInvocation SimpleName get
unexpected manager request StringLiteral MethodInvocation NumberLiteral empty
unexpected manager request StringLiteral MethodInvocation MethodInvocation SimpleName manager count
unexpected manager request StringLiteral MethodInvocation MethodInvocation SimpleName get
empty NumberLiteral MethodInvocation MethodInvocation SimpleName manager count
empty NumberLiteral MethodInvocation MethodInvocation SimpleName get
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test resolve session attribute
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test resolve session attribute
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
void PrimitiveType MethodDeclaration SimpleName test resolve session attribute
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement Modifier final
test resolve session attribute SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test resolve session attribute
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test resolve session attribute
