string SimpleName SimpleType SingleVariableDeclaration SimpleName entity id
call api with body and params SimpleName MethodInvocation QualifiedName api v lineage inputs graph
call api with body and params SimpleName MethodInvocation SimpleName entity id
call api with body and params SimpleName MethodInvocation StringLiteral inputsgraph
api v lineage inputs graph QualifiedName MethodInvocation SimpleName entity id
api v lineage inputs graph QualifiedName MethodInvocation StringLiteral inputsgraph
entity id SimpleName MethodInvocation StringLiteral inputsgraph
response SimpleName VariableDeclarationFragment MethodInvocation SimpleName call api with body and params
response SimpleName VariableDeclarationFragment MethodInvocation QualifiedName api v lineage inputs graph
response SimpleName VariableDeclarationFragment MethodInvocation SimpleName entity id
response SimpleName VariableDeclarationFragment MethodInvocation StringLiteral inputsgraph
object node SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName response
response SimpleName MethodInvocation SimpleName get
response SimpleName MethodInvocation QualifiedName atlas clientresults
get SimpleName MethodInvocation QualifiedName atlas clientresults
object node SimpleName SimpleType CastExpression MethodInvocation SimpleName response
object node SimpleName SimpleType CastExpression MethodInvocation SimpleName get
object node SimpleName SimpleType CastExpression MethodInvocation QualifiedName atlas clientresults
public Modifier MethodDeclaration SimpleType SimpleName object node
public Modifier MethodDeclaration SimpleName get input graph for entity
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity id
public Modifier MethodDeclaration SimpleType SimpleName atlas service exception
object node SimpleName SimpleType MethodDeclaration SimpleName get input graph for entity
object node SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName entity id
object node SimpleName SimpleType MethodDeclaration SimpleType SimpleName atlas service exception
get input graph for entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get input graph for entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity id
get input graph for entity SimpleName MethodDeclaration SimpleType SimpleName atlas service exception
entity id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName object node
public Modifier TypeDeclaration MethodDeclaration SimpleName get input graph for entity
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity id
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName object node
test SimpleName TypeDeclaration MethodDeclaration SimpleName get input graph for entity
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity id
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
