referenceable SimpleName SimpleType ClassInstanceCreation SimpleName database type builtin
entity SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName referenceable
entity SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName database type builtin
final Modifier VariableDeclarationStatement SimpleType SimpleName referenceable
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName entity
final Modifier VariableDeclarationStatement VariableDeclarationFragment ClassInstanceCreation SimpleName database type builtin
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity
db StringLiteral InfixExpression MethodInvocation SimpleName random string
db name SimpleName VariableDeclarationFragment InfixExpression StringLiteral db
db name SimpleName VariableDeclarationFragment InfixExpression MethodInvocation SimpleName random string
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName db name
final Modifier VariableDeclarationStatement VariableDeclarationFragment InfixExpression StringLiteral db
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName db name
entity SimpleName MethodInvocation SimpleName set
entity SimpleName MethodInvocation SimpleName name
entity SimpleName MethodInvocation SimpleName db name
set SimpleName MethodInvocation SimpleName name
set SimpleName MethodInvocation SimpleName db name
name SimpleName MethodInvocation SimpleName db name
entity SimpleName MethodInvocation SimpleName set
entity SimpleName MethodInvocation SimpleName description
entity SimpleName MethodInvocation MethodInvocation SimpleName random string
set SimpleName MethodInvocation SimpleName description
set SimpleName MethodInvocation MethodInvocation SimpleName random string
description SimpleName MethodInvocation MethodInvocation SimpleName random string
entity SimpleName MethodInvocation SimpleName set
entity SimpleName MethodInvocation SimpleName qualified name
entity SimpleName MethodInvocation SimpleName db name
set SimpleName MethodInvocation SimpleName qualified name
set SimpleName MethodInvocation SimpleName db name
qualified name SimpleName MethodInvocation SimpleName db name
entity SimpleName MethodInvocation SimpleName set
entity SimpleName MethodInvocation SimpleName cluster name
entity SimpleName MethodInvocation MethodInvocation SimpleName random string
set SimpleName MethodInvocation SimpleName cluster name
set SimpleName MethodInvocation MethodInvocation SimpleName random string
cluster name SimpleName MethodInvocation MethodInvocation SimpleName random string
entity create request SimpleName SimpleType ClassInstanceCreation SimpleName test user
entity create request SimpleName SimpleType ClassInstanceCreation SimpleName entity
test user SimpleName ClassInstanceCreation SimpleName entity
send hook message SimpleName MethodInvocation ClassInstanceCreation SimpleType SimpleName entity create request
send hook message SimpleName MethodInvocation ClassInstanceCreation SimpleName test user
send hook message SimpleName MethodInvocation ClassInstanceCreation SimpleName entity
entity SimpleName MethodInvocation SimpleName get
entity SimpleName MethodInvocation SimpleName qualified name
get SimpleName MethodInvocation SimpleName qualified name
string SimpleName MethodInvocation SimpleName format
string SimpleName MethodInvocation StringLiteral s where qualified names
string SimpleName MethodInvocation SimpleName database type builtin
string SimpleName MethodInvocation MethodInvocation SimpleName entity
string SimpleName MethodInvocation MethodInvocation SimpleName get
string SimpleName MethodInvocation MethodInvocation SimpleName qualified name
format SimpleName MethodInvocation StringLiteral s where qualified names
format SimpleName MethodInvocation SimpleName database type builtin
format SimpleName MethodInvocation MethodInvocation SimpleName entity
format SimpleName MethodInvocation MethodInvocation SimpleName get
format SimpleName MethodInvocation MethodInvocation SimpleName qualified name
s where qualified names StringLiteral MethodInvocation SimpleName database type builtin
s where qualified names StringLiteral MethodInvocation MethodInvocation SimpleName entity
s where qualified names StringLiteral MethodInvocation MethodInvocation SimpleName get
s where qualified names StringLiteral MethodInvocation MethodInvocation SimpleName qualified name
database type builtin SimpleName MethodInvocation MethodInvocation SimpleName entity
database type builtin SimpleName MethodInvocation MethodInvocation SimpleName get
database type builtin SimpleName MethodInvocation MethodInvocation SimpleName qualified name
search by dsl SimpleName MethodInvocation MethodInvocation SimpleName string
search by dsl SimpleName MethodInvocation MethodInvocation SimpleName format
search by dsl SimpleName MethodInvocation MethodInvocation StringLiteral s where qualified names
search by dsl SimpleName MethodInvocation MethodInvocation SimpleName database type builtin
search by dsl SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName entity
search by dsl SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
search by dsl SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName qualified name
results SimpleName VariableDeclarationFragment MethodInvocation SimpleName search by dsl
results SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName string
results SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName format
results SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation StringLiteral s where qualified names
results SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName database type builtin
array node SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName results
results SimpleName MethodInvocation SimpleName size
results SimpleName MethodInvocation InfixExpression NumberLiteral empty
size SimpleName MethodInvocation InfixExpression NumberLiteral empty
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType boolean
override SimpleName MarkerAnnotation MethodDeclaration SimpleName evaluate
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName evaluate
public Modifier MethodDeclaration SimpleType SimpleName exception
boolean PrimitiveType MethodDeclaration SimpleName evaluate
boolean PrimitiveType MethodDeclaration SimpleType SimpleName exception
evaluate SimpleName MethodDeclaration SimpleType SimpleName exception
wait for SimpleName MethodInvocation SimpleName max wait time
wait for SimpleName MethodInvocation ClassInstanceCreation SimpleType SimpleName predicate
max wait time SimpleName MethodInvocation ClassInstanceCreation SimpleType SimpleName predicate
entity SimpleName MethodInvocation SimpleName get
entity SimpleName MethodInvocation SimpleName qualified name
get SimpleName MethodInvocation SimpleName qualified name
string SimpleName SimpleType CastExpression MethodInvocation SimpleName entity
string SimpleName SimpleType CastExpression MethodInvocation SimpleName get
string SimpleName SimpleType CastExpression MethodInvocation SimpleName qualified name
atlas client v SimpleName MethodInvocation SimpleName get entity
atlas client v SimpleName MethodInvocation SimpleName database type builtin
atlas client v SimpleName MethodInvocation SimpleName qualified name
atlas client v SimpleName MethodInvocation CastExpression SimpleType SimpleName string
atlas client v SimpleName MethodInvocation CastExpression MethodInvocation SimpleName entity
atlas client v SimpleName MethodInvocation CastExpression MethodInvocation SimpleName get
atlas client v SimpleName MethodInvocation CastExpression MethodInvocation SimpleName qualified name
get entity SimpleName MethodInvocation SimpleName database type builtin
get entity SimpleName MethodInvocation SimpleName qualified name
get entity SimpleName MethodInvocation CastExpression SimpleType SimpleName string
get entity SimpleName MethodInvocation CastExpression MethodInvocation SimpleName entity
get entity SimpleName MethodInvocation CastExpression MethodInvocation SimpleName get
get entity SimpleName MethodInvocation CastExpression MethodInvocation SimpleName qualified name
database type builtin SimpleName MethodInvocation SimpleName qualified name
database type builtin SimpleName MethodInvocation CastExpression SimpleType SimpleName string
database type builtin SimpleName MethodInvocation CastExpression MethodInvocation SimpleName entity
database type builtin SimpleName MethodInvocation CastExpression MethodInvocation SimpleName get
database type builtin SimpleName MethodInvocation CastExpression MethodInvocation SimpleName qualified name
qualified name SimpleName MethodInvocation CastExpression SimpleType SimpleName string
qualified name SimpleName MethodInvocation CastExpression MethodInvocation SimpleName entity
qualified name SimpleName MethodInvocation CastExpression MethodInvocation SimpleName get
qualified name SimpleName MethodInvocation CastExpression MethodInvocation SimpleName qualified name
instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName atlas client v
instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName get entity
instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName database type builtin
instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName qualified name
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName instance
list SimpleName SimpleType ParameterizedType SimpleType SimpleName entity audit event
instance SimpleName MethodInvocation SimpleName get id
instance SimpleName MethodInvocation MethodInvocation SimpleName get id
get id SimpleName MethodInvocation MethodInvocation SimpleName get id
short PrimitiveType CastExpression NumberLiteral empty
atlas client v SimpleName MethodInvocation SimpleName get entity audit events
atlas client v SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName instance
atlas client v SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
atlas client v SimpleName MethodInvocation MethodInvocation SimpleName get id
atlas client v SimpleName MethodInvocation CastExpression PrimitiveType short
atlas client v SimpleName MethodInvocation CastExpression NumberLiteral empty
get entity audit events SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName instance
get entity audit events SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
get entity audit events SimpleName MethodInvocation MethodInvocation SimpleName get id
get entity audit events SimpleName MethodInvocation CastExpression PrimitiveType short
get entity audit events SimpleName MethodInvocation CastExpression NumberLiteral empty
get id SimpleName MethodInvocation MethodInvocation CastExpression PrimitiveType short
get id SimpleName MethodInvocation MethodInvocation CastExpression NumberLiteral empty
events SimpleName VariableDeclarationFragment MethodInvocation SimpleName atlas client v
events SimpleName VariableDeclarationFragment MethodInvocation SimpleName get entity audit events
events SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get id
events SimpleName VariableDeclarationFragment MethodInvocation CastExpression PrimitiveType short
events SimpleName VariableDeclarationFragment MethodInvocation CastExpression NumberLiteral empty
events SimpleName MethodInvocation SimpleName size
assert equals SimpleName MethodInvocation MethodInvocation SimpleName events
assert equals SimpleName MethodInvocation MethodInvocation SimpleName size
assert equals SimpleName MethodInvocation NumberLiteral empty
events SimpleName MethodInvocation MethodInvocation NumberLiteral empty
size SimpleName MethodInvocation MethodInvocation NumberLiteral empty
events SimpleName MethodInvocation SimpleName get
events SimpleName MethodInvocation NumberLiteral empty
get SimpleName MethodInvocation NumberLiteral empty
events SimpleName MethodInvocation MethodInvocation SimpleName get user
get SimpleName MethodInvocation MethodInvocation SimpleName get user
empty NumberLiteral MethodInvocation MethodInvocation SimpleName get user
assert equals SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName events
assert equals SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
assert equals SimpleName MethodInvocation MethodInvocation MethodInvocation NumberLiteral empty
assert equals SimpleName MethodInvocation MethodInvocation SimpleName get user
assert equals SimpleName MethodInvocation SimpleName test user
events SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName test user
get SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName test user
empty NumberLiteral MethodInvocation MethodInvocation MethodInvocation SimpleName test user
get user SimpleName MethodInvocation MethodInvocation SimpleName test user
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test create entity
test SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test create entity
public Modifier MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
void PrimitiveType MethodDeclaration SimpleName test create entity
void PrimitiveType MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement Modifier final
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement Modifier final
test create entity SimpleName MethodDeclaration SimpleType SimpleName exception
test create entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
test create entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test create entity
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test create entity
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
