list SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas entity header
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName entity headers
atlas entity header SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName entity headers
atlas entity header SimpleName SimpleType SingleVariableDeclaration SimpleName new entity header
ret SimpleName VariableDeclarationFragment BooleanLiteral false
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName ret
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment BooleanLiteral false
collection utils SimpleName MethodInvocation SimpleName is not empty
collection utils SimpleName MethodInvocation SimpleName entity headers
is not empty SimpleName MethodInvocation SimpleName entity headers
collection utils SimpleName MethodInvocation InfixExpression InfixExpression SimpleName new entity header
is not empty SimpleName MethodInvocation InfixExpression InfixExpression SimpleName new entity header
entity headers SimpleName MethodInvocation InfixExpression InfixExpression SimpleName new entity header
atlas entity header SimpleName SimpleType SingleVariableDeclaration SimpleName entity header
entity header SimpleName MethodInvocation SimpleName get guid
new entity header SimpleName MethodInvocation SimpleName get guid
string utils SimpleName MethodInvocation SimpleName equals
string utils SimpleName MethodInvocation MethodInvocation SimpleName entity header
string utils SimpleName MethodInvocation MethodInvocation SimpleName get guid
string utils SimpleName MethodInvocation MethodInvocation SimpleName new entity header
string utils SimpleName MethodInvocation MethodInvocation SimpleName get guid
equals SimpleName MethodInvocation MethodInvocation SimpleName entity header
equals SimpleName MethodInvocation MethodInvocation SimpleName get guid
equals SimpleName MethodInvocation MethodInvocation SimpleName new entity header
equals SimpleName MethodInvocation MethodInvocation SimpleName get guid
entity header SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName new entity header
entity header SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get guid
get guid SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName new entity header
get guid SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get guid
ret SimpleName Assignment BooleanLiteral true
atlas entity header SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName entity headers
entity header SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName entity headers
boolean PrimitiveType VariableDeclarationStatement Block ReturnStatement SimpleName ret
private Modifier MethodDeclaration PrimitiveType boolean
private Modifier MethodDeclaration SimpleName entity header exists
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity headers
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas entity header
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName new entity header
private Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
private Modifier MethodDeclaration Block ReturnStatement SimpleName ret
boolean PrimitiveType MethodDeclaration SimpleName entity header exists
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName entity headers
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas entity header
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName new entity header
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
boolean PrimitiveType MethodDeclaration Block ReturnStatement SimpleName ret
entity header exists SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity headers
entity header exists SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas entity header
entity header exists SimpleName MethodDeclaration SingleVariableDeclaration SimpleName new entity header
entity header exists SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
entity header exists SimpleName MethodDeclaration Block ReturnStatement SimpleName ret
entity headers SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new entity header
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName entity header exists
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity headers
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new entity header
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName entity header exists
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity headers
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new entity header
