node SimpleName SimpleType SingleVariableDeclaration SimpleName n
public Modifier MethodDeclaration SimpleType SimpleName element
public Modifier MethodDeclaration SimpleName get xbl shadow tree
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName node
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName n
element SimpleName SimpleType MethodDeclaration SimpleName get xbl shadow tree
element SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName n
get xbl shadow tree SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName node
get xbl shadow tree SimpleName MethodDeclaration SingleVariableDeclaration SimpleName n
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName element
public Modifier TypeDeclaration MethodDeclaration SimpleName get xbl shadow tree
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName n
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName element
test SimpleName TypeDeclaration MethodDeclaration SimpleName get xbl shadow tree
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName n
