file system SimpleName SimpleType SingleVariableDeclaration SimpleName fs
instance SimpleName SimpleType SingleVariableDeclaration SimpleName instance
t credentials SimpleName SimpleType SingleVariableDeclaration SimpleName credentials
boolean PrimitiveType SingleVariableDeclaration SimpleName no trash
trace file system SimpleName MethodInvocation SimpleName wrap
trace file system SimpleName MethodInvocation SimpleName fs
wrap SimpleName MethodInvocation SimpleName fs
fs SimpleName FieldAccess Assignment MethodInvocation SimpleName trace file system
fs SimpleName FieldAccess Assignment MethodInvocation SimpleName wrap
fs SimpleName FieldAccess Assignment MethodInvocation SimpleName fs
credentials SimpleName FieldAccess Assignment SimpleName credentials
instance SimpleName FieldAccess Assignment SimpleName instance
instance SimpleName MethodInvocation SimpleName get configuration
instance SimpleName MethodInvocation MethodInvocation SimpleName get time in millis
get configuration SimpleName MethodInvocation MethodInvocation SimpleName get time in millis
instance SimpleName MethodInvocation MethodInvocation QualifiedName propertygc cycle start
get configuration SimpleName MethodInvocation MethodInvocation QualifiedName propertygc cycle start
get time in millis SimpleName MethodInvocation QualifiedName propertygc cycle start
gc start delay SimpleName Assignment MethodInvocation MethodInvocation SimpleName instance
gc start delay SimpleName Assignment MethodInvocation MethodInvocation SimpleName get configuration
gc start delay SimpleName Assignment MethodInvocation SimpleName get time in millis
gc start delay SimpleName Assignment MethodInvocation QualifiedName propertygc cycle start
instance SimpleName MethodInvocation SimpleName get configuration
instance SimpleName MethodInvocation MethodInvocation SimpleName get time in millis
get configuration SimpleName MethodInvocation MethodInvocation SimpleName get time in millis
instance SimpleName MethodInvocation MethodInvocation QualifiedName propertygc cycle delay
get configuration SimpleName MethodInvocation MethodInvocation QualifiedName propertygc cycle delay
get time in millis SimpleName MethodInvocation QualifiedName propertygc cycle delay
gc delay SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName instance
gc delay SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get configuration
gc delay SimpleName VariableDeclarationFragment MethodInvocation SimpleName get time in millis
gc delay SimpleName VariableDeclarationFragment MethodInvocation QualifiedName propertygc cycle delay
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName gc delay
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get time in millis
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation QualifiedName propertygc cycle delay
instance SimpleName MethodInvocation SimpleName get configuration
instance SimpleName MethodInvocation MethodInvocation SimpleName get count
get configuration SimpleName MethodInvocation MethodInvocation SimpleName get count
instance SimpleName MethodInvocation MethodInvocation QualifiedName propertygc delete threads
get configuration SimpleName MethodInvocation MethodInvocation QualifiedName propertygc delete threads
get count SimpleName MethodInvocation QualifiedName propertygc delete threads
num delete threads SimpleName Assignment MethodInvocation MethodInvocation SimpleName instance
num delete threads SimpleName Assignment MethodInvocation MethodInvocation SimpleName get configuration
num delete threads SimpleName Assignment MethodInvocation SimpleName get count
num delete threads SimpleName Assignment MethodInvocation QualifiedName propertygc delete threads
empty NumberLiteral InfixExpression StringLiteral sec offline
gc start delay SimpleName InfixExpression StringLiteral milliseconds
offline SimpleName ConditionalExpression InfixExpression NumberLiteral empty
offline SimpleName ConditionalExpression InfixExpression StringLiteral sec offline
offline SimpleName ConditionalExpression InfixExpression SimpleName gc start delay
offline SimpleName ConditionalExpression InfixExpression StringLiteral milliseconds
empty NumberLiteral InfixExpression ConditionalExpression InfixExpression SimpleName gc start delay
empty NumberLiteral InfixExpression ConditionalExpression InfixExpression StringLiteral milliseconds
sec offline StringLiteral InfixExpression ConditionalExpression InfixExpression SimpleName gc start delay
sec offline StringLiteral InfixExpression ConditionalExpression InfixExpression StringLiteral milliseconds
start delay StringLiteral InfixExpression ParenthesizedExpression ConditionalExpression SimpleName offline
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral start delay
info SimpleName MethodInvocation InfixExpression StringLiteral start delay
time delay StringLiteral InfixExpression SimpleName gc delay
time delay StringLiteral InfixExpression StringLiteral milliseconds
gc delay SimpleName InfixExpression StringLiteral milliseconds
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral time delay
log SimpleName MethodInvocation InfixExpression SimpleName gc delay
log SimpleName MethodInvocation InfixExpression StringLiteral milliseconds
info SimpleName MethodInvocation InfixExpression StringLiteral time delay
info SimpleName MethodInvocation InfixExpression SimpleName gc delay
info SimpleName MethodInvocation InfixExpression StringLiteral milliseconds
safemode StringLiteral InfixExpression SimpleName safemode
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral safemode
log SimpleName MethodInvocation InfixExpression SimpleName safemode
info SimpleName MethodInvocation InfixExpression StringLiteral safemode
info SimpleName MethodInvocation InfixExpression SimpleName safemode
offline StringLiteral InfixExpression SimpleName offline
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral offline
log SimpleName MethodInvocation InfixExpression SimpleName offline
info SimpleName MethodInvocation InfixExpression StringLiteral offline
info SimpleName MethodInvocation InfixExpression SimpleName offline
verbose StringLiteral InfixExpression SimpleName verbose
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral verbose
log SimpleName MethodInvocation InfixExpression SimpleName verbose
info SimpleName MethodInvocation InfixExpression StringLiteral verbose
info SimpleName MethodInvocation InfixExpression SimpleName verbose
runtime SimpleName MethodInvocation SimpleName get runtime
runtime SimpleName MethodInvocation MethodInvocation SimpleName max memory
get runtime SimpleName MethodInvocation MethodInvocation SimpleName max memory
memory threshold StringLiteral InfixExpression SimpleName candidate memory percentage
memory threshold StringLiteral InfixExpression StringLiteral of
memory threshold StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName runtime
memory threshold StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName get runtime
memory threshold StringLiteral InfixExpression MethodInvocation SimpleName max memory
memory threshold StringLiteral InfixExpression StringLiteral bytes
candidate memory percentage SimpleName InfixExpression StringLiteral of
candidate memory percentage SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName runtime
candidate memory percentage SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName get runtime
candidate memory percentage SimpleName InfixExpression MethodInvocation SimpleName max memory
candidate memory percentage SimpleName InfixExpression StringLiteral bytes
of StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName runtime
of StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName get runtime
of StringLiteral InfixExpression MethodInvocation SimpleName max memory
of StringLiteral InfixExpression StringLiteral bytes
runtime SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral bytes
get runtime SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral bytes
max memory SimpleName MethodInvocation InfixExpression StringLiteral bytes
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral memory threshold
log SimpleName MethodInvocation InfixExpression SimpleName candidate memory percentage
log SimpleName MethodInvocation InfixExpression StringLiteral of
log SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName max memory
log SimpleName MethodInvocation InfixExpression StringLiteral bytes
info SimpleName MethodInvocation InfixExpression StringLiteral memory threshold
info SimpleName MethodInvocation InfixExpression SimpleName candidate memory percentage
info SimpleName MethodInvocation InfixExpression StringLiteral of
info SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName max memory
info SimpleName MethodInvocation InfixExpression StringLiteral bytes
delete threads StringLiteral InfixExpression SimpleName num delete threads
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral delete threads
log SimpleName MethodInvocation InfixExpression SimpleName num delete threads
info SimpleName MethodInvocation InfixExpression StringLiteral delete threads
info SimpleName MethodInvocation InfixExpression SimpleName num delete threads
fs SimpleName MethodInvocation SimpleName get conf
trash SimpleName SimpleType ClassInstanceCreation SimpleName fs
trash SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName fs
trash SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName get conf
fs SimpleName ClassInstanceCreation MethodInvocation SimpleName fs
fs SimpleName ClassInstanceCreation MethodInvocation SimpleName get conf
trash SimpleName FieldAccess Assignment ClassInstanceCreation SimpleName fs
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName init
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName file system
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName fs
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName instance
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName instance
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName t credentials
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName credentials
void PrimitiveType MethodDeclaration SimpleName init
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName file system
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName fs
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName instance
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName instance
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName t credentials
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName credentials
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName no trash
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName file system
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleName fs
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName instance
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleName instance
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName t credentials
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleName credentials
init SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
init SimpleName MethodDeclaration SingleVariableDeclaration SimpleName no trash
init SimpleName MethodDeclaration SimpleType SimpleName io exception
fs SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance
fs SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName credentials
fs SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
fs SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName no trash
fs SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
instance SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName credentials
instance SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
instance SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName no trash
instance SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
credentials SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
credentials SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName no trash
credentials SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
no trash SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName init
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fs
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName credentials
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName no trash
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName init
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fs
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName credentials
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName no trash
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
