interval SimpleName SimpleType SingleVariableDeclaration SimpleName i
timing specifier SimpleName SimpleType SingleVariableDeclaration SimpleName ts
boolean PrimitiveType SingleVariableDeclaration SimpleName is begin
i SimpleName MethodInvocation SimpleName get begin instance time
i SimpleName MethodInvocation SimpleName get end instance time
is begin SimpleName ConditionalExpression MethodInvocation SimpleName i
is begin SimpleName ConditionalExpression MethodInvocation SimpleName get begin instance time
is begin SimpleName ConditionalExpression MethodInvocation SimpleName i
is begin SimpleName ConditionalExpression MethodInvocation SimpleName get end instance time
i SimpleName MethodInvocation ConditionalExpression MethodInvocation SimpleName i
i SimpleName MethodInvocation ConditionalExpression MethodInvocation SimpleName get end instance time
get begin instance time SimpleName MethodInvocation ConditionalExpression MethodInvocation SimpleName i
get begin instance time SimpleName MethodInvocation ConditionalExpression MethodInvocation SimpleName get end instance time
it SimpleName VariableDeclarationFragment ConditionalExpression SimpleName is begin
it SimpleName VariableDeclarationFragment ConditionalExpression MethodInvocation SimpleName i
it SimpleName VariableDeclarationFragment ConditionalExpression MethodInvocation SimpleName get begin instance time
it SimpleName VariableDeclarationFragment ConditionalExpression MethodInvocation SimpleName i
it SimpleName VariableDeclarationFragment ConditionalExpression MethodInvocation SimpleName get end instance time
instance time SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName it
propagation flags SimpleName MethodInvocation SimpleName contains
propagation flags SimpleName MethodInvocation SimpleName it
propagation flags SimpleName MethodInvocation SimpleName ts
contains SimpleName MethodInvocation SimpleName it
contains SimpleName MethodInvocation SimpleName ts
it SimpleName MethodInvocation SimpleName ts
propagation flags SimpleName MethodInvocation SimpleName add
propagation flags SimpleName MethodInvocation SimpleName it
propagation flags SimpleName MethodInvocation SimpleName ts
add SimpleName MethodInvocation SimpleName it
add SimpleName MethodInvocation SimpleName ts
it SimpleName MethodInvocation SimpleName ts
boolean PrimitiveType MethodDeclaration SimpleName should propagate
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName interval
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName i
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName timing specifier
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName ts
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName is begin
boolean PrimitiveType MethodDeclaration Block ReturnStatement BooleanLiteral true
should propagate SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName interval
should propagate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName i
should propagate SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName timing specifier
should propagate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName ts
should propagate SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
should propagate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName is begin
should propagate SimpleName MethodDeclaration Block ReturnStatement BooleanLiteral true
i SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ts
i SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
i SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName is begin
ts SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
ts SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName is begin
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName should propagate
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName i
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ts
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName is begin
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName should propagate
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName i
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ts
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName is begin
