object SimpleName SimpleType SingleVariableDeclaration SimpleName o
object SimpleName SimpleType SingleVariableDeclaration SimpleName o
table SimpleName MethodInvocation SimpleName get
table SimpleName MethodInvocation SimpleName o
table SimpleName MethodInvocation SimpleName o
get SimpleName MethodInvocation SimpleName o
get SimpleName MethodInvocation SimpleName o
o SimpleName MethodInvocation SimpleName o
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName contains
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName o
boolean PrimitiveType MethodDeclaration SimpleName contains
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName o
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName o
contains SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
contains SimpleName MethodDeclaration SingleVariableDeclaration SimpleName o
contains SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
contains SimpleName MethodDeclaration SingleVariableDeclaration SimpleName o
o SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName contains
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName contains
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
