timing specifier SimpleName SimpleType SingleVariableDeclaration SimpleName dependent
boolean PrimitiveType SingleVariableDeclaration SimpleName for begin
boolean SimpleName SimpleType ClassInstanceCreation SimpleName for begin
dependent SimpleName ArrayInitializer ClassInstanceCreation SimpleType SimpleName boolean
dependent SimpleName ArrayInitializer ClassInstanceCreation SimpleName for begin
trace SimpleName MethodInvocation SimpleName enter
trace SimpleName MethodInvocation StringLiteral add dependent
trace SimpleName MethodInvocation ArrayCreation ArrayInitializer SimpleName dependent
enter SimpleName MethodInvocation StringLiteral add dependent
enter SimpleName MethodInvocation ArrayCreation ArrayInitializer SimpleName dependent
add dependent StringLiteral MethodInvocation ArrayCreation ArrayInitializer SimpleName dependent
begin dependents SimpleName MethodInvocation SimpleName add
begin dependents SimpleName MethodInvocation SimpleName dependent
add SimpleName MethodInvocation SimpleName dependent
end dependents SimpleName MethodInvocation SimpleName add
end dependents SimpleName MethodInvocation SimpleName dependent
add SimpleName MethodInvocation SimpleName dependent
trace SimpleName MethodInvocation SimpleName exit
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName add dependent
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName timing specifier
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName dependent
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName for begin
void PrimitiveType MethodDeclaration SimpleName add dependent
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName timing specifier
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName dependent
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName for begin
add dependent SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName timing specifier
add dependent SimpleName MethodDeclaration SingleVariableDeclaration SimpleName dependent
add dependent SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
add dependent SimpleName MethodDeclaration SingleVariableDeclaration SimpleName for begin
dependent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
dependent SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName for begin
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName add dependent
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName dependent
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName for begin
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName add dependent
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName dependent
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName for begin
