animatable value SimpleName SimpleType SingleVariableDeclaration SimpleName result
animatable value SimpleName SimpleType SingleVariableDeclaration SimpleName to
float PrimitiveType SingleVariableDeclaration SimpleName interpolation
animatable value SimpleName SimpleType SingleVariableDeclaration SimpleName accumulation
int PrimitiveType SingleVariableDeclaration SimpleName multiplier
animatable angle or ident value SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName res
animatable angle or ident value SimpleName SimpleType ClassInstanceCreation SimpleName target
res SimpleName Assignment ClassInstanceCreation SimpleType SimpleName animatable angle or ident value
res SimpleName Assignment ClassInstanceCreation SimpleName target
animatable angle or ident value SimpleName SimpleType CastExpression SimpleName result
res SimpleName Assignment CastExpression SimpleType SimpleName animatable angle or ident value
res SimpleName Assignment CastExpression SimpleName result
resident QualifiedName MethodInvocation SimpleName equals
resident QualifiedName MethodInvocation SimpleName ident
equals SimpleName MethodInvocation SimpleName ident
reshas changed QualifiedName Assignment InfixExpression PrefixExpression QualifiedName resis ident
resident QualifiedName Assignment SimpleName ident
resis ident QualifiedName Assignment BooleanLiteral true
old unit SimpleName VariableDeclarationFragment QualifiedName resunit
short PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName old unit
short PrimitiveType VariableDeclarationStatement VariableDeclarationFragment QualifiedName resunit
old value SimpleName VariableDeclarationFragment QualifiedName resvalue
float PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName old value
float PrimitiveType VariableDeclarationStatement VariableDeclarationFragment QualifiedName resvalue
interpolate SimpleName SuperMethodInvocation SimpleName res
interpolate SimpleName SuperMethodInvocation SimpleName to
interpolate SimpleName SuperMethodInvocation SimpleName interpolation
interpolate SimpleName SuperMethodInvocation SimpleName accumulation
interpolate SimpleName SuperMethodInvocation SimpleName multiplier
res SimpleName SuperMethodInvocation SimpleName to
res SimpleName SuperMethodInvocation SimpleName interpolation
res SimpleName SuperMethodInvocation SimpleName accumulation
res SimpleName SuperMethodInvocation SimpleName multiplier
to SimpleName SuperMethodInvocation SimpleName interpolation
to SimpleName SuperMethodInvocation SimpleName accumulation
to SimpleName SuperMethodInvocation SimpleName multiplier
interpolation SimpleName SuperMethodInvocation SimpleName accumulation
interpolation SimpleName SuperMethodInvocation SimpleName multiplier
accumulation SimpleName SuperMethodInvocation SimpleName multiplier
resunit QualifiedName InfixExpression SimpleName old unit
resvalue QualifiedName InfixExpression SimpleName old value
resunit QualifiedName InfixExpression InfixExpression InfixExpression QualifiedName resvalue
resunit QualifiedName InfixExpression InfixExpression InfixExpression SimpleName old value
old unit SimpleName InfixExpression InfixExpression InfixExpression QualifiedName resvalue
old unit SimpleName InfixExpression InfixExpression InfixExpression SimpleName old value
reshas changed QualifiedName Assignment BooleanLiteral true
short PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType float
is ident SimpleName IfStatement Block VariableDeclarationStatement PrimitiveType short
is ident SimpleName IfStatement Block VariableDeclarationStatement PrimitiveType float
animatable angle or ident value SimpleName SimpleType CastExpression SimpleName to
to value SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName animatable angle or ident value
to value SimpleName VariableDeclarationFragment CastExpression SimpleName to
animatable angle or ident value SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName to value
is ident SimpleName InfixExpression QualifiedName to valueis ident
interpolation SimpleName InfixExpression NumberLiteral .
resis ident QualifiedName InfixExpression QualifiedName to valueis ident
resunit QualifiedName InfixExpression QualifiedName to valueunit
resis ident QualifiedName InfixExpression InfixExpression InfixExpression QualifiedName resunit
resis ident QualifiedName InfixExpression InfixExpression InfixExpression QualifiedName to valueunit
to valueis ident QualifiedName InfixExpression InfixExpression InfixExpression QualifiedName resunit
to valueis ident QualifiedName InfixExpression InfixExpression InfixExpression QualifiedName to valueunit
resvalue QualifiedName InfixExpression QualifiedName to valuevalue
to valueident QualifiedName MethodInvocation SimpleName equals
to valueident QualifiedName MethodInvocation SimpleName ident
equals SimpleName MethodInvocation SimpleName ident
resis ident QualifiedName InfixExpression QualifiedName to valueis ident
resis ident QualifiedName InfixExpression PrefixExpression MethodInvocation QualifiedName to valueident
resis ident QualifiedName InfixExpression PrefixExpression MethodInvocation SimpleName equals
resis ident QualifiedName InfixExpression PrefixExpression MethodInvocation SimpleName ident
to valueis ident QualifiedName InfixExpression PrefixExpression MethodInvocation QualifiedName to valueident
to valueis ident QualifiedName InfixExpression PrefixExpression MethodInvocation SimpleName equals
to valueis ident QualifiedName InfixExpression PrefixExpression MethodInvocation SimpleName ident
resis ident QualifiedName Assignment QualifiedName to valueis ident
resident QualifiedName Assignment QualifiedName to valueident
resunit QualifiedName Assignment QualifiedName to valueunit
resvalue QualifiedName Assignment QualifiedName to valuevalue
reshas changed QualifiedName Assignment BooleanLiteral true
resis ident QualifiedName InfixExpression SimpleName is ident
resunit QualifiedName InfixExpression SimpleName unit
resis ident QualifiedName InfixExpression InfixExpression InfixExpression QualifiedName resunit
resis ident QualifiedName InfixExpression InfixExpression InfixExpression SimpleName unit
is ident SimpleName InfixExpression InfixExpression InfixExpression QualifiedName resunit
is ident SimpleName InfixExpression InfixExpression InfixExpression SimpleName unit
resvalue QualifiedName InfixExpression SimpleName value
resident QualifiedName MethodInvocation SimpleName equals
resident QualifiedName MethodInvocation SimpleName ident
equals SimpleName MethodInvocation SimpleName ident
resis ident QualifiedName InfixExpression SimpleName is ident
resis ident QualifiedName InfixExpression PrefixExpression MethodInvocation QualifiedName resident
resis ident QualifiedName InfixExpression PrefixExpression MethodInvocation SimpleName equals
resis ident QualifiedName InfixExpression PrefixExpression MethodInvocation SimpleName ident
is ident SimpleName InfixExpression PrefixExpression MethodInvocation QualifiedName resident
is ident SimpleName InfixExpression PrefixExpression MethodInvocation SimpleName equals
is ident SimpleName InfixExpression PrefixExpression MethodInvocation SimpleName ident
resis ident QualifiedName Assignment SimpleName is ident
resident QualifiedName Assignment SimpleName ident
resunit QualifiedName Assignment SimpleName unit
resvalue QualifiedName Assignment SimpleName value
reshas changed QualifiedName Assignment BooleanLiteral true
interpolate SimpleName SuperMethodInvocation SimpleName res
interpolate SimpleName SuperMethodInvocation SimpleName to
interpolate SimpleName SuperMethodInvocation SimpleName interpolation
interpolate SimpleName SuperMethodInvocation SimpleName accumulation
interpolate SimpleName SuperMethodInvocation SimpleName multiplier
res SimpleName SuperMethodInvocation SimpleName to
res SimpleName SuperMethodInvocation SimpleName interpolation
res SimpleName SuperMethodInvocation SimpleName accumulation
res SimpleName SuperMethodInvocation SimpleName multiplier
to SimpleName SuperMethodInvocation SimpleName interpolation
to SimpleName SuperMethodInvocation SimpleName accumulation
to SimpleName SuperMethodInvocation SimpleName multiplier
interpolation SimpleName SuperMethodInvocation SimpleName accumulation
interpolation SimpleName SuperMethodInvocation SimpleName multiplier
accumulation SimpleName SuperMethodInvocation SimpleName multiplier
public Modifier MethodDeclaration SimpleType SimpleName animatable value
public Modifier MethodDeclaration SimpleName interpolate
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animatable value
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName result
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animatable value
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName to
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName interpolation
animatable value SimpleName SimpleType MethodDeclaration SimpleName interpolate
animatable value SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName result
animatable value SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName to
animatable value SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType float
animatable value SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName interpolation
animatable value SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName accumulation
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animatable value
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName result
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animatable value
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName to
interpolate SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType float
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName interpolation
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animatable value
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName accumulation
interpolate SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
interpolate SimpleName MethodDeclaration SingleVariableDeclaration SimpleName multiplier
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName to
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName interpolation
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName accumulation
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
result SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
to SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
to SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName interpolation
to SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName accumulation
to SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
to SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
float PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName accumulation
interpolation SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName accumulation
float PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
float PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
interpolation SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
interpolation SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
accumulation SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
accumulation SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName animatable value
public Modifier TypeDeclaration MethodDeclaration SimpleName interpolate
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName to
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName interpolation
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName accumulation
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName animatable value
test SimpleName TypeDeclaration MethodDeclaration SimpleName interpolate
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName to
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName interpolation
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName accumulation
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName multiplier
