animation target SimpleName SimpleType SingleVariableDeclaration SimpleName target
short PrimitiveType SingleVariableDeclaration SimpleName type
string SimpleName SimpleType SingleVariableDeclaration SimpleName ns
string SimpleName SimpleType SingleVariableDeclaration SimpleName an
get target info SimpleName MethodInvocation SimpleName target
info SimpleName VariableDeclarationFragment MethodInvocation SimpleName get target info
info SimpleName VariableDeclarationFragment MethodInvocation SimpleName target
target info SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName info
sandwich SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName sandwich
type SimpleName InfixExpression SimpleName anim type xml
infoxml animations QualifiedName MethodInvocation SimpleName get
infoxml animations QualifiedName MethodInvocation SimpleName ns
infoxml animations QualifiedName MethodInvocation SimpleName an
get SimpleName MethodInvocation SimpleName ns
get SimpleName MethodInvocation SimpleName an
ns SimpleName MethodInvocation SimpleName an
sandwich SimpleName SimpleType CastExpression MethodInvocation QualifiedName infoxml animations
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName get
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName ns
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName an
sandwich SimpleName Assignment CastExpression SimpleType SimpleName sandwich
sandwich SimpleName Assignment CastExpression MethodInvocation QualifiedName infoxml animations
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName get
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName ns
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName an
sandwich SimpleName Assignment ClassInstanceCreation SimpleType SimpleName sandwich
infoxml animations QualifiedName MethodInvocation SimpleName put
infoxml animations QualifiedName MethodInvocation SimpleName ns
infoxml animations QualifiedName MethodInvocation SimpleName an
infoxml animations QualifiedName MethodInvocation SimpleName sandwich
put SimpleName MethodInvocation SimpleName ns
put SimpleName MethodInvocation SimpleName an
put SimpleName MethodInvocation SimpleName sandwich
ns SimpleName MethodInvocation SimpleName an
ns SimpleName MethodInvocation SimpleName sandwich
an SimpleName MethodInvocation SimpleName sandwich
type SimpleName InfixExpression SimpleName anim type css
infocss animations QualifiedName MethodInvocation SimpleName get
infocss animations QualifiedName MethodInvocation SimpleName an
get SimpleName MethodInvocation SimpleName an
sandwich SimpleName SimpleType CastExpression MethodInvocation QualifiedName infocss animations
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName get
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName an
sandwich SimpleName Assignment CastExpression SimpleType SimpleName sandwich
sandwich SimpleName Assignment CastExpression MethodInvocation QualifiedName infocss animations
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName get
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName an
sandwich SimpleName Assignment ClassInstanceCreation SimpleType SimpleName sandwich
infocss animations QualifiedName MethodInvocation SimpleName put
infocss animations QualifiedName MethodInvocation SimpleName an
infocss animations QualifiedName MethodInvocation SimpleName sandwich
put SimpleName MethodInvocation SimpleName an
put SimpleName MethodInvocation SimpleName sandwich
an SimpleName MethodInvocation SimpleName sandwich
infoother animations QualifiedName MethodInvocation SimpleName get
infoother animations QualifiedName MethodInvocation SimpleName an
get SimpleName MethodInvocation SimpleName an
sandwich SimpleName SimpleType CastExpression MethodInvocation QualifiedName infoother animations
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName get
sandwich SimpleName SimpleType CastExpression MethodInvocation SimpleName an
sandwich SimpleName Assignment CastExpression SimpleType SimpleName sandwich
sandwich SimpleName Assignment CastExpression MethodInvocation QualifiedName infoother animations
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName get
sandwich SimpleName Assignment CastExpression MethodInvocation SimpleName an
sandwich SimpleName Assignment ClassInstanceCreation SimpleType SimpleName sandwich
infoother animations QualifiedName MethodInvocation SimpleName put
infoother animations QualifiedName MethodInvocation SimpleName an
infoother animations QualifiedName MethodInvocation SimpleName sandwich
put SimpleName MethodInvocation SimpleName an
put SimpleName MethodInvocation SimpleName sandwich
an SimpleName MethodInvocation SimpleName sandwich
protected Modifier MethodDeclaration SimpleType SimpleName sandwich
protected Modifier MethodDeclaration SimpleName get sandwich
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animation target
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName target
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType short
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName type
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName ns
sandwich SimpleName SimpleType MethodDeclaration SimpleName get sandwich
sandwich SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName target
sandwich SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType short
sandwich SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName type
sandwich SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName ns
sandwich SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName an
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName animation target
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleName target
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType short
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleName type
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleName ns
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get sandwich SimpleName MethodDeclaration SingleVariableDeclaration SimpleName an
get sandwich SimpleName MethodDeclaration Block ReturnStatement SimpleName sandwich
target SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType short
target SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName type
target SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ns
target SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName an
short PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ns
type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ns
short PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName an
type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName an
ns SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName an
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName sandwich
public Modifier TypeDeclaration MethodDeclaration SimpleName get sandwich
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName target
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType short
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ns
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName an
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName sandwich
test SimpleName TypeDeclaration MethodDeclaration SimpleName get sandwich
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName target
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType short
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName ns
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName an
