event SimpleName SimpleType SingleVariableDeclaration SimpleName e
e SimpleName MethodInvocation SimpleName get time stamp
owner SimpleName MethodInvocation SimpleName get root
owner SimpleName MethodInvocation MethodInvocation SimpleName get document begin time
get root SimpleName MethodInvocation MethodInvocation SimpleName get document begin time
owner SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get time in millis
get root SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get time in millis
get document begin time SimpleName MethodInvocation MethodInvocation SimpleName get time in millis
e SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get time in millis
get time stamp SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get time in millis
time SimpleName VariableDeclarationFragment InfixExpression MethodInvocation SimpleName e
time SimpleName VariableDeclarationFragment InfixExpression MethodInvocation SimpleName get time stamp
time SimpleName VariableDeclarationFragment InfixExpression MethodInvocation SimpleName get time in millis
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName time
time SimpleName InfixExpression NumberLiteral f
instance time SimpleName SimpleType ClassInstanceCreation InfixExpression SimpleName time
instance time SimpleName SimpleType ClassInstanceCreation InfixExpression NumberLiteral f
instance time SimpleName SimpleType ClassInstanceCreation BooleanLiteral true
time SimpleName InfixExpression ClassInstanceCreation BooleanLiteral true
f NumberLiteral InfixExpression ClassInstanceCreation BooleanLiteral true
instance SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName instance time
instance SimpleName VariableDeclarationFragment ClassInstanceCreation InfixExpression SimpleName time
instance SimpleName VariableDeclarationFragment ClassInstanceCreation InfixExpression NumberLiteral f
instance SimpleName VariableDeclarationFragment ClassInstanceCreation BooleanLiteral true
instance time SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName instance
owner SimpleName MethodInvocation SimpleName add instance time
owner SimpleName MethodInvocation SimpleName instance
owner SimpleName MethodInvocation SimpleName is begin
add instance time SimpleName MethodInvocation SimpleName instance
add instance time SimpleName MethodInvocation SimpleName is begin
instance SimpleName MethodInvocation SimpleName is begin
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName resolve
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName event
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName e
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
void PrimitiveType MethodDeclaration SimpleName resolve
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName event
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName e
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
resolve SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName event
resolve SimpleName MethodDeclaration SingleVariableDeclaration SimpleName e
resolve SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName resolve
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName e
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName resolve
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName e
