int PrimitiveType SingleVariableDeclaration SimpleName type
float PrimitiveType SingleVariableDeclaration SimpleName val
short PrimitiveType CastExpression SimpleName type
new value specified units SimpleName SuperMethodInvocation CastExpression PrimitiveType short
new value specified units SimpleName SuperMethodInvocation CastExpression SimpleName type
new value specified units SimpleName SuperMethodInvocation SimpleName val
short PrimitiveType CastExpression SuperMethodInvocation SimpleName val
type SimpleName CastExpression SuperMethodInvocation SimpleName val
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName set animated value
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName type
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType float
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName val
void PrimitiveType MethodDeclaration SimpleName set animated value
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName type
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType float
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName val
set animated value SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
set animated value SimpleName MethodDeclaration SingleVariableDeclaration SimpleName type
set animated value SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType float
set animated value SimpleName MethodDeclaration SingleVariableDeclaration SimpleName val
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set animated value
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set animated value
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName val
