string SimpleName SimpleType SingleVariableDeclaration SimpleName location
string SimpleName SimpleType SingleVariableDeclaration SimpleName input format
string SimpleName SimpleType SingleVariableDeclaration SimpleName output format
boolean PrimitiveType SingleVariableDeclaration SimpleName compressed
atlas entity SimpleName SimpleType ClassInstanceCreation SimpleName storage desc type
entity SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName atlas entity
entity SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName storage desc type
atlas entity SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity
entity SimpleName MethodInvocation SimpleName set attribute
entity SimpleName MethodInvocation StringLiteral location
entity SimpleName MethodInvocation SimpleName location
set attribute SimpleName MethodInvocation StringLiteral location
set attribute SimpleName MethodInvocation SimpleName location
location StringLiteral MethodInvocation SimpleName location
entity SimpleName MethodInvocation SimpleName set attribute
entity SimpleName MethodInvocation StringLiteral input format
entity SimpleName MethodInvocation SimpleName input format
set attribute SimpleName MethodInvocation StringLiteral input format
set attribute SimpleName MethodInvocation SimpleName input format
input format StringLiteral MethodInvocation SimpleName input format
entity SimpleName MethodInvocation SimpleName set attribute
entity SimpleName MethodInvocation StringLiteral output format
entity SimpleName MethodInvocation SimpleName output format
set attribute SimpleName MethodInvocation StringLiteral output format
set attribute SimpleName MethodInvocation SimpleName output format
output format StringLiteral MethodInvocation SimpleName output format
entity SimpleName MethodInvocation SimpleName set attribute
entity SimpleName MethodInvocation StringLiteral compressed
entity SimpleName MethodInvocation SimpleName compressed
set attribute SimpleName MethodInvocation StringLiteral compressed
set attribute SimpleName MethodInvocation SimpleName compressed
compressed StringLiteral MethodInvocation SimpleName compressed
create instance SimpleName MethodInvocation SimpleName entity
atlas entity SimpleName SimpleType MethodDeclaration SimpleName create storage descriptor
atlas entity SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName location
atlas entity SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName input format
atlas entity SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName output format
atlas entity SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
atlas entity SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName compressed
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleName location
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleName input format
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleName output format
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
create storage descriptor SimpleName MethodDeclaration SingleVariableDeclaration SimpleName compressed
create storage descriptor SimpleName MethodDeclaration SimpleType SimpleName exception
location SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName input format
location SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output format
location SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
location SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName compressed
location SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
input format SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output format
input format SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
input format SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName compressed
input format SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
output format SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
output format SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName compressed
output format SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
compressed SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas entity
public Modifier TypeDeclaration MethodDeclaration SimpleName create storage descriptor
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName location
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName input format
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output format
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName compressed
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas entity
test SimpleName TypeDeclaration MethodDeclaration SimpleName create storage descriptor
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName location
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName input format
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName output format
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName compressed
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
