path SimpleName SingleMemberAnnotation StringLiteral guidguidclassificationclassification name
produces SimpleName SingleMemberAnnotation QualifiedName servletsjson media type
path param SimpleName SingleMemberAnnotation StringLiteral guid
path param SimpleName SingleMemberAnnotation SingleVariableDeclaration SimpleType SimpleName string
guid StringLiteral SingleMemberAnnotation SingleVariableDeclaration SimpleType SimpleName string
path param SimpleName SingleMemberAnnotation SingleVariableDeclaration SimpleName guid
guid StringLiteral SingleMemberAnnotation SingleVariableDeclaration SimpleName guid
string SimpleName SimpleType SingleVariableDeclaration SimpleName guid
path param SimpleName SingleMemberAnnotation StringLiteral classification name
path param SimpleName SingleMemberAnnotation SingleVariableDeclaration SimpleType SimpleName string
classification name StringLiteral SingleMemberAnnotation SingleVariableDeclaration SimpleType SimpleName string
path param SimpleName SingleMemberAnnotation SingleVariableDeclaration SimpleName classification name
classification name StringLiteral SingleMemberAnnotation SingleVariableDeclaration SimpleName classification name
string SimpleName SimpleType SingleVariableDeclaration SimpleName classification name
string utils SimpleName MethodInvocation SimpleName is empty
string utils SimpleName MethodInvocation SimpleName guid
is empty SimpleName MethodInvocation SimpleName guid
atlas base exception SimpleName SimpleType ClassInstanceCreation QualifiedName atlas error codeinstance guid not found
atlas base exception SimpleName SimpleType ClassInstanceCreation SimpleName guid
atlas error codeinstance guid not found QualifiedName ClassInstanceCreation SimpleName guid
validate type SimpleName MethodInvocation SimpleName classification name
validate type SimpleName MethodInvocation QualifiedName type categoryclassification
classification name SimpleName MethodInvocation QualifiedName type categoryclassification
metadata service SimpleName MethodInvocation SimpleName get trait definition
metadata service SimpleName MethodInvocation SimpleName guid
metadata service SimpleName MethodInvocation SimpleName classification name
get trait definition SimpleName MethodInvocation SimpleName guid
get trait definition SimpleName MethodInvocation SimpleName classification name
guid SimpleName MethodInvocation SimpleName classification name
trait SimpleName VariableDeclarationFragment MethodInvocation SimpleName metadata service
trait SimpleName VariableDeclarationFragment MethodInvocation SimpleName get trait definition
trait SimpleName VariableDeclarationFragment MethodInvocation SimpleName guid
trait SimpleName VariableDeclarationFragment MethodInvocation SimpleName classification name
i struct SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName trait
rest adapters SimpleName MethodInvocation SimpleName get classification
rest adapters SimpleName MethodInvocation SimpleName trait
get classification SimpleName MethodInvocation SimpleName trait
atlas exception SimpleName SimpleType SingleVariableDeclaration SimpleName e
to atlas base exception SimpleName MethodInvocation SimpleName e
get SimpleName MarkerAnnotation MethodDeclaration SingleMemberAnnotation SimpleName path
get SimpleName MarkerAnnotation MethodDeclaration SingleMemberAnnotation StringLiteral guidguidclassificationclassification name
get SimpleName MarkerAnnotation MethodDeclaration SingleMemberAnnotation SimpleName produces
get SimpleName MarkerAnnotation MethodDeclaration SingleMemberAnnotation QualifiedName servletsjson media type
get SimpleName MarkerAnnotation MethodDeclaration Modifier public
get SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName atlas classification
get SimpleName MarkerAnnotation MethodDeclaration SimpleName get classification
path SimpleName SingleMemberAnnotation MethodDeclaration SingleMemberAnnotation SimpleName produces
path SimpleName SingleMemberAnnotation MethodDeclaration SingleMemberAnnotation QualifiedName servletsjson media type
guidguidclassificationclassification name StringLiteral SingleMemberAnnotation MethodDeclaration SingleMemberAnnotation SimpleName produces
guidguidclassificationclassification name StringLiteral SingleMemberAnnotation MethodDeclaration SingleMemberAnnotation QualifiedName servletsjson media type
path SimpleName SingleMemberAnnotation MethodDeclaration Modifier public
guidguidclassificationclassification name StringLiteral SingleMemberAnnotation MethodDeclaration Modifier public
path SimpleName SingleMemberAnnotation MethodDeclaration SimpleType SimpleName atlas classification
guidguidclassificationclassification name StringLiteral SingleMemberAnnotation MethodDeclaration SimpleType SimpleName atlas classification
path SimpleName SingleMemberAnnotation MethodDeclaration SimpleName get classification
guidguidclassificationclassification name StringLiteral SingleMemberAnnotation MethodDeclaration SimpleName get classification
path SimpleName SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName guid
guidguidclassificationclassification name StringLiteral SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName guid
produces SimpleName SingleMemberAnnotation MethodDeclaration Modifier public
servletsjson media type QualifiedName SingleMemberAnnotation MethodDeclaration Modifier public
produces SimpleName SingleMemberAnnotation MethodDeclaration SimpleType SimpleName atlas classification
servletsjson media type QualifiedName SingleMemberAnnotation MethodDeclaration SimpleType SimpleName atlas classification
produces SimpleName SingleMemberAnnotation MethodDeclaration SimpleName get classification
servletsjson media type QualifiedName SingleMemberAnnotation MethodDeclaration SimpleName get classification
produces SimpleName SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName guid
servletsjson media type QualifiedName SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName guid
produces SimpleName SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName classification name
servletsjson media type QualifiedName SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName classification name
public Modifier MethodDeclaration SimpleType SimpleName atlas classification
public Modifier MethodDeclaration SimpleName get classification
public Modifier MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation SimpleName path param
public Modifier MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation StringLiteral guid
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName guid
public Modifier MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation SimpleName path param
public Modifier MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation StringLiteral classification name
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName classification name
public Modifier MethodDeclaration SimpleType SimpleName atlas base exception
atlas classification SimpleName SimpleType MethodDeclaration SimpleName get classification
atlas classification SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName guid
atlas classification SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName classification name
atlas classification SimpleName SimpleType MethodDeclaration SimpleType SimpleName atlas base exception
get classification SimpleName MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation SimpleName path param
get classification SimpleName MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation StringLiteral guid
get classification SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get classification SimpleName MethodDeclaration SingleVariableDeclaration SimpleName guid
get classification SimpleName MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation SimpleName path param
get classification SimpleName MethodDeclaration SingleVariableDeclaration SingleMemberAnnotation StringLiteral classification name
get classification SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get classification SimpleName MethodDeclaration SingleVariableDeclaration SimpleName classification name
get classification SimpleName MethodDeclaration SimpleType SimpleName atlas base exception
guid SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classification name
guid SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
classification name SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName get
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName path
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral guidguidclassificationclassification name
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName produces
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation QualifiedName servletsjson media type
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas classification
public Modifier TypeDeclaration MethodDeclaration SimpleName get classification
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName guid
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classification name
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName get
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName path
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral guidguidclassificationclassification name
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName produces
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation QualifiedName servletsjson media type
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas classification
test SimpleName TypeDeclaration MethodDeclaration SimpleName get classification
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName guid
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classification name
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
