bootstrap types registrar SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName reserved types registrar
i bootstrap types registrar SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName bootstrap types registrar
bootstrap types registrar SimpleName MethodInvocation SimpleName register types
bootstrap types registrar SimpleName MethodInvocation StringLiteral somedir
bootstrap types registrar SimpleName MethodInvocation SimpleName type system
bootstrap types registrar SimpleName MethodInvocation SimpleName metadata service
register types SimpleName MethodInvocation StringLiteral somedir
register types SimpleName MethodInvocation SimpleName type system
register types SimpleName MethodInvocation SimpleName metadata service
somedir StringLiteral MethodInvocation SimpleName type system
somedir StringLiteral MethodInvocation SimpleName metadata service
type system SimpleName MethodInvocation SimpleName metadata service
verify zero interactions SimpleName MethodInvocation SimpleName type system
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test registration with no files
test SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName atlas exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test registration with no files
public Modifier MethodDeclaration SimpleType SimpleName atlas exception
void PrimitiveType MethodDeclaration SimpleName test registration with no files
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas exception
test registration with no files SimpleName MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test registration with no files
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test registration with no files
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
