table name SimpleName VariableDeclarationFragment MethodInvocation SimpleName create table
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName table name
new name SimpleName VariableDeclarationFragment MethodInvocation SimpleName table name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName new name
alter table StringLiteral InfixExpression SimpleName table name
alter table StringLiteral InfixExpression StringLiteral rename to
alter table StringLiteral InfixExpression SimpleName new name
table name SimpleName InfixExpression StringLiteral rename to
table name SimpleName InfixExpression SimpleName new name
rename to StringLiteral InfixExpression SimpleName new name
query SimpleName VariableDeclarationFragment InfixExpression StringLiteral alter table
query SimpleName VariableDeclarationFragment InfixExpression SimpleName table name
query SimpleName VariableDeclarationFragment InfixExpression StringLiteral rename to
query SimpleName VariableDeclarationFragment InfixExpression SimpleName new name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName query
run command SimpleName MethodInvocation SimpleName query
assert table is registered SimpleName MethodInvocation SimpleName default db
assert table is registered SimpleName MethodInvocation SimpleName new name
default db SimpleName MethodInvocation SimpleName new name
assert table is not registered SimpleName MethodInvocation SimpleName default db
assert table is not registered SimpleName MethodInvocation SimpleName table name
default db SimpleName MethodInvocation SimpleName table name
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test alter table rename
test SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test alter table rename
public Modifier MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration SimpleName test alter table rename
void PrimitiveType MethodDeclaration SimpleType SimpleName exception
test alter table rename SimpleName MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test alter table rename
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test alter table rename
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
