object SimpleName SimpleType SingleVariableDeclaration SimpleName o
o SimpleName MethodInvocation SimpleName get class
get class SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName o
get class SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get class
id SimpleName SimpleType CastExpression SimpleName o
id SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName id
id SimpleName VariableDeclarationFragment CastExpression SimpleName o
id SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName id
version SimpleName InfixExpression QualifiedName id version
type name SimpleName MethodInvocation SimpleName equals
type name SimpleName MethodInvocation QualifiedName id type name
equals SimpleName MethodInvocation QualifiedName id type name
id SimpleName MethodInvocation SimpleName equals
id SimpleName MethodInvocation QualifiedName id id
equals SimpleName MethodInvocation QualifiedName id id
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType boolean
override SimpleName MarkerAnnotation MethodDeclaration SimpleName equals
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName equals
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier MethodDeclaration Block ReturnStatement BooleanLiteral true
boolean PrimitiveType MethodDeclaration SimpleName equals
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName o
boolean PrimitiveType MethodDeclaration Block ReturnStatement BooleanLiteral true
equals SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
equals SimpleName MethodDeclaration SingleVariableDeclaration SimpleName o
equals SimpleName MethodDeclaration Block ReturnStatement BooleanLiteral true
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName equals
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName equals
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
