collection SimpleName SimpleType ParameterizedType SimpleType SimpleName i typed referenceable instance
collection SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName entities
i typed referenceable instance SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName entities
list SimpleName SimpleType ParameterizedType SimpleType SimpleName entity audit event
system SimpleName MethodInvocation SimpleName current time millis
current time SimpleName VariableDeclarationFragment MethodInvocation SimpleName system
current time SimpleName VariableDeclarationFragment MethodInvocation SimpleName current time millis
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName current time
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName system
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName current time millis
i typed referenceable instance SimpleName SimpleType SingleVariableDeclaration SimpleName entity
instance serialization SimpleName MethodInvocation SimpleName to json
instance serialization SimpleName MethodInvocation SimpleName entity
instance serialization SimpleName MethodInvocation BooleanLiteral true
to json SimpleName MethodInvocation SimpleName entity
to json SimpleName MethodInvocation BooleanLiteral true
entity SimpleName MethodInvocation BooleanLiteral true
created StringLiteral InfixExpression MethodInvocation SimpleName instance serialization
created StringLiteral InfixExpression MethodInvocation SimpleName to json
created StringLiteral InfixExpression MethodInvocation SimpleName entity
created StringLiteral InfixExpression MethodInvocation BooleanLiteral true
create event SimpleName MethodInvocation SimpleName entity
create event SimpleName MethodInvocation SimpleName current time
create event SimpleName MethodInvocation QualifiedName entity audit evententity audit actionentity create
create event SimpleName MethodInvocation InfixExpression StringLiteral created
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName instance serialization
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName entity
create event SimpleName MethodInvocation InfixExpression MethodInvocation BooleanLiteral true
entity SimpleName MethodInvocation SimpleName current time
entity SimpleName MethodInvocation QualifiedName entity audit evententity audit actionentity create
entity SimpleName MethodInvocation InfixExpression StringLiteral created
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName instance serialization
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName entity
entity SimpleName MethodInvocation InfixExpression MethodInvocation BooleanLiteral true
current time SimpleName MethodInvocation QualifiedName entity audit evententity audit actionentity create
current time SimpleName MethodInvocation InfixExpression StringLiteral created
current time SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName instance serialization
current time SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
current time SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName entity
current time SimpleName MethodInvocation InfixExpression MethodInvocation BooleanLiteral true
entity audit evententity audit actionentity create QualifiedName MethodInvocation InfixExpression StringLiteral created
entity audit evententity audit actionentity create QualifiedName MethodInvocation InfixExpression MethodInvocation SimpleName instance serialization
entity audit evententity audit actionentity create QualifiedName MethodInvocation InfixExpression MethodInvocation SimpleName to json
entity audit evententity audit actionentity create QualifiedName MethodInvocation InfixExpression MethodInvocation SimpleName entity
entity audit evententity audit actionentity create QualifiedName MethodInvocation InfixExpression MethodInvocation BooleanLiteral true
event SimpleName VariableDeclarationFragment MethodInvocation SimpleName create event
event SimpleName VariableDeclarationFragment MethodInvocation SimpleName entity
event SimpleName VariableDeclarationFragment MethodInvocation SimpleName current time
event SimpleName VariableDeclarationFragment MethodInvocation QualifiedName entity audit evententity audit actionentity create
event SimpleName VariableDeclarationFragment MethodInvocation InfixExpression StringLiteral created
entity audit event SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName event
events SimpleName MethodInvocation SimpleName add
events SimpleName MethodInvocation SimpleName event
add SimpleName MethodInvocation SimpleName event
i typed referenceable instance SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName entities
entity SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName entities
audit repository SimpleName MethodInvocation SimpleName put events
audit repository SimpleName MethodInvocation SimpleName events
put events SimpleName MethodInvocation SimpleName events
long PrimitiveType VariableDeclarationStatement Block EnhancedForStatement SimpleName entities
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName on entities added
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName entities
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName atlas exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName on entities added
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName entities
public Modifier MethodDeclaration SimpleType SimpleName atlas exception
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
public Modifier MethodDeclaration Block EnhancedForStatement SimpleName entities
void PrimitiveType MethodDeclaration SimpleName on entities added
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName entities
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas exception
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
void PrimitiveType MethodDeclaration Block EnhancedForStatement SimpleName entities
on entities added SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entities
on entities added SimpleName MethodDeclaration SimpleType SimpleName atlas exception
on entities added SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
on entities added SimpleName MethodDeclaration Block EnhancedForStatement SimpleName entities
entities SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName on entities added
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entities
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName on entities added
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entities
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
