buffer SimpleName SimpleType SingleVariableDeclaration SimpleName buffer
buffer SimpleName MethodInvocation SimpleName get int
t columns SimpleName VariableDeclarationFragment MethodInvocation SimpleName buffer
t columns SimpleName VariableDeclarationFragment MethodInvocation SimpleName get int
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName t columns
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName buffer
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get int
buffer SimpleName MethodInvocation SimpleName get int
t rows SimpleName VariableDeclarationFragment MethodInvocation SimpleName buffer
t rows SimpleName VariableDeclarationFragment MethodInvocation SimpleName get int
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName t rows
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName buffer
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get int
buffer SimpleName MethodInvocation SimpleName get int
t width SimpleName VariableDeclarationFragment MethodInvocation SimpleName buffer
t width SimpleName VariableDeclarationFragment MethodInvocation SimpleName get int
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName t width
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName buffer
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get int
buffer SimpleName MethodInvocation SimpleName get int
t height SimpleName VariableDeclarationFragment MethodInvocation SimpleName buffer
t height SimpleName VariableDeclarationFragment MethodInvocation SimpleName get int
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName t height
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName buffer
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName get int
log SimpleName MethodInvocation SimpleName is debug enabled
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral handle window change ({} - {}) ({} {})
log SimpleName MethodInvocation SimpleName t columns
log SimpleName MethodInvocation SimpleName t rows
debug SimpleName MethodInvocation StringLiteral handle window change ({} - {}) ({} {})
debug SimpleName MethodInvocation SimpleName t columns
debug SimpleName MethodInvocation SimpleName t rows
debug SimpleName MethodInvocation SimpleName t width
handle window change ({} - {}) ({} {}) StringLiteral MethodInvocation SimpleName t columns
handle window change ({} - {}) ({} {}) StringLiteral MethodInvocation SimpleName t rows
handle window change ({} - {}) ({} {}) StringLiteral MethodInvocation SimpleName t width
handle window change ({} - {}) ({} {}) StringLiteral MethodInvocation SimpleName t height
t columns SimpleName MethodInvocation SimpleName t rows
t columns SimpleName MethodInvocation SimpleName t width
t columns SimpleName MethodInvocation SimpleName t height
t rows SimpleName MethodInvocation SimpleName t width
t rows SimpleName MethodInvocation SimpleName t height
t width SimpleName MethodInvocation SimpleName t height
e SimpleName VariableDeclarationFragment MethodInvocation SimpleName get environment
standard environment SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName e
integer SimpleName MethodInvocation SimpleName to string
integer SimpleName MethodInvocation SimpleName t columns
to string SimpleName MethodInvocation SimpleName t columns
e SimpleName MethodInvocation SimpleName set
e SimpleName MethodInvocation QualifiedName environmentenv columns
e SimpleName MethodInvocation MethodInvocation SimpleName integer
e SimpleName MethodInvocation MethodInvocation SimpleName to string
e SimpleName MethodInvocation MethodInvocation SimpleName t columns
set SimpleName MethodInvocation QualifiedName environmentenv columns
set SimpleName MethodInvocation MethodInvocation SimpleName integer
set SimpleName MethodInvocation MethodInvocation SimpleName to string
set SimpleName MethodInvocation MethodInvocation SimpleName t columns
environmentenv columns QualifiedName MethodInvocation MethodInvocation SimpleName integer
environmentenv columns QualifiedName MethodInvocation MethodInvocation SimpleName to string
environmentenv columns QualifiedName MethodInvocation MethodInvocation SimpleName t columns
integer SimpleName MethodInvocation SimpleName to string
integer SimpleName MethodInvocation SimpleName t rows
to string SimpleName MethodInvocation SimpleName t rows
e SimpleName MethodInvocation SimpleName set
e SimpleName MethodInvocation QualifiedName environmentenv lines
e SimpleName MethodInvocation MethodInvocation SimpleName integer
e SimpleName MethodInvocation MethodInvocation SimpleName to string
e SimpleName MethodInvocation MethodInvocation SimpleName t rows
set SimpleName MethodInvocation QualifiedName environmentenv lines
set SimpleName MethodInvocation MethodInvocation SimpleName integer
set SimpleName MethodInvocation MethodInvocation SimpleName to string
set SimpleName MethodInvocation MethodInvocation SimpleName t rows
environmentenv lines QualifiedName MethodInvocation MethodInvocation SimpleName integer
environmentenv lines QualifiedName MethodInvocation MethodInvocation SimpleName to string
environmentenv lines QualifiedName MethodInvocation MethodInvocation SimpleName t rows
e SimpleName MethodInvocation SimpleName signal
e SimpleName MethodInvocation QualifiedName signalwinch
signal SimpleName MethodInvocation QualifiedName signalwinch
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
protected Modifier MethodDeclaration PrimitiveType boolean
protected Modifier MethodDeclaration SimpleName handle window change
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName buffer
protected Modifier MethodDeclaration SimpleType SimpleName io exception
protected Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
protected Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
protected Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
protected Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
protected Modifier MethodDeclaration Block ReturnStatement BooleanLiteral true
boolean PrimitiveType MethodDeclaration SimpleName handle window change
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName buffer
boolean PrimitiveType MethodDeclaration SimpleType SimpleName io exception
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
boolean PrimitiveType MethodDeclaration Block ReturnStatement BooleanLiteral true
handle window change SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
handle window change SimpleName MethodDeclaration SingleVariableDeclaration SimpleName buffer
handle window change SimpleName MethodDeclaration SimpleType SimpleName io exception
handle window change SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
handle window change SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
handle window change SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
handle window change SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
handle window change SimpleName MethodDeclaration Block ReturnStatement BooleanLiteral true
buffer SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName handle window change
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName handle window change
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
