fields SimpleName SimpleType SingleVariableDeclaration SimpleName field
field SimpleName SwitchStatement SwitchCase SimpleName username
field SimpleName SwitchStatement ReturnStatement MethodInvocation SimpleName get username
field SimpleName SwitchStatement SwitchCase SimpleName password
field SimpleName SwitchStatement ReturnStatement MethodInvocation SimpleName get password
username SimpleName SwitchCase SwitchStatement SwitchCase SimpleName password
public Modifier MethodDeclaration SimpleType SimpleName object
public Modifier MethodDeclaration SimpleName get field value
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName fields
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName field
public Modifier MethodDeclaration Block SwitchStatement SimpleName field
object SimpleName SimpleType MethodDeclaration SimpleName get field value
object SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName field
get field value SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName fields
get field value SimpleName MethodDeclaration SingleVariableDeclaration SimpleName field
get field value SimpleName MethodDeclaration Block SwitchStatement SimpleName field
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName object
public Modifier TypeDeclaration MethodDeclaration SimpleName get field value
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName field
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName object
test SimpleName TypeDeclaration MethodDeclaration SimpleName get field value
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName field
