string SimpleName SimpleType SingleVariableDeclaration SimpleName table name
table name SimpleName FieldAccess Assignment SimpleName table name
public Modifier MethodDeclaration SimpleType SimpleName remove table property args
public Modifier MethodDeclaration SimpleName set table name
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName table name
remove table property args SimpleName SimpleType MethodDeclaration SimpleName set table name
remove table property args SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName table name
set table name SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
set table name SimpleName MethodDeclaration SingleVariableDeclaration SimpleName table name
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName remove table property args
public Modifier TypeDeclaration MethodDeclaration SimpleName set table name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName table name
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName remove table property args
test SimpleName TypeDeclaration MethodDeclaration SimpleName set table name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName table name
