command factory SimpleName SimpleType MethodDeclaration SimpleName get delegate command factory
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName command factory
public Modifier TypeDeclaration MethodDeclaration SimpleName get delegate command factory
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName command factory
test SimpleName TypeDeclaration MethodDeclaration SimpleName get delegate command factory
