public Modifier MethodDeclaration SimpleType SimpleName node
public Modifier MethodDeclaration SimpleName next sibling
node SimpleName SimpleType MethodDeclaration SimpleName next sibling
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName node
public Modifier TypeDeclaration MethodDeclaration SimpleName next sibling
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName node
test SimpleName TypeDeclaration MethodDeclaration SimpleName next sibling
