state SimpleName Assignment SimpleName invalid
document SimpleName MethodInvocation SimpleName detach node iterator
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName detach
void PrimitiveType MethodDeclaration SimpleName detach
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName detach
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName detach
