string SimpleName SimpleType SingleVariableDeclaration SimpleName id
node SimpleName SimpleType SingleVariableDeclaration SimpleName node
node SimpleName InstanceofExpression SimpleType SimpleName element with id
element with id SimpleName SimpleType CastExpression SimpleName node
e SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName element with id
e SimpleName VariableDeclarationFragment CastExpression SimpleName node
element with id SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName e
e SimpleName MethodInvocation SimpleName get id
e SimpleName MethodInvocation MethodInvocation SimpleName equals
get id SimpleName MethodInvocation MethodInvocation SimpleName equals
e SimpleName MethodInvocation MethodInvocation SimpleName id
get id SimpleName MethodInvocation MethodInvocation SimpleName id
equals SimpleName MethodInvocation SimpleName id
element SimpleName SimpleType CastExpression SimpleName e
node SimpleName MethodInvocation SimpleName get first child
n SimpleName VariableDeclarationFragment MethodInvocation SimpleName node
n SimpleName VariableDeclarationFragment MethodInvocation SimpleName get first child
node SimpleName SimpleType VariableDeclarationExpression VariableDeclarationFragment SimpleName n
n SimpleName MethodInvocation SimpleName get next sibling
n SimpleName Assignment MethodInvocation SimpleName n
n SimpleName Assignment MethodInvocation SimpleName get next sibling
get by id SimpleName MethodInvocation SimpleName id
get by id SimpleName MethodInvocation SimpleName n
id SimpleName MethodInvocation SimpleName n
result SimpleName VariableDeclarationFragment MethodInvocation SimpleName get by id
result SimpleName VariableDeclarationFragment MethodInvocation SimpleName id
result SimpleName VariableDeclarationFragment MethodInvocation SimpleName n
element SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName result
n SimpleName InfixExpression ForStatement Assignment SimpleName n
protected Modifier MethodDeclaration Modifier static
protected Modifier MethodDeclaration SimpleType SimpleName element
protected Modifier MethodDeclaration SimpleName get by id
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName id
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName node
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName node
static Modifier MethodDeclaration SimpleType SimpleName element
static Modifier MethodDeclaration SimpleName get by id
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName id
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName node
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName node
element SimpleName SimpleType MethodDeclaration SimpleName get by id
element SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName id
element SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName node
get by id SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get by id SimpleName MethodDeclaration SingleVariableDeclaration SimpleName id
get by id SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName node
get by id SimpleName MethodDeclaration SingleVariableDeclaration SimpleName node
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName node
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName element
public Modifier TypeDeclaration MethodDeclaration SimpleName get by id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName node
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName element
test SimpleName TypeDeclaration MethodDeclaration SimpleName get by id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName node
