t credentials SimpleName SimpleType SingleVariableDeclaration SimpleName c
string SimpleName SimpleType SingleVariableDeclaration SimpleName user
string SimpleName SimpleType SingleVariableDeclaration SimpleName namespace
can modify namespace permission SimpleName MethodInvocation SimpleName c
can modify namespace permission SimpleName MethodInvocation SimpleName user
can modify namespace permission SimpleName MethodInvocation SimpleName namespace
c SimpleName MethodInvocation SimpleName user
c SimpleName MethodInvocation SimpleName namespace
user SimpleName MethodInvocation SimpleName namespace
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName can grant namespace
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName t credentials
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName c
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName user
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName namespace
boolean PrimitiveType MethodDeclaration SimpleName can grant namespace
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName t credentials
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName c
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName user
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName namespace
boolean PrimitiveType MethodDeclaration SimpleType SimpleName thrift security exception
can grant namespace SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName t credentials
can grant namespace SimpleName MethodDeclaration SingleVariableDeclaration SimpleName c
can grant namespace SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
can grant namespace SimpleName MethodDeclaration SingleVariableDeclaration SimpleName user
can grant namespace SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
can grant namespace SimpleName MethodDeclaration SingleVariableDeclaration SimpleName namespace
can grant namespace SimpleName MethodDeclaration SimpleType SimpleName thrift security exception
c SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user
c SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
c SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName thrift security exception
user SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
user SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName thrift security exception
namespace SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName thrift security exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName can grant namespace
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName c
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName thrift security exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName can grant namespace
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName c
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName thrift security exception
