string SimpleName SimpleType SingleVariableDeclaration SimpleName location
server queue SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName server queue
server queues SimpleName MethodInvocation SimpleName get
server queues SimpleName MethodInvocation SimpleName location
get SimpleName MethodInvocation SimpleName location
server queue SimpleName Assignment MethodInvocation SimpleName server queues
server queue SimpleName Assignment MethodInvocation SimpleName get
server queue SimpleName Assignment MethodInvocation SimpleName location
server queue SimpleName Assignment ClassInstanceCreation SimpleType SimpleName server queue
server queues SimpleName MethodInvocation SimpleName put
server queues SimpleName MethodInvocation SimpleName location
server queues SimpleName MethodInvocation SimpleName server queue
put SimpleName MethodInvocation SimpleName location
put SimpleName MethodInvocation SimpleName server queue
location SimpleName MethodInvocation SimpleName server queue
server queues SimpleName SynchronizedStatement Block ReturnStatement SimpleName server queue
private Modifier MethodDeclaration SimpleType SimpleName server queue
private Modifier MethodDeclaration SimpleName get server queue
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName location
private Modifier MethodDeclaration Block SynchronizedStatement SimpleName server queues
private Modifier MethodDeclaration Block ReturnStatement SimpleName server queue
server queue SimpleName SimpleType MethodDeclaration SimpleName get server queue
server queue SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName location
get server queue SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get server queue SimpleName MethodDeclaration SingleVariableDeclaration SimpleName location
get server queue SimpleName MethodDeclaration Block SynchronizedStatement SimpleName server queues
get server queue SimpleName MethodDeclaration Block ReturnStatement SimpleName server queue
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName server queue
public Modifier TypeDeclaration MethodDeclaration SimpleName get server queue
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName location
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName server queue
test SimpleName TypeDeclaration MethodDeclaration SimpleName get server queue
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName location
