test utils SimpleName MethodInvocation SimpleName create dept eg
test utils SimpleName MethodInvocation SimpleName type system
create dept eg SimpleName MethodInvocation SimpleName type system
hr dept SimpleName VariableDeclarationFragment MethodInvocation SimpleName test utils
hr dept SimpleName VariableDeclarationFragment MethodInvocation SimpleName create dept eg
hr dept SimpleName VariableDeclarationFragment MethodInvocation SimpleName type system
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName hr dept
type system SimpleName MethodInvocation SimpleName get data type
type system SimpleName MethodInvocation TypeLiteral SimpleType SimpleName class type
type system SimpleName MethodInvocation StringLiteral department
get data type SimpleName MethodInvocation TypeLiteral SimpleType SimpleName class type
get data type SimpleName MethodInvocation StringLiteral department
class type SimpleName SimpleType TypeLiteral MethodInvocation StringLiteral department
dept type SimpleName VariableDeclarationFragment MethodInvocation SimpleName type system
dept type SimpleName VariableDeclarationFragment MethodInvocation SimpleName get data type
dept type SimpleName VariableDeclarationFragment MethodInvocation StringLiteral department
class type SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName dept type
dept type SimpleName MethodInvocation SimpleName convert
dept type SimpleName MethodInvocation SimpleName hr dept
dept type SimpleName MethodInvocation QualifiedName multiplicityrequired
convert SimpleName MethodInvocation SimpleName hr dept
convert SimpleName MethodInvocation QualifiedName multiplicityrequired
hr dept SimpleName MethodInvocation QualifiedName multiplicityrequired
hr dept SimpleName VariableDeclarationFragment MethodInvocation SimpleName dept type
hr dept SimpleName VariableDeclarationFragment MethodInvocation SimpleName convert
hr dept SimpleName VariableDeclarationFragment MethodInvocation SimpleName hr dept
hr dept SimpleName VariableDeclarationFragment MethodInvocation QualifiedName multiplicityrequired
i typed referenceable instance SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName hr dept
repository service SimpleName MethodInvocation SimpleName create entities
repository service SimpleName MethodInvocation SimpleName hr dept
create entities SimpleName MethodInvocation SimpleName hr dept
guids SimpleName VariableDeclarationFragment MethodInvocation SimpleName repository service
guids SimpleName VariableDeclarationFragment MethodInvocation SimpleName create entities
guids SimpleName VariableDeclarationFragment MethodInvocation SimpleName hr dept
assert SimpleName MethodInvocation SimpleName assert not null
assert SimpleName MethodInvocation SimpleName guids
assert not null SimpleName MethodInvocation SimpleName guids
assert SimpleName MethodInvocation SimpleName assert equals
assert SimpleName MethodInvocation QualifiedName guidslength
assert SimpleName MethodInvocation NumberLiteral empty
assert equals SimpleName MethodInvocation QualifiedName guidslength
assert equals SimpleName MethodInvocation NumberLiteral empty
guidslength QualifiedName MethodInvocation NumberLiteral empty
guids SimpleName ArrayAccess NumberLiteral empty
guid SimpleName Assignment ArrayAccess SimpleName guids
guid SimpleName Assignment ArrayAccess NumberLiteral empty
assert SimpleName MethodInvocation SimpleName assert not null
assert SimpleName MethodInvocation SimpleName guid
assert not null SimpleName MethodInvocation SimpleName guid
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test submit entity
test SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test submit entity
public Modifier MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration SimpleName test submit entity
void PrimitiveType MethodDeclaration SimpleType SimpleName exception
test submit entity SimpleName MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test submit entity
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test submit entity
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
