string SimpleName SimpleType SingleVariableDeclaration SimpleName str
string utils SimpleName MethodInvocation SimpleName is empty
string utils SimpleName MethodInvocation SimpleName str
is empty SimpleName MethodInvocation SimpleName str
str SimpleName MethodInvocation SimpleName to lower case
str SimpleName MethodInvocation MethodInvocation SimpleName trim
to lower case SimpleName MethodInvocation MethodInvocation SimpleName trim
private Modifier MethodDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SimpleName normalize
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName str
string SimpleName SimpleType MethodDeclaration SimpleName normalize
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName str
normalize SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
normalize SimpleName MethodDeclaration SingleVariableDeclaration SimpleName str
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName normalize
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName str
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName normalize
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName str
