int PrimitiveType SingleVariableDeclaration SimpleName cmd
buffer SimpleName SimpleType SingleVariableDeclaration SimpleName buffer
current auth SimpleName MethodInvocation SimpleName get username
username SimpleName VariableDeclarationFragment ConditionalExpression MethodInvocation SimpleName current auth
username SimpleName VariableDeclarationFragment ConditionalExpression MethodInvocation SimpleName get username
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName username
log SimpleName MethodInvocation SimpleName is debug enabled
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral handle authentication failure
log SimpleName MethodInvocation SimpleName username
log SimpleName MethodInvocation SimpleName session
debug SimpleName MethodInvocation StringLiteral handle authentication failure
debug SimpleName MethodInvocation SimpleName username
debug SimpleName MethodInvocation SimpleName session
handle authentication failure StringLiteral MethodInvocation SimpleName username
handle authentication failure StringLiteral MethodInvocation SimpleName session
username SimpleName MethodInvocation SimpleName session
buffer utils SimpleName MethodInvocation SimpleName clear
buffer utils SimpleName MethodInvocation SimpleName buffer
clear SimpleName MethodInvocation SimpleName buffer
session SimpleName MethodInvocation SimpleName prepare buffer
session SimpleName MethodInvocation QualifiedName ssh constantsssh msg userauth failure
session SimpleName MethodInvocation MethodInvocation SimpleName buffer utils
session SimpleName MethodInvocation MethodInvocation SimpleName clear
session SimpleName MethodInvocation MethodInvocation SimpleName buffer
prepare buffer SimpleName MethodInvocation QualifiedName ssh constantsssh msg userauth failure
prepare buffer SimpleName MethodInvocation MethodInvocation SimpleName buffer utils
prepare buffer SimpleName MethodInvocation MethodInvocation SimpleName clear
prepare buffer SimpleName MethodInvocation MethodInvocation SimpleName buffer
ssh constantsssh msg userauth failure QualifiedName MethodInvocation MethodInvocation SimpleName buffer utils
ssh constantsssh msg userauth failure QualifiedName MethodInvocation MethodInvocation SimpleName clear
ssh constantsssh msg userauth failure QualifiedName MethodInvocation MethodInvocation SimpleName buffer
buffer SimpleName Assignment MethodInvocation SimpleName session
buffer SimpleName Assignment MethodInvocation SimpleName prepare buffer
buffer SimpleName Assignment MethodInvocation QualifiedName ssh constantsssh msg userauth failure
buffer SimpleName Assignment MethodInvocation MethodInvocation SimpleName buffer utils
buffer SimpleName Assignment MethodInvocation MethodInvocation SimpleName clear
buffer SimpleName Assignment MethodInvocation MethodInvocation SimpleName buffer
auth methods SimpleName MethodInvocation SimpleName size
auth methods SimpleName MethodInvocation InfixExpression NumberLiteral empty
size SimpleName MethodInvocation InfixExpression NumberLiteral empty
empty NumberLiteral InfixExpression ParenthesizedExpression InfixExpression QualifiedName bytesize
string builder SimpleName SimpleType ClassInstanceCreation InfixExpression QualifiedName bytesize
sb SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName string builder
sb SimpleName VariableDeclarationFragment ClassInstanceCreation InfixExpression QualifiedName bytesize
string builder SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName sb
list SimpleName SimpleType ParameterizedType SimpleType SimpleName string
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName l
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName l
generic utils SimpleName MethodInvocation SimpleName size
generic utils SimpleName MethodInvocation SimpleName l
size SimpleName MethodInvocation SimpleName l
generic utils SimpleName MethodInvocation InfixExpression NumberLiteral empty
size SimpleName MethodInvocation InfixExpression NumberLiteral empty
l SimpleName MethodInvocation InfixExpression NumberLiteral empty
l SimpleName MethodInvocation SimpleName get
l SimpleName MethodInvocation NumberLiteral empty
get SimpleName MethodInvocation NumberLiteral empty
m SimpleName VariableDeclarationFragment MethodInvocation SimpleName l
m SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
m SimpleName VariableDeclarationFragment MethodInvocation NumberLiteral empty
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName m
user auth none factoryname QualifiedName MethodInvocation SimpleName equals
user auth none factoryname QualifiedName MethodInvocation SimpleName m
equals SimpleName MethodInvocation SimpleName m
sb SimpleName MethodInvocation SimpleName length
sb SimpleName MethodInvocation InfixExpression NumberLiteral empty
length SimpleName MethodInvocation InfixExpression NumberLiteral empty
sb SimpleName MethodInvocation SimpleName append
sb SimpleName MethodInvocation StringLiteral empty
append SimpleName MethodInvocation StringLiteral empty
sb SimpleName MethodInvocation SimpleName append
sb SimpleName MethodInvocation SimpleName m
append SimpleName MethodInvocation SimpleName m
l SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName auth methods
sb SimpleName MethodInvocation SimpleName to string
buffer SimpleName MethodInvocation SimpleName put string
buffer SimpleName MethodInvocation MethodInvocation SimpleName sb
buffer SimpleName MethodInvocation MethodInvocation SimpleName to string
put string SimpleName MethodInvocation MethodInvocation SimpleName sb
put string SimpleName MethodInvocation MethodInvocation SimpleName to string
buffer SimpleName MethodInvocation SimpleName put boolean
buffer SimpleName MethodInvocation BooleanLiteral false
put boolean SimpleName MethodInvocation BooleanLiteral false
session SimpleName MethodInvocation SimpleName write packet
session SimpleName MethodInvocation SimpleName buffer
write packet SimpleName MethodInvocation SimpleName buffer
current auth SimpleName MethodInvocation SimpleName destroy
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName handle authentication failure
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName cmd
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName buffer
protected Modifier MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration SimpleName handle authentication failure
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName cmd
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName buffer
void PrimitiveType MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration Block EnhancedForStatement SimpleName auth methods
handle authentication failure SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
handle authentication failure SimpleName MethodDeclaration SingleVariableDeclaration SimpleName cmd
handle authentication failure SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
handle authentication failure SimpleName MethodDeclaration SingleVariableDeclaration SimpleName buffer
handle authentication failure SimpleName MethodDeclaration SimpleType SimpleName exception
handle authentication failure SimpleName MethodDeclaration Block EnhancedForStatement SimpleName auth methods
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
cmd SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
cmd SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
buffer SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName handle authentication failure
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cmd
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName handle authentication failure
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cmd
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
