keyboard interactive authenticator SimpleName SimpleType SingleVariableDeclaration SimpleName auth
interactive authenticator SimpleName Assignment SimpleName auth
public Modifier MethodDeclaration SimpleType SimpleName server builder
public Modifier MethodDeclaration SimpleName interactive authenticator
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName keyboard interactive authenticator
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName auth
server builder SimpleName SimpleType MethodDeclaration SimpleName interactive authenticator
server builder SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName auth
interactive authenticator SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName keyboard interactive authenticator
interactive authenticator SimpleName MethodDeclaration SingleVariableDeclaration SimpleName auth
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName server builder
public Modifier TypeDeclaration MethodDeclaration SimpleName interactive authenticator
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName auth
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName server builder
test SimpleName TypeDeclaration MethodDeclaration SimpleName interactive authenticator
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName auth
