boolean PrimitiveType SingleVariableDeclaration SimpleName immediately
future SimpleName MethodInvocation SimpleName set closed
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName do close
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName immediately
void PrimitiveType MethodDeclaration SimpleName do close
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName immediately
do close SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
do close SimpleName MethodDeclaration SingleVariableDeclaration SimpleName immediately
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName do close
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName immediately
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName do close
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName immediately
