has next SimpleName IfStatement ReturnStatement BooleanLiteral true
source SimpleName MethodInvocation SimpleName has next
source SimpleName MethodInvocation SimpleName next
source SimpleName MethodInvocation MethodInvocation SimpleName get
next SimpleName MethodInvocation MethodInvocation SimpleName get
encoder SimpleName MethodInvocation SimpleName decode
encoder SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName source
encoder SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName next
encoder SimpleName MethodInvocation MethodInvocation SimpleName get
decode SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName source
decode SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName next
decode SimpleName MethodInvocation MethodInvocation SimpleName get
next SimpleName Assignment MethodInvocation SimpleName encoder
next SimpleName Assignment MethodInvocation SimpleName decode
next SimpleName Assignment MethodInvocation MethodInvocation SimpleName get
has next SimpleName Assignment BooleanLiteral true
value format exception SimpleName SimpleType SingleVariableDeclaration SimpleName vfe
lossy SimpleName PrefixExpression IfStatement ThrowStatement SimpleName vfe
has next SimpleName IfStatement Block WhileStatement BooleanLiteral true
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType boolean
override SimpleName MarkerAnnotation MethodDeclaration SimpleName has next
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName has next
public Modifier MethodDeclaration Block IfStatement SimpleName has next
public Modifier MethodDeclaration Block WhileStatement BooleanLiteral true
boolean PrimitiveType MethodDeclaration SimpleName has next
boolean PrimitiveType MethodDeclaration Block IfStatement SimpleName has next
boolean PrimitiveType MethodDeclaration Block WhileStatement BooleanLiteral true
has next SimpleName MethodDeclaration Block IfStatement SimpleName has next
has next SimpleName MethodDeclaration Block WhileStatement BooleanLiteral true
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName has next
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName has next
