context SimpleName SimpleType SingleVariableDeclaration SimpleName cx
scriptable SimpleName SimpleType SingleVariableDeclaration SimpleName this obj
object SimpleName SimpleType ArrayType SingleVariableDeclaration SimpleName args
function SimpleName SimpleType SingleVariableDeclaration SimpleName fun obj
window wrapper SimpleName SimpleType CastExpression SimpleName this obj
ww SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName window wrapper
ww SimpleName VariableDeclarationFragment CastExpression SimpleName this obj
window wrapper SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName ww
window SimpleName VariableDeclarationFragment QualifiedName wwwindow
window SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName window
window SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment QualifiedName wwwindow
object SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName result
result SimpleName Assignment StringLiteral empty
args SimpleName ArrayAccess NumberLiteral empty
context SimpleName MethodInvocation SimpleName to type
context SimpleName MethodInvocation ArrayAccess SimpleName args
context SimpleName MethodInvocation ArrayAccess NumberLiteral empty
context SimpleName MethodInvocation TypeLiteral SimpleType SimpleName string
to type SimpleName MethodInvocation ArrayAccess SimpleName args
to type SimpleName MethodInvocation ArrayAccess NumberLiteral empty
to type SimpleName MethodInvocation TypeLiteral SimpleType SimpleName string
string SimpleName SimpleType CastExpression MethodInvocation SimpleName context
string SimpleName SimpleType CastExpression MethodInvocation SimpleName to type
message SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName string
message SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName context
message SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName to type
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName message
window SimpleName MethodInvocation SimpleName prompt
window SimpleName MethodInvocation SimpleName message
prompt SimpleName MethodInvocation SimpleName message
result SimpleName Assignment MethodInvocation SimpleName window
result SimpleName Assignment MethodInvocation SimpleName prompt
result SimpleName Assignment MethodInvocation SimpleName message
args SimpleName ArrayAccess NumberLiteral empty
context SimpleName MethodInvocation SimpleName to type
context SimpleName MethodInvocation ArrayAccess SimpleName args
context SimpleName MethodInvocation ArrayAccess NumberLiteral empty
context SimpleName MethodInvocation TypeLiteral SimpleType SimpleName string
to type SimpleName MethodInvocation ArrayAccess SimpleName args
to type SimpleName MethodInvocation ArrayAccess NumberLiteral empty
to type SimpleName MethodInvocation TypeLiteral SimpleType SimpleName string
string SimpleName SimpleType CastExpression MethodInvocation SimpleName context
string SimpleName SimpleType CastExpression MethodInvocation SimpleName to type
message SimpleName Assignment CastExpression SimpleType SimpleName string
message SimpleName Assignment CastExpression MethodInvocation SimpleName context
message SimpleName Assignment CastExpression MethodInvocation SimpleName to type
args SimpleName ArrayAccess NumberLiteral empty
context SimpleName MethodInvocation SimpleName to type
context SimpleName MethodInvocation ArrayAccess SimpleName args
context SimpleName MethodInvocation ArrayAccess NumberLiteral empty
context SimpleName MethodInvocation TypeLiteral SimpleType SimpleName string
to type SimpleName MethodInvocation ArrayAccess SimpleName args
to type SimpleName MethodInvocation ArrayAccess NumberLiteral empty
to type SimpleName MethodInvocation TypeLiteral SimpleType SimpleName string
string SimpleName SimpleType CastExpression MethodInvocation SimpleName context
string SimpleName SimpleType CastExpression MethodInvocation SimpleName to type
def val SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName string
def val SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName context
def val SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName to type
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName def val
window SimpleName MethodInvocation SimpleName prompt
window SimpleName MethodInvocation SimpleName message
window SimpleName MethodInvocation SimpleName def val
prompt SimpleName MethodInvocation SimpleName message
prompt SimpleName MethodInvocation SimpleName def val
message SimpleName MethodInvocation SimpleName def val
result SimpleName Assignment MethodInvocation SimpleName window
result SimpleName Assignment MethodInvocation SimpleName prompt
result SimpleName Assignment MethodInvocation SimpleName message
result SimpleName Assignment MethodInvocation SimpleName def val
argslength QualifiedName SwitchStatement SwitchCase NumberLiteral empty
argslength QualifiedName SwitchStatement ExpressionStatement Assignment SimpleName result
argslength QualifiedName SwitchStatement ExpressionStatement Assignment StringLiteral empty
argslength QualifiedName SwitchStatement SwitchCase NumberLiteral empty
argslength QualifiedName SwitchStatement VariableDeclarationStatement SimpleType SimpleName string
argslength QualifiedName SwitchStatement VariableDeclarationStatement VariableDeclarationFragment SimpleName message
empty NumberLiteral SwitchCase SwitchStatement SwitchCase NumberLiteral empty
context SimpleName MethodInvocation SimpleName to object
context SimpleName MethodInvocation SimpleName result
context SimpleName MethodInvocation SimpleName this obj
to object SimpleName MethodInvocation SimpleName result
to object SimpleName MethodInvocation SimpleName this obj
result SimpleName MethodInvocation SimpleName this obj
public Modifier MethodDeclaration Modifier static
public Modifier MethodDeclaration SimpleType SimpleName object
public Modifier MethodDeclaration SimpleName prompt
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName context
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName cx
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName scriptable
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName this obj
static Modifier MethodDeclaration SimpleType SimpleName object
static Modifier MethodDeclaration SimpleName prompt
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName context
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName cx
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName scriptable
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName this obj
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName args
object SimpleName SimpleType MethodDeclaration SimpleName prompt
object SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName cx
object SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName this obj
object SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName args
object SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName fun obj
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName context
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleName cx
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName scriptable
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleName this obj
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleName args
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName function
prompt SimpleName MethodDeclaration SingleVariableDeclaration SimpleName fun obj
prompt SimpleName MethodDeclaration SimpleType SimpleName java script exception
cx SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName this obj
cx SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName args
cx SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fun obj
cx SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName java script exception
this obj SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName args
this obj SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fun obj
this obj SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName java script exception
args SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fun obj
args SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName java script exception
fun obj SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName java script exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName object
public Modifier TypeDeclaration MethodDeclaration SimpleName prompt
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cx
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName this obj
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName args
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fun obj
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName java script exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName object
test SimpleName TypeDeclaration MethodDeclaration SimpleName prompt
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cx
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName this obj
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName args
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName fun obj
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName java script exception
