builder SimpleName MethodInvocation MethodInvocation SimpleName close
builder SimpleName MethodInvocation MethodInvocation SuperMethodInvocation SimpleName get inner closeable
close SimpleName MethodInvocation SuperMethodInvocation SimpleName get inner closeable
builder SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName run
close SimpleName MethodInvocation MethodInvocation SimpleName run
get inner closeable SimpleName SuperMethodInvocation MethodInvocation MethodInvocation SimpleName run
close SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName to string
close SimpleName MethodInvocation MethodInvocation ExpressionMethodReference SimpleName close immediately
run SimpleName MethodInvocation MethodInvocation SimpleName to string
run SimpleName MethodInvocation ExpressionMethodReference SimpleName close immediately
to string SimpleName MethodInvocation MethodInvocation ExpressionMethodReference SimpleName close immediately
close SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName build
run SimpleName MethodInvocation MethodInvocation SimpleName build
to string SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName build
close immediately SimpleName ExpressionMethodReference MethodInvocation MethodInvocation SimpleName build
override SimpleName MarkerAnnotation MethodDeclaration Modifier protected
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName closeable
override SimpleName MarkerAnnotation MethodDeclaration SimpleName get inner closeable
protected Modifier MethodDeclaration SimpleType SimpleName closeable
protected Modifier MethodDeclaration SimpleName get inner closeable
closeable SimpleName SimpleType MethodDeclaration SimpleName get inner closeable
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName closeable
public Modifier TypeDeclaration MethodDeclaration SimpleName get inner closeable
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName closeable
test SimpleName TypeDeclaration MethodDeclaration SimpleName get inner closeable
