suppress warnings SimpleName SingleMemberAnnotation StringLiteral syntheticaccess
get inner closeable SimpleName MethodInvocation MethodInvocation SimpleName close
get inner closeable SimpleName MethodInvocation MethodInvocation BooleanLiteral true
close SimpleName MethodInvocation BooleanLiteral true
abstract inner closeable SimpleName SuperMethodInvocation SimpleName do close immediately
future SimpleName VariableDeclarationFragment LambdaExpression SuperMethodInvocation SimpleName abstract inner closeable
future SimpleName VariableDeclarationFragment LambdaExpression SuperMethodInvocation SimpleName do close immediately
get inner closeable SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName add listener
close SimpleName MethodInvocation MethodInvocation SimpleName add listener
true BooleanLiteral MethodInvocation MethodInvocation SimpleName add listener
add listener SimpleName MethodInvocation LambdaExpression VariableDeclarationFragment SimpleName future
add listener SimpleName MethodInvocation LambdaExpression SuperMethodInvocation SimpleName abstract inner closeable
add listener SimpleName MethodInvocation LambdaExpression SuperMethodInvocation SimpleName do close immediately
override SimpleName MarkerAnnotation MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
override SimpleName MarkerAnnotation MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
override SimpleName MarkerAnnotation MethodDeclaration Modifier protected
override SimpleName MarkerAnnotation MethodDeclaration Modifier final
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName do close immediately
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration Modifier protected
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration Modifier protected
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration Modifier final
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration Modifier final
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration PrimitiveType void
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration PrimitiveType void
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration SimpleName do close immediately
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration SimpleName do close immediately
protected Modifier MethodDeclaration Modifier final
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName do close immediately
final Modifier MethodDeclaration PrimitiveType void
final Modifier MethodDeclaration SimpleName do close immediately
void PrimitiveType MethodDeclaration SimpleName do close immediately
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName do close immediately
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName do close immediately
