minor compaction reason SimpleName SimpleType SingleVariableDeclaration SimpleName minc reason
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName flush id
flush id SimpleName Assignment MethodInvocation SimpleName get flush id
no node exception SimpleName SimpleType SingleVariableDeclaration SimpleName e
e SimpleName MethodInvocation SimpleName get message
asked to initiate min c when there was no flush id StringLiteral InfixExpression MethodInvocation SimpleName get extent
asked to initiate min c when there was no flush id StringLiteral InfixExpression StringLiteral empty
asked to initiate min c when there was no flush id StringLiteral InfixExpression MethodInvocation SimpleName e
asked to initiate min c when there was no flush id StringLiteral InfixExpression MethodInvocation SimpleName get message
get extent SimpleName MethodInvocation InfixExpression StringLiteral empty
get extent SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName e
get extent SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get message
empty StringLiteral InfixExpression MethodInvocation SimpleName e
empty StringLiteral InfixExpression MethodInvocation SimpleName get message
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation InfixExpression StringLiteral asked to initiate min c when there was no flush id
log SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get extent
log SimpleName MethodInvocation InfixExpression StringLiteral empty
log SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName e
log SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get message
info SimpleName MethodInvocation InfixExpression StringLiteral asked to initiate min c when there was no flush id
info SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get extent
info SimpleName MethodInvocation InfixExpression StringLiteral empty
info SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName e
info SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get message
create minor compaction task SimpleName MethodInvocation SimpleName flush id
create minor compaction task SimpleName MethodInvocation SimpleName minc reason
flush id SimpleName MethodInvocation SimpleName minc reason
mct SimpleName VariableDeclarationFragment MethodInvocation SimpleName create minor compaction task
mct SimpleName VariableDeclarationFragment MethodInvocation SimpleName flush id
mct SimpleName VariableDeclarationFragment MethodInvocation SimpleName minc reason
minor compaction task SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName mct
mct SimpleName InfixExpression IfStatement ReturnStatement BooleanLiteral false
mct SimpleName MethodInvocation SimpleName run
long PrimitiveType VariableDeclarationStatement Block ReturnStatement BooleanLiteral true
public Modifier MethodDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SimpleName minor compact now
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName minor compaction reason
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName minc reason
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
public Modifier MethodDeclaration Block ReturnStatement BooleanLiteral true
boolean PrimitiveType MethodDeclaration SimpleName minor compact now
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName minor compaction reason
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName minc reason
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
boolean PrimitiveType MethodDeclaration Block ReturnStatement BooleanLiteral true
minor compact now SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName minor compaction reason
minor compact now SimpleName MethodDeclaration SingleVariableDeclaration SimpleName minc reason
minor compact now SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType long
minor compact now SimpleName MethodDeclaration Block ReturnStatement BooleanLiteral true
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName minor compact now
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName minc reason
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName minor compact now
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName minc reason
