orgapacheaccumulocoretracethriftt info QualifiedName SimpleType SingleVariableDeclaration SimpleName tinfo
long PrimitiveType SingleVariableDeclaration SimpleName scan id
orgapachethriftasyncasync method callback QualifiedName SimpleType SingleVariableDeclaration SimpleName result handler
continue multi scan call SimpleName SimpleType ClassInstanceCreation SimpleName tinfo
continue multi scan call SimpleName SimpleType ClassInstanceCreation SimpleName scan id
continue multi scan call SimpleName SimpleType ClassInstanceCreation SimpleName result handler
continue multi scan call SimpleName SimpleType ClassInstanceCreation SimpleName protocol factory
tinfo SimpleName ClassInstanceCreation SimpleName scan id
tinfo SimpleName ClassInstanceCreation SimpleName result handler
tinfo SimpleName ClassInstanceCreation SimpleName protocol factory
tinfo SimpleName ClassInstanceCreation SimpleName transport
scan id SimpleName ClassInstanceCreation SimpleName result handler
scan id SimpleName ClassInstanceCreation SimpleName protocol factory
scan id SimpleName ClassInstanceCreation SimpleName transport
result handler SimpleName ClassInstanceCreation SimpleName protocol factory
result handler SimpleName ClassInstanceCreation SimpleName transport
protocol factory SimpleName ClassInstanceCreation SimpleName transport
method call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName continue multi scan call
method call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName tinfo
method call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName scan id
method call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName result handler
method call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName protocol factory
method call SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName transport
continue multi scan call SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName method call
current method SimpleName FieldAccess Assignment SimpleName method call
manager SimpleName MethodInvocation SimpleName call
manager SimpleName MethodInvocation SimpleName method call
call SimpleName MethodInvocation SimpleName method call
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName continue multi scan
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType QualifiedName orgapacheaccumulocoretracethriftt info
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName tinfo
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType long
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName scan id
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType QualifiedName orgapachethriftasyncasync method callback
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName result handler
void PrimitiveType MethodDeclaration SimpleName continue multi scan
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType QualifiedName orgapacheaccumulocoretracethriftt info
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName tinfo
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType long
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName scan id
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType QualifiedName orgapachethriftasyncasync method callback
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName result handler
void PrimitiveType MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
continue multi scan SimpleName MethodDeclaration SingleVariableDeclaration SimpleType QualifiedName orgapacheaccumulocoretracethriftt info
continue multi scan SimpleName MethodDeclaration SingleVariableDeclaration SimpleName tinfo
continue multi scan SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType long
continue multi scan SimpleName MethodDeclaration SingleVariableDeclaration SimpleName scan id
continue multi scan SimpleName MethodDeclaration SingleVariableDeclaration SimpleType QualifiedName orgapachethriftasyncasync method callback
continue multi scan SimpleName MethodDeclaration SingleVariableDeclaration SimpleName result handler
continue multi scan SimpleName MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
tinfo SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
tinfo SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName scan id
tinfo SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result handler
tinfo SimpleName SingleVariableDeclaration MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
long PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result handler
scan id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result handler
long PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
scan id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
result handler SimpleName SingleVariableDeclaration MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName continue multi scan
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName tinfo
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName scan id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result handler
public Modifier TypeDeclaration MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName continue multi scan
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName tinfo
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName scan id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName result handler
test SimpleName TypeDeclaration MethodDeclaration SimpleType QualifiedName orgapachethriftt exception
