text SimpleName SimpleType SingleVariableDeclaration SimpleName text
text SimpleName MethodInvocation SimpleName to string
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName string
override SimpleName MarkerAnnotation MethodDeclaration SimpleName apply
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName text
public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName apply
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName text
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName text
string SimpleName SimpleType MethodDeclaration SimpleName apply
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName text
apply SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName text
apply SimpleName MethodDeclaration SingleVariableDeclaration SimpleName text
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName apply
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName text
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName apply
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName text
