client session SimpleName SimpleType SingleVariableDeclaration SimpleName session
string SimpleName SimpleType SingleVariableDeclaration SimpleName command
session SimpleName MethodInvocation SimpleName create exec channel
session SimpleName MethodInvocation SimpleName command
create exec channel SimpleName MethodInvocation SimpleName command
channel SimpleName VariableDeclarationFragment MethodInvocation SimpleName session
channel SimpleName VariableDeclarationFragment MethodInvocation SimpleName create exec channel
channel SimpleName VariableDeclarationFragment MethodInvocation SimpleName command
channel exec SimpleName SimpleType VariableDeclarationExpression VariableDeclarationFragment SimpleName channel
channel SimpleName MethodInvocation SimpleName set out
channel SimpleName MethodInvocation QualifiedName systemout
set out SimpleName MethodInvocation QualifiedName systemout
channel SimpleName MethodInvocation SimpleName set err
channel SimpleName MethodInvocation QualifiedName systemerr
set err SimpleName MethodInvocation QualifiedName systemerr
channel SimpleName MethodInvocation SimpleName open
channel SimpleName MethodInvocation MethodInvocation SimpleName verify
open SimpleName MethodInvocation MethodInvocation SimpleName verify
channel SimpleName MethodInvocation MethodInvocation NumberLiteral l
open SimpleName MethodInvocation MethodInvocation NumberLiteral l
channel SimpleName MethodInvocation MethodInvocation QualifiedName time unitseconds
open SimpleName MethodInvocation MethodInvocation QualifiedName time unitseconds
verify SimpleName MethodInvocation NumberLiteral l
verify SimpleName MethodInvocation QualifiedName time unitseconds
l NumberLiteral MethodInvocation QualifiedName time unitseconds
collection SimpleName SimpleType ParameterizedType SimpleType SimpleName client channel event
enum set SimpleName MethodInvocation SimpleName of
enum set SimpleName MethodInvocation QualifiedName client channel eventclosed
of SimpleName MethodInvocation QualifiedName client channel eventclosed
time unitminutes QualifiedName MethodInvocation SimpleName to millis
time unitminutes QualifiedName MethodInvocation NumberLiteral l
to millis SimpleName MethodInvocation NumberLiteral l
channel SimpleName MethodInvocation SimpleName wait for
channel SimpleName MethodInvocation MethodInvocation SimpleName enum set
channel SimpleName MethodInvocation MethodInvocation SimpleName of
channel SimpleName MethodInvocation MethodInvocation QualifiedName client channel eventclosed
channel SimpleName MethodInvocation MethodInvocation QualifiedName time unitminutes
channel SimpleName MethodInvocation MethodInvocation SimpleName to millis
channel SimpleName MethodInvocation MethodInvocation NumberLiteral l
wait for SimpleName MethodInvocation MethodInvocation SimpleName enum set
wait for SimpleName MethodInvocation MethodInvocation SimpleName of
wait for SimpleName MethodInvocation MethodInvocation QualifiedName client channel eventclosed
wait for SimpleName MethodInvocation MethodInvocation QualifiedName time unitminutes
wait for SimpleName MethodInvocation MethodInvocation SimpleName to millis
wait for SimpleName MethodInvocation MethodInvocation NumberLiteral l
enum set SimpleName MethodInvocation MethodInvocation MethodInvocation QualifiedName time unitminutes
enum set SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName to millis
enum set SimpleName MethodInvocation MethodInvocation MethodInvocation NumberLiteral l
of SimpleName MethodInvocation MethodInvocation MethodInvocation QualifiedName time unitminutes
of SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName to millis
of SimpleName MethodInvocation MethodInvocation MethodInvocation NumberLiteral l
client channel eventclosed QualifiedName MethodInvocation MethodInvocation MethodInvocation QualifiedName time unitminutes
client channel eventclosed QualifiedName MethodInvocation MethodInvocation MethodInvocation SimpleName to millis
client channel eventclosed QualifiedName MethodInvocation MethodInvocation MethodInvocation NumberLiteral l
result SimpleName VariableDeclarationFragment MethodInvocation SimpleName channel
result SimpleName VariableDeclarationFragment MethodInvocation SimpleName wait for
result SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName enum set
result SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName of
result SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation QualifiedName client channel eventclosed
result SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation QualifiedName time unitminutes
result SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName to millis
result SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation NumberLiteral l
command StringLiteral InfixExpression SimpleName command
command StringLiteral InfixExpression StringLiteral not completed on time
command StringLiteral InfixExpression SimpleName result
command SimpleName InfixExpression StringLiteral not completed on time
command SimpleName InfixExpression SimpleName result
not completed on time StringLiteral InfixExpression SimpleName result
result SimpleName MethodInvocation SimpleName contains
result SimpleName MethodInvocation QualifiedName client channel eventclosed
contains SimpleName MethodInvocation QualifiedName client channel eventclosed
assert true SimpleName MethodInvocation InfixExpression StringLiteral command
assert true SimpleName MethodInvocation InfixExpression SimpleName command
assert true SimpleName MethodInvocation InfixExpression StringLiteral not completed on time
assert true SimpleName MethodInvocation InfixExpression SimpleName result
assert true SimpleName MethodInvocation MethodInvocation SimpleName result
assert true SimpleName MethodInvocation MethodInvocation SimpleName contains
assert true SimpleName MethodInvocation MethodInvocation QualifiedName client channel eventclosed
command StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName result
command StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName contains
command StringLiteral InfixExpression MethodInvocation MethodInvocation QualifiedName client channel eventclosed
command SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName result
command SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName contains
command SimpleName InfixExpression MethodInvocation MethodInvocation QualifiedName client channel eventclosed
not completed on time StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName result
not completed on time StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName contains
not completed on time StringLiteral InfixExpression MethodInvocation MethodInvocation QualifiedName client channel eventclosed
result SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName result
result SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName contains
result SimpleName InfixExpression MethodInvocation MethodInvocation QualifiedName client channel eventclosed
channel SimpleName MethodInvocation SimpleName get exit status
status SimpleName VariableDeclarationFragment MethodInvocation SimpleName channel
status SimpleName VariableDeclarationFragment MethodInvocation SimpleName get exit status
integer SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName status
failed ( StringLiteral InfixExpression SimpleName status
failed ( StringLiteral InfixExpression StringLiteral )
failed ( StringLiteral InfixExpression SimpleName command
status SimpleName InfixExpression StringLiteral )
status SimpleName InfixExpression SimpleName command
) StringLiteral InfixExpression SimpleName command
status SimpleName MethodInvocation SimpleName int value
assert equals SimpleName MethodInvocation InfixExpression StringLiteral failed (
assert equals SimpleName MethodInvocation InfixExpression SimpleName status
assert equals SimpleName MethodInvocation InfixExpression StringLiteral )
assert equals SimpleName MethodInvocation InfixExpression SimpleName command
assert equals SimpleName MethodInvocation NumberLiteral empty
assert equals SimpleName MethodInvocation MethodInvocation SimpleName status
assert equals SimpleName MethodInvocation MethodInvocation SimpleName int value
failed ( StringLiteral InfixExpression MethodInvocation NumberLiteral empty
status SimpleName InfixExpression MethodInvocation NumberLiteral empty
) StringLiteral InfixExpression MethodInvocation NumberLiteral empty
command SimpleName InfixExpression MethodInvocation NumberLiteral empty
failed ( StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName status
failed ( StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName int value
status SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName status
status SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName int value
) StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName status
) StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName int value
command SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName status
command SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName int value
empty NumberLiteral MethodInvocation MethodInvocation SimpleName status
empty NumberLiteral MethodInvocation MethodInvocation SimpleName int value
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName execute
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName client session
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName session
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName command
private Modifier MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration SimpleName execute
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName client session
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName session
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName command
void PrimitiveType MethodDeclaration SimpleType SimpleName exception
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName client session
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleName session
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleName command
execute SimpleName MethodDeclaration SimpleType SimpleName exception
session SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName command
session SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
command SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName execute
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName session
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName command
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName execute
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName session
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName command
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
