collection SimpleName SimpleType ParameterizedType SimpleType SimpleName string
collection SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName task ids to remove
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName task ids to remove
tasks SimpleName MethodInvocation SimpleName remove all
tasks SimpleName MethodInvocation SimpleName task ids to remove
remove all SimpleName MethodInvocation SimpleName task ids to remove
synchronized Modifier MethodDeclaration PrimitiveType void
synchronized Modifier MethodDeclaration SimpleName remove
synchronized Modifier MethodDeclaration SingleVariableDeclaration SimpleName task ids to remove
void PrimitiveType MethodDeclaration SimpleName remove
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName task ids to remove
remove SimpleName MethodDeclaration SingleVariableDeclaration SimpleName task ids to remove
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier synchronized
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName remove
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName task ids to remove
test SimpleName TypeDeclaration MethodDeclaration Modifier synchronized
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName remove
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName task ids to remove
