expected SimpleName MemberValuePair TypeLiteral SimpleType SimpleName null pointer exception
test SimpleName NormalAnnotation MemberValuePair SimpleName expected
control SimpleName MethodInvocation SimpleName replay
task SimpleName MethodInvocation StringLiteral empty
aggregate SimpleName MethodInvocation MethodInvocation SimpleName task
aggregate SimpleName MethodInvocation MethodInvocation StringLiteral empty
aggregate SimpleName MethodInvocation MethodInvocation SimpleName get aggregates
task SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get aggregates
empty StringLiteral MethodInvocation MethodInvocation MethodInvocation SimpleName get aggregates
test SimpleName NormalAnnotation MethodDeclaration Modifier public
expected SimpleName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
test SimpleName NormalAnnotation MethodDeclaration PrimitiveType void
expected SimpleName MemberValuePair NormalAnnotation MethodDeclaration PrimitiveType void
test SimpleName NormalAnnotation MethodDeclaration SimpleName test task with no host
expected SimpleName MemberValuePair NormalAnnotation MethodDeclaration SimpleName test task with no host
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test task with no host
void PrimitiveType MethodDeclaration SimpleName test task with no host
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration NormalAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test task with no host
test SimpleName TypeDeclaration MethodDeclaration NormalAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test task with no host
