suppress warnings SimpleName SingleMemberAnnotation StringLiteral syntheticaccess
channel SimpleName SimpleType SingleVariableDeclaration SimpleName channel
string SimpleName SimpleType SingleVariableDeclaration SimpleName request
boolean PrimitiveType SingleVariableDeclaration SimpleName want reply
buffer SimpleName SimpleType SingleVariableDeclaration SimpleName buffer
request SimpleName MethodInvocation SimpleName equals
request SimpleName MethodInvocation StringLiteral exitsignal
equals SimpleName MethodInvocation StringLiteral exitsignal
buffer SimpleName MethodInvocation SimpleName get string
exit signal SimpleName Assignment MethodInvocation SimpleName buffer
exit signal SimpleName Assignment MethodInvocation SimpleName get string
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration MarkerAnnotation SimpleName override
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration MarkerAnnotation SimpleName override
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration Modifier public
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration Modifier public
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration SimpleType SimpleName result
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration SimpleType SimpleName result
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration SimpleName process
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration SimpleName process
suppress warnings SimpleName SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName channel
syntheticaccess StringLiteral SingleMemberAnnotation MethodDeclaration SingleVariableDeclaration SimpleName channel
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName result
override SimpleName MarkerAnnotation MethodDeclaration SimpleName process
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName channel
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName request
public Modifier MethodDeclaration SimpleType SimpleName result
public Modifier MethodDeclaration SimpleName process
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName channel
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName channel
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName request
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName want reply
result SimpleName SimpleType MethodDeclaration SimpleName process
result SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName channel
result SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName request
result SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
result SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName want reply
result SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName buffer
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName channel
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleName channel
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleName request
process SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleName want reply
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
process SimpleName MethodDeclaration SingleVariableDeclaration SimpleName buffer
process SimpleName MethodDeclaration SimpleType SimpleName exception
channel SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName request
channel SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
channel SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName want reply
channel SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
channel SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
request SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
request SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName want reply
request SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
request SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
want reply SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
want reply SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
buffer SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
public Modifier TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName result
public Modifier TypeDeclaration MethodDeclaration SimpleName process
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName request
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName want reply
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation SimpleName suppress warnings
test SimpleName TypeDeclaration MethodDeclaration SingleMemberAnnotation StringLiteral syntheticaccess
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName result
test SimpleName TypeDeclaration MethodDeclaration SimpleName process
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName request
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName want reply
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
