int PrimitiveType SingleVariableDeclaration SimpleName id
path SimpleName SimpleType SingleVariableDeclaration SimpleName file
int PrimitiveType SingleVariableDeclaration SimpleName flags
boolean PrimitiveType SingleVariableDeclaration SimpleName follow links
buffer SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName byte array buffer
buffer SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName buffer
byte PrimitiveType CastExpression SimpleName ssh fxp attrs
buffer SimpleName MethodInvocation SimpleName put byte
buffer SimpleName MethodInvocation CastExpression PrimitiveType byte
buffer SimpleName MethodInvocation CastExpression SimpleName ssh fxp attrs
put byte SimpleName MethodInvocation CastExpression PrimitiveType byte
put byte SimpleName MethodInvocation CastExpression SimpleName ssh fxp attrs
buffer SimpleName MethodInvocation SimpleName put int
buffer SimpleName MethodInvocation SimpleName id
put int SimpleName MethodInvocation SimpleName id
write attrs SimpleName MethodInvocation SimpleName buffer
write attrs SimpleName MethodInvocation SimpleName file
write attrs SimpleName MethodInvocation SimpleName flags
write attrs SimpleName MethodInvocation SimpleName follow links
buffer SimpleName MethodInvocation SimpleName file
buffer SimpleName MethodInvocation SimpleName flags
buffer SimpleName MethodInvocation SimpleName follow links
file SimpleName MethodInvocation SimpleName flags
file SimpleName MethodInvocation SimpleName follow links
flags SimpleName MethodInvocation SimpleName follow links
send SimpleName MethodInvocation SimpleName buffer
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName send attrs
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName id
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName path
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName file
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName flags
void PrimitiveType MethodDeclaration SimpleName send attrs
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName id
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName path
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName file
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName flags
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName follow links
send attrs SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
send attrs SimpleName MethodDeclaration SingleVariableDeclaration SimpleName id
send attrs SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName path
send attrs SimpleName MethodDeclaration SingleVariableDeclaration SimpleName file
send attrs SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
send attrs SimpleName MethodDeclaration SingleVariableDeclaration SimpleName flags
send attrs SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
send attrs SimpleName MethodDeclaration SingleVariableDeclaration SimpleName follow links
send attrs SimpleName MethodDeclaration SimpleType SimpleName io exception
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName flags
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName flags
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
file SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
file SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName flags
file SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
file SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
file SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
flags SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
flags SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
flags SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
boolean PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
follow links SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName send attrs
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName flags
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName send attrs
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName flags
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName follow links
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
