mockito SimpleName MethodInvocation SimpleName mock
mockito SimpleName MethodInvocation TypeLiteral SimpleType SimpleName sftp client
mock SimpleName MethodInvocation TypeLiteral SimpleType SimpleName sftp client
client SimpleName VariableDeclarationFragment MethodInvocation SimpleName mockito
client SimpleName VariableDeclarationFragment MethodInvocation SimpleName mock
sftp client SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName client
atomic boolean SimpleName SimpleType ClassInstanceCreation BooleanLiteral false
close called SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName atomic boolean
close called SimpleName VariableDeclarationFragment ClassInstanceCreation BooleanLiteral false
final Modifier VariableDeclarationStatement SimpleType SimpleName atomic boolean
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName close called
final Modifier VariableDeclarationStatement VariableDeclarationFragment ClassInstanceCreation BooleanLiteral false
atomic boolean SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName close called
answer SimpleName SimpleType ParameterizedType SimpleType SimpleName void
invocation on mock SimpleName SimpleType SingleVariableDeclaration SimpleName invocation
invocation SimpleName MethodInvocation SimpleName get arguments
args SimpleName VariableDeclarationFragment MethodInvocation SimpleName invocation
args SimpleName VariableDeclarationFragment MethodInvocation SimpleName get arguments
args SimpleName ArrayAccess NumberLiteral empty
close already called on handle StringLiteral InfixExpression ArrayAccess SimpleName args
close already called on handle StringLiteral InfixExpression ArrayAccess NumberLiteral empty
close called SimpleName MethodInvocation SimpleName get and set
close called SimpleName MethodInvocation BooleanLiteral true
get and set SimpleName MethodInvocation BooleanLiteral true
assert false SimpleName MethodInvocation InfixExpression StringLiteral close already called on handle
assert false SimpleName MethodInvocation InfixExpression ArrayAccess SimpleName args
assert false SimpleName MethodInvocation InfixExpression ArrayAccess NumberLiteral empty
assert false SimpleName MethodInvocation MethodInvocation SimpleName close called
assert false SimpleName MethodInvocation MethodInvocation SimpleName get and set
assert false SimpleName MethodInvocation MethodInvocation BooleanLiteral true
close already called on handle StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName close called
close already called on handle StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName get and set
close already called on handle StringLiteral InfixExpression MethodInvocation MethodInvocation BooleanLiteral true
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName answer
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName invocation
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName throwable
public Modifier MethodDeclaration SimpleType SimpleName void
public Modifier MethodDeclaration SimpleName answer
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName invocation on mock
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName invocation
public Modifier MethodDeclaration SimpleType SimpleName throwable
void SimpleName SimpleType MethodDeclaration SimpleName answer
void SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName invocation
void SimpleName SimpleType MethodDeclaration SimpleType SimpleName throwable
answer SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName invocation on mock
answer SimpleName MethodDeclaration SingleVariableDeclaration SimpleName invocation
answer SimpleName MethodDeclaration SimpleType SimpleName throwable
invocation SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName throwable
mockito SimpleName MethodInvocation SimpleName do answer
mockito SimpleName MethodInvocation MethodInvocation SimpleName when
do answer SimpleName MethodInvocation MethodInvocation SimpleName when
mockito SimpleName MethodInvocation MethodInvocation SimpleName client
do answer SimpleName MethodInvocation MethodInvocation SimpleName client
when SimpleName MethodInvocation SimpleName client
matchers SimpleName MethodInvocation SimpleName any
matchers SimpleName MethodInvocation TypeLiteral SimpleType SimpleName handle
any SimpleName MethodInvocation TypeLiteral SimpleType SimpleName handle
mockito SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName close
do answer SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName close
when SimpleName MethodInvocation MethodInvocation SimpleName close
client SimpleName MethodInvocation MethodInvocation SimpleName close
when SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName matchers
when SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName any
client SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName matchers
client SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName any
close SimpleName MethodInvocation MethodInvocation SimpleName matchers
close SimpleName MethodInvocation MethodInvocation SimpleName any
default closeable handle SimpleName SimpleType ClassInstanceCreation SimpleName client
default closeable handle SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName get current test name
client SimpleName ClassInstanceCreation MethodInvocation SimpleName get current test name
handle SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName default closeable handle
handle SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName client
handle SimpleName VariableDeclarationFragment ClassInstanceCreation MethodInvocation SimpleName get current test name
closeable handle SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName handle
index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName index
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment NumberLiteral empty
index SimpleName InfixExpression QualifiedName bytesize
handle SimpleName MethodInvocation SimpleName close
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName index
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression QualifiedName bytesize
int PrimitiveType VariableDeclarationExpression ForStatement PostfixExpression SimpleName index
index SimpleName InfixExpression ForStatement PostfixExpression SimpleName index
bytesize QualifiedName InfixExpression ForStatement PostfixExpression SimpleName index
close called SimpleName MethodInvocation SimpleName get
assert true SimpleName MethodInvocation StringLiteral close method not called
assert true SimpleName MethodInvocation MethodInvocation SimpleName close called
assert true SimpleName MethodInvocation MethodInvocation SimpleName get
close method not called StringLiteral MethodInvocation MethodInvocation SimpleName close called
close method not called StringLiteral MethodInvocation MethodInvocation SimpleName get
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test close idempotent
test SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName io exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test close idempotent
public Modifier MethodDeclaration SimpleType SimpleName io exception
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
void PrimitiveType MethodDeclaration SimpleName test close idempotent
void PrimitiveType MethodDeclaration SimpleType SimpleName io exception
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement Modifier final
test close idempotent SimpleName MethodDeclaration SimpleType SimpleName io exception
test close idempotent SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test close idempotent
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test close idempotent
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
