list SimpleName SimpleType ParameterizedType SimpleType SimpleName struct
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName partitions actual
struct SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName partitions actual
list SimpleName SimpleType ParameterizedType SimpleType SimpleName struct
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName partitions
struct SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName partitions
partitions actual SimpleName MethodInvocation SimpleName size
partitions SimpleName MethodInvocation SimpleName size
assert equals SimpleName MethodInvocation MethodInvocation SimpleName partitions actual
assert equals SimpleName MethodInvocation MethodInvocation SimpleName size
assert equals SimpleName MethodInvocation MethodInvocation SimpleName partitions
assert equals SimpleName MethodInvocation MethodInvocation SimpleName size
partitions actual SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions
partitions actual SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName size
size SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions
size SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName size
index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment SimpleName index
int PrimitiveType VariableDeclarationExpression VariableDeclarationFragment NumberLiteral empty
partitions SimpleName MethodInvocation SimpleName size
index SimpleName InfixExpression MethodInvocation SimpleName partitions
index SimpleName InfixExpression MethodInvocation SimpleName size
partitions actual SimpleName MethodInvocation SimpleName get
partitions actual SimpleName MethodInvocation SimpleName index
get SimpleName MethodInvocation SimpleName index
partitions SimpleName MethodInvocation SimpleName get
partitions SimpleName MethodInvocation SimpleName index
get SimpleName MethodInvocation SimpleName index
partitions actual SimpleName MethodInvocation MethodInvocation SimpleName equals contents
get SimpleName MethodInvocation MethodInvocation SimpleName equals contents
index SimpleName MethodInvocation MethodInvocation SimpleName equals contents
partitions actual SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions
partitions actual SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
partitions actual SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName index
get SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions
get SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
get SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName index
index SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions
index SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
index SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName index
equals contents SimpleName MethodInvocation MethodInvocation SimpleName partitions
equals contents SimpleName MethodInvocation MethodInvocation SimpleName get
equals contents SimpleName MethodInvocation MethodInvocation SimpleName index
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions actual
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName index
assert true SimpleName MethodInvocation MethodInvocation SimpleName equals contents
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName partitions
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName index
int PrimitiveType VariableDeclarationExpression ForStatement InfixExpression SimpleName index
int PrimitiveType VariableDeclarationExpression ForStatement PostfixExpression SimpleName index
index SimpleName InfixExpression ForStatement PostfixExpression SimpleName index
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName assert partitions
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName partitions actual
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName partitions
void PrimitiveType MethodDeclaration SimpleName assert partitions
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName partitions actual
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName partitions
assert partitions SimpleName MethodDeclaration SingleVariableDeclaration SimpleName partitions actual
assert partitions SimpleName MethodDeclaration SingleVariableDeclaration SimpleName partitions
partitions actual SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName partitions
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName assert partitions
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName partitions actual
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName partitions
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName assert partitions
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName partitions actual
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName partitions
