float PrimitiveType SingleVariableDeclaration SimpleName x
path SimpleName MethodInvocation SimpleName create dom exception
path SimpleName MethodInvocation QualifiedName dom exceptionno modification allowed err
path SimpleName MethodInvocation StringLiteral readonlypoint
create dom exception SimpleName MethodInvocation QualifiedName dom exceptionno modification allowed err
create dom exception SimpleName MethodInvocation StringLiteral readonlypoint
dom exceptionno modification allowed err QualifiedName MethodInvocation StringLiteral readonlypoint
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set x
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName x
public Modifier MethodDeclaration SimpleType SimpleName dom exception
void PrimitiveType MethodDeclaration SimpleName set x
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType float
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName x
void PrimitiveType MethodDeclaration SimpleType SimpleName dom exception
set x SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType float
set x SimpleName MethodDeclaration SingleVariableDeclaration SimpleName x
set x SimpleName MethodDeclaration SimpleType SimpleName dom exception
float PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName dom exception
x SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName dom exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set x
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName x
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName dom exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set x
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType float
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName x
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName dom exception
