mouse event SimpleName SimpleType SingleVariableDeclaration SimpleName e
e SimpleName MethodInvocation SimpleName get x
start x SimpleName Assignment MethodInvocation SimpleName e
start x SimpleName Assignment MethodInvocation SimpleName get x
e SimpleName MethodInvocation SimpleName get y
start y SimpleName Assignment MethodInvocation SimpleName e
start y SimpleName Assignment MethodInvocation SimpleName get y
system SimpleName MethodInvocation SimpleName current time millis
start time SimpleName Assignment MethodInvocation SimpleName system
start time SimpleName Assignment MethodInvocation SimpleName current time millis
check click SimpleName Assignment BooleanLiteral true
select interactor SimpleName MethodInvocation SimpleName e
interactor SimpleName MethodInvocation SimpleName mouse pressed
interactor SimpleName MethodInvocation SimpleName e
mouse pressed SimpleName MethodInvocation SimpleName e
dispatch mouse pressed SimpleName MethodInvocation SimpleName e
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName mouse pressed
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName mouse event
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName e
void PrimitiveType MethodDeclaration SimpleName mouse pressed
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName mouse event
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName e
mouse pressed SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName mouse event
mouse pressed SimpleName MethodDeclaration SingleVariableDeclaration SimpleName e
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName mouse pressed
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName e
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName mouse pressed
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName e
