algorithm parameter spec SimpleName SimpleType SingleVariableDeclaration SimpleName key spec
key spec SimpleName FieldAccess Assignment SimpleName key spec
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set key spec
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName algorithm parameter spec
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName key spec
void PrimitiveType MethodDeclaration SimpleName set key spec
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName algorithm parameter spec
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName key spec
set key spec SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName algorithm parameter spec
set key spec SimpleName MethodDeclaration SingleVariableDeclaration SimpleName key spec
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set key spec
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName key spec
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set key spec
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName key spec
