string SimpleName SimpleType SingleVariableDeclaration SimpleName entity guid
lineage direction SimpleName SimpleType SingleVariableDeclaration SimpleName direction
int PrimitiveType SingleVariableDeclaration SimpleName depth
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName lineage query
direction SimpleName MethodInvocation SimpleName equals
direction SimpleName MethodInvocation QualifiedName lineage directioninput
equals SimpleName MethodInvocation QualifiedName lineage directioninput
generate lineage query SimpleName MethodInvocation SimpleName entity guid
generate lineage query SimpleName MethodInvocation SimpleName depth
generate lineage query SimpleName MethodInvocation SimpleName process outputs edge
generate lineage query SimpleName MethodInvocation SimpleName process inputs edge
entity guid SimpleName MethodInvocation SimpleName depth
entity guid SimpleName MethodInvocation SimpleName process outputs edge
entity guid SimpleName MethodInvocation SimpleName process inputs edge
depth SimpleName MethodInvocation SimpleName process outputs edge
depth SimpleName MethodInvocation SimpleName process inputs edge
process outputs edge SimpleName MethodInvocation SimpleName process inputs edge
lineage query SimpleName Assignment MethodInvocation SimpleName generate lineage query
lineage query SimpleName Assignment MethodInvocation SimpleName entity guid
lineage query SimpleName Assignment MethodInvocation SimpleName depth
lineage query SimpleName Assignment MethodInvocation SimpleName process outputs edge
lineage query SimpleName Assignment MethodInvocation SimpleName process inputs edge
direction SimpleName MethodInvocation SimpleName equals
direction SimpleName MethodInvocation QualifiedName lineage directionoutput
equals SimpleName MethodInvocation QualifiedName lineage directionoutput
generate lineage query SimpleName MethodInvocation SimpleName entity guid
generate lineage query SimpleName MethodInvocation SimpleName depth
generate lineage query SimpleName MethodInvocation SimpleName process inputs edge
generate lineage query SimpleName MethodInvocation SimpleName process outputs edge
entity guid SimpleName MethodInvocation SimpleName depth
entity guid SimpleName MethodInvocation SimpleName process inputs edge
entity guid SimpleName MethodInvocation SimpleName process outputs edge
depth SimpleName MethodInvocation SimpleName process inputs edge
depth SimpleName MethodInvocation SimpleName process outputs edge
process inputs edge SimpleName MethodInvocation SimpleName process outputs edge
lineage query SimpleName Assignment MethodInvocation SimpleName generate lineage query
lineage query SimpleName Assignment MethodInvocation SimpleName entity guid
lineage query SimpleName Assignment MethodInvocation SimpleName depth
lineage query SimpleName Assignment MethodInvocation SimpleName process inputs edge
lineage query SimpleName Assignment MethodInvocation SimpleName process outputs edge
private Modifier MethodDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SimpleName get lineage query
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity guid
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName lineage direction
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName direction
private Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName depth
string SimpleName SimpleType MethodDeclaration SimpleName get lineage query
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName entity guid
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName direction
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
string SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName depth
get lineage query SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get lineage query SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity guid
get lineage query SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName lineage direction
get lineage query SimpleName MethodDeclaration SingleVariableDeclaration SimpleName direction
get lineage query SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
get lineage query SimpleName MethodDeclaration SingleVariableDeclaration SimpleName depth
get lineage query SimpleName MethodDeclaration Block ReturnStatement SimpleName lineage query
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName direction
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName depth
direction SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
direction SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName depth
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName get lineage query
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity guid
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName direction
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName depth
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName get lineage query
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity guid
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName direction
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName depth
