list SimpleName SimpleType ParameterizedType SimpleType SimpleName string
final Modifier SingleVariableDeclaration SimpleType SimpleName string
final Modifier SingleVariableDeclaration SimpleName entity type
string SimpleName SimpleType SingleVariableDeclaration SimpleName entity type
final Modifier SingleVariableDeclaration SimpleType SimpleName string
final Modifier SingleVariableDeclaration SimpleName unique attribute name
string SimpleName SimpleType SingleVariableDeclaration SimpleName unique attribute name
final Modifier SingleVariableDeclaration SimpleType SimpleName string
final Modifier SingleVariableDeclaration SimpleName unique attribute value
string SimpleName SimpleType SingleVariableDeclaration SimpleName unique attribute value
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral deleting entity type {} attribute name {} attribute value {}
log SimpleName MethodInvocation SimpleName entity type
log SimpleName MethodInvocation SimpleName unique attribute name
log SimpleName MethodInvocation SimpleName unique attribute value
debug SimpleName MethodInvocation StringLiteral deleting entity type {} attribute name {} attribute value {}
debug SimpleName MethodInvocation SimpleName entity type
debug SimpleName MethodInvocation SimpleName unique attribute name
debug SimpleName MethodInvocation SimpleName unique attribute value
deleting entity type {} attribute name {} attribute value {} StringLiteral MethodInvocation SimpleName entity type
deleting entity type {} attribute name {} attribute value {} StringLiteral MethodInvocation SimpleName unique attribute name
deleting entity type {} attribute name {} attribute value {} StringLiteral MethodInvocation SimpleName unique attribute value
entity type SimpleName MethodInvocation SimpleName unique attribute name
entity type SimpleName MethodInvocation SimpleName unique attribute value
unique attribute name SimpleName MethodInvocation SimpleName unique attribute value
entity resource SimpleName MethodInvocation SimpleName delete entities
entity resource SimpleName MethodInvocation SimpleName entity type
entity resource SimpleName MethodInvocation SimpleName unique attribute name
entity resource SimpleName MethodInvocation SimpleName unique attribute value
delete entities SimpleName MethodInvocation SimpleName entity type
delete entities SimpleName MethodInvocation SimpleName unique attribute name
delete entities SimpleName MethodInvocation SimpleName unique attribute value
entity type SimpleName MethodInvocation SimpleName unique attribute name
entity type SimpleName MethodInvocation SimpleName unique attribute value
unique attribute name SimpleName MethodInvocation SimpleName unique attribute value
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName response
override SimpleName MarkerAnnotation MethodDeclaration SimpleName invoke
response SimpleName SimpleType MethodDeclaration SimpleName invoke
entity operation SimpleName SimpleType ClassInstanceCreation QualifiedName apidelete entity
apidelete entity QualifiedName ClassInstanceCreation AnonymousClassDeclaration MethodDeclaration SimpleName invoke
entity operation SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName entity operation
entity operation SimpleName VariableDeclarationFragment ClassInstanceCreation QualifiedName apidelete entity
entity operation SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity operation
entity operation SimpleName MethodInvocation SimpleName run
response SimpleName VariableDeclarationFragment MethodInvocation SimpleName entity operation
response SimpleName VariableDeclarationFragment MethodInvocation SimpleName run
json object SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName response
list SimpleName SimpleType ParameterizedType SimpleType SimpleName string
extract operation SimpleName SimpleType ParameterizedType SimpleType SimpleName string
extract operation SimpleName SimpleType ParameterizedType SimpleType SimpleName string
string SimpleName SimpleType ParameterizedType SimpleType SimpleName string
extract results SimpleName MethodInvocation SimpleName response
extract results SimpleName MethodInvocation SimpleName guid
response SimpleName MethodInvocation SimpleName guid
results SimpleName VariableDeclarationFragment MethodInvocation SimpleName extract results
results SimpleName VariableDeclarationFragment MethodInvocation SimpleName response
results SimpleName VariableDeclarationFragment MethodInvocation SimpleName guid
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral delete entities returned results {}
log SimpleName MethodInvocation SimpleName results
debug SimpleName MethodInvocation StringLiteral delete entities returned results {}
debug SimpleName MethodInvocation SimpleName results
delete entities returned results {} StringLiteral MethodInvocation SimpleName results
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleName delete entity
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration Modifier final
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName entity type
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration Modifier final
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName list
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName delete entity
public Modifier MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity type
public Modifier MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
public Modifier MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
list SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName delete entity
string SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName delete entity
delete entity SimpleName MethodDeclaration SingleVariableDeclaration Modifier final
delete entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
delete entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity type
delete entity SimpleName MethodDeclaration SingleVariableDeclaration Modifier final
delete entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
delete entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
delete entity SimpleName MethodDeclaration SingleVariableDeclaration Modifier final
delete entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
delete entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
delete entity SimpleName MethodDeclaration SimpleType SimpleName atlas service exception
delete entity SimpleName MethodDeclaration Block ReturnStatement SimpleName results
final Modifier SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
final Modifier SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
entity type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
entity type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
final Modifier SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
final Modifier SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
entity type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
entity type SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
final Modifier SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
entity type SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
final Modifier SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
final Modifier SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
unique attribute name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
unique attribute name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
final Modifier SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
unique attribute name SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
final Modifier SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
unique attribute value SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleName delete entity
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleName delete entity
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName unique attribute value
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas service exception
