public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName get payload
public Modifier MethodDeclaration Block ReturnStatement SimpleName payload
string SimpleName SimpleType MethodDeclaration SimpleName get payload
get payload SimpleName MethodDeclaration Block ReturnStatement SimpleName payload
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName get payload
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName get payload
