db entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName create db entity
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName db entity
create instance SimpleName MethodInvocation SimpleName db entity
db guid SimpleName VariableDeclarationFragment MethodInvocation SimpleName create instance
db guid SimpleName VariableDeclarationFragment MethodInvocation SimpleName db entity
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName db guid
create table entity SimpleName MethodInvocation SimpleName db guid
table entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName create table entity
table entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName db guid
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName table entity
col SimpleName VariableDeclarationFragment MethodInvocation SimpleName create column entity
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName col
col SimpleName VariableDeclarationFragment MethodInvocation SimpleName create column entity
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName col
col SimpleName VariableDeclarationFragment MethodInvocation SimpleName create column entity
referenceable SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName col
immutable list SimpleName MethodInvocation SimpleName of
immutable list SimpleName MethodInvocation SimpleName col
immutable list SimpleName MethodInvocation SimpleName col
immutable list SimpleName MethodInvocation SimpleName col
of SimpleName MethodInvocation SimpleName col
of SimpleName MethodInvocation SimpleName col
of SimpleName MethodInvocation SimpleName col
col SimpleName MethodInvocation SimpleName col
col SimpleName MethodInvocation SimpleName col
col SimpleName MethodInvocation SimpleName col
table entity SimpleName MethodInvocation SimpleName set
table entity SimpleName MethodInvocation SimpleName columns attr name
table entity SimpleName MethodInvocation MethodInvocation SimpleName immutable list
table entity SimpleName MethodInvocation MethodInvocation SimpleName of
table entity SimpleName MethodInvocation MethodInvocation SimpleName col
table entity SimpleName MethodInvocation MethodInvocation SimpleName col
table entity SimpleName MethodInvocation MethodInvocation SimpleName col
set SimpleName MethodInvocation SimpleName columns attr name
set SimpleName MethodInvocation MethodInvocation SimpleName immutable list
set SimpleName MethodInvocation MethodInvocation SimpleName of
set SimpleName MethodInvocation MethodInvocation SimpleName col
set SimpleName MethodInvocation MethodInvocation SimpleName col
set SimpleName MethodInvocation MethodInvocation SimpleName col
columns attr name SimpleName MethodInvocation MethodInvocation SimpleName immutable list
columns attr name SimpleName MethodInvocation MethodInvocation SimpleName of
columns attr name SimpleName MethodInvocation MethodInvocation SimpleName col
columns attr name SimpleName MethodInvocation MethodInvocation SimpleName col
columns attr name SimpleName MethodInvocation MethodInvocation SimpleName col
create instance SimpleName MethodInvocation SimpleName table entity
table entity SimpleName MethodInvocation SimpleName get
table entity SimpleName MethodInvocation SimpleName name
get SimpleName MethodInvocation SimpleName name
repository service SimpleName MethodInvocation SimpleName get entity definition
repository service SimpleName MethodInvocation QualifiedName test utilstable type
repository service SimpleName MethodInvocation SimpleName name
repository service SimpleName MethodInvocation MethodInvocation SimpleName table entity
repository service SimpleName MethodInvocation MethodInvocation SimpleName get
repository service SimpleName MethodInvocation MethodInvocation SimpleName name
get entity definition SimpleName MethodInvocation QualifiedName test utilstable type
get entity definition SimpleName MethodInvocation SimpleName name
get entity definition SimpleName MethodInvocation MethodInvocation SimpleName table entity
get entity definition SimpleName MethodInvocation MethodInvocation SimpleName get
get entity definition SimpleName MethodInvocation MethodInvocation SimpleName name
test utilstable type QualifiedName MethodInvocation SimpleName name
test utilstable type QualifiedName MethodInvocation MethodInvocation SimpleName table entity
test utilstable type QualifiedName MethodInvocation MethodInvocation SimpleName get
test utilstable type QualifiedName MethodInvocation MethodInvocation SimpleName name
name SimpleName MethodInvocation MethodInvocation SimpleName table entity
name SimpleName MethodInvocation MethodInvocation SimpleName get
name SimpleName MethodInvocation MethodInvocation SimpleName name
table instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName repository service
table instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName get entity definition
table instance SimpleName VariableDeclarationFragment MethodInvocation QualifiedName test utilstable type
table instance SimpleName VariableDeclarationFragment MethodInvocation SimpleName name
table instance SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName table entity
table instance SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get
table instance SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName name
i typed referenceable instance SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName table instance
list SimpleName SimpleType ParameterizedType SimpleType SimpleName i referenceable instance
list SimpleName SimpleType ParameterizedType SimpleType SimpleName i referenceable instance
table instance SimpleName MethodInvocation SimpleName get
table instance SimpleName MethodInvocation SimpleName columns attr name
get SimpleName MethodInvocation SimpleName columns attr name
table columns SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName table instance
table columns SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName get
table columns SimpleName VariableDeclarationFragment CastExpression MethodInvocation SimpleName columns attr name
list SimpleName SimpleType ParameterizedType SimpleType SimpleName string
table instance SimpleName MethodInvocation SimpleName get id
table instance SimpleName MethodInvocation MethodInvocation SimpleName get id
get id SimpleName MethodInvocation MethodInvocation SimpleName get id
delete entities SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName table instance
delete entities SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
delete entities SimpleName MethodInvocation MethodInvocation SimpleName get id
deleted guids SimpleName VariableDeclarationFragment MethodInvocation SimpleName delete entities
deleted guids SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get id
table instance SimpleName MethodInvocation SimpleName get id
table instance SimpleName MethodInvocation MethodInvocation SimpleName get id
get id SimpleName MethodInvocation MethodInvocation SimpleName get id
deleted guids SimpleName MethodInvocation SimpleName contains
deleted guids SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName table instance
deleted guids SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
deleted guids SimpleName MethodInvocation MethodInvocation SimpleName get id
contains SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName table instance
contains SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
contains SimpleName MethodInvocation MethodInvocation SimpleName get id
assert SimpleName MethodInvocation SimpleName assert true
assert SimpleName MethodInvocation MethodInvocation SimpleName deleted guids
assert SimpleName MethodInvocation MethodInvocation SimpleName contains
assert SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
assert true SimpleName MethodInvocation MethodInvocation SimpleName deleted guids
assert true SimpleName MethodInvocation MethodInvocation SimpleName contains
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
i referenceable instance SimpleName SimpleType SingleVariableDeclaration SimpleName column
column SimpleName MethodInvocation SimpleName get id
column SimpleName MethodInvocation MethodInvocation SimpleName get id
get id SimpleName MethodInvocation MethodInvocation SimpleName get id
deleted guids SimpleName MethodInvocation SimpleName contains
deleted guids SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName column
deleted guids SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
deleted guids SimpleName MethodInvocation MethodInvocation SimpleName get id
contains SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName column
contains SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
contains SimpleName MethodInvocation MethodInvocation SimpleName get id
assert SimpleName MethodInvocation SimpleName assert true
assert SimpleName MethodInvocation MethodInvocation SimpleName deleted guids
assert SimpleName MethodInvocation MethodInvocation SimpleName contains
assert SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
assert true SimpleName MethodInvocation MethodInvocation SimpleName deleted guids
assert true SimpleName MethodInvocation MethodInvocation SimpleName contains
assert true SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get id
i referenceable instance SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName table columns
column SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName table columns
string SimpleName SimpleType SingleVariableDeclaration SimpleName guid
assert entity deleted SimpleName MethodInvocation SimpleName guid
string SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName deleted guids
guid SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName deleted guids
assert test delete entities SimpleName MethodInvocation SimpleName table instance
table columns SimpleName EnhancedForStatement Block EnhancedForStatement SimpleName deleted guids
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test delete entities
test SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test delete entities
public Modifier MethodDeclaration SimpleType SimpleName exception
public Modifier MethodDeclaration Block EnhancedForStatement SimpleName table columns
public Modifier MethodDeclaration Block EnhancedForStatement SimpleName deleted guids
void PrimitiveType MethodDeclaration SimpleName test delete entities
void PrimitiveType MethodDeclaration SimpleType SimpleName exception
void PrimitiveType MethodDeclaration Block EnhancedForStatement SimpleName table columns
void PrimitiveType MethodDeclaration Block EnhancedForStatement SimpleName deleted guids
test delete entities SimpleName MethodDeclaration SimpleType SimpleName exception
test delete entities SimpleName MethodDeclaration Block EnhancedForStatement SimpleName table columns
test delete entities SimpleName MethodDeclaration Block EnhancedForStatement SimpleName deleted guids
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test delete entities
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test delete entities
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
