collection SimpleName SimpleType ParameterizedType SimpleType SimpleName string
collection SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName created entity ids
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName created entity ids
created entity ids SimpleName FieldAccess MethodInvocation SimpleName add all
created entity ids SimpleName FieldAccess MethodInvocation SimpleName created entity ids
add all SimpleName MethodInvocation SimpleName created entity ids
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName record entity create
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName created entity ids
void PrimitiveType MethodDeclaration SimpleName record entity create
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName created entity ids
record entity create SimpleName MethodDeclaration SingleVariableDeclaration SimpleName created entity ids
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName record entity create
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName created entity ids
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName record entity create
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName created entity ids
