server session SimpleName SimpleType SingleVariableDeclaration SimpleName session
sftp event listener manager SimpleName SimpleType SingleVariableDeclaration SimpleName subsystem
path SimpleName SimpleType SingleVariableDeclaration SimpleName file
string SimpleName SimpleType SingleVariableDeclaration SimpleName handle
channel SimpleName SimpleType SingleVariableDeclaration SimpleName channel
channel SimpleName InstanceofExpression SimpleType SimpleName file channel
non file channel to sync StringLiteral InfixExpression SimpleName channel
stream corrupted exception SimpleName SimpleType ClassInstanceCreation InfixExpression StringLiteral non file channel to sync
stream corrupted exception SimpleName SimpleType ClassInstanceCreation InfixExpression SimpleName channel
file channel SimpleName SimpleType CastExpression SimpleName channel
channel SimpleName CastExpression ParenthesizedExpression MethodInvocation SimpleName force
channel SimpleName CastExpression ParenthesizedExpression MethodInvocation BooleanLiteral true
force SimpleName MethodInvocation BooleanLiteral true
default Modifier MethodDeclaration PrimitiveType void
default Modifier MethodDeclaration SimpleName sync file data
default Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName server session
default Modifier MethodDeclaration SingleVariableDeclaration SimpleName session
default Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName sftp event listener manager
default Modifier MethodDeclaration SingleVariableDeclaration SimpleName subsystem
default Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName path
default Modifier MethodDeclaration SingleVariableDeclaration SimpleName file
void PrimitiveType MethodDeclaration SimpleName sync file data
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName server session
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName session
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName sftp event listener manager
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName subsystem
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName path
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName file
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName handle
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName server session
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleName session
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName sftp event listener manager
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleName subsystem
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName path
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleName file
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleName handle
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName channel
sync file data SimpleName MethodDeclaration SingleVariableDeclaration SimpleName channel
session SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName subsystem
session SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
session SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
session SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
session SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
subsystem SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
subsystem SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
subsystem SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
subsystem SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
file SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
file SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
file SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
handle SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
handle SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
channel SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier default
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName sync file data
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName session
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName subsystem
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier default
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName sync file data
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName session
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName subsystem
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName channel
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
