byte PrimitiveType ArrayType SingleVariableDeclaration SimpleName data
int PrimitiveType SingleVariableDeclaration SimpleName doff
int PrimitiveType SingleVariableDeclaration SimpleName length
long PrimitiveType SingleVariableDeclaration SimpleName offset
channel SimpleName VariableDeclarationFragment MethodInvocation SimpleName get file channel
seekable byte channel SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName channel
channel SimpleName MethodInvocation SimpleName position
channel SimpleName MethodInvocation SimpleName offset
position SimpleName MethodInvocation SimpleName offset
channel SimpleName MethodInvocation SimpleName size
size SimpleName VariableDeclarationFragment MethodInvocation SimpleName channel
size SimpleName VariableDeclarationFragment MethodInvocation SimpleName size
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName size
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName channel
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName size
channel SimpleName MethodInvocation SimpleName position
cur pos SimpleName VariableDeclarationFragment MethodInvocation SimpleName channel
cur pos SimpleName VariableDeclarationFragment MethodInvocation SimpleName position
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName cur pos
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName channel
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName position
size SimpleName InfixExpression SimpleName cur pos
available SimpleName VariableDeclarationFragment InfixExpression SimpleName size
available SimpleName VariableDeclarationFragment InfixExpression SimpleName cur pos
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName available
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment InfixExpression SimpleName size
long PrimitiveType VariableDeclarationStatement VariableDeclarationFragment InfixExpression SimpleName cur pos
available SimpleName InfixExpression NumberLiteral empty
buf len SimpleName VariableDeclarationFragment SimpleName length
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName buf len
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName length
buf len SimpleName InfixExpression SimpleName available
int PrimitiveType CastExpression SimpleName available
buf len SimpleName Assignment CastExpression PrimitiveType int
buf len SimpleName Assignment CastExpression SimpleName available
byte buffer SimpleName MethodInvocation SimpleName wrap
byte buffer SimpleName MethodInvocation SimpleName data
byte buffer SimpleName MethodInvocation SimpleName doff
byte buffer SimpleName MethodInvocation SimpleName buf len
wrap SimpleName MethodInvocation SimpleName data
wrap SimpleName MethodInvocation SimpleName doff
wrap SimpleName MethodInvocation SimpleName buf len
data SimpleName MethodInvocation SimpleName doff
data SimpleName MethodInvocation SimpleName buf len
doff SimpleName MethodInvocation SimpleName buf len
channel SimpleName MethodInvocation SimpleName read
channel SimpleName MethodInvocation MethodInvocation SimpleName byte buffer
channel SimpleName MethodInvocation MethodInvocation SimpleName wrap
channel SimpleName MethodInvocation MethodInvocation SimpleName data
channel SimpleName MethodInvocation MethodInvocation SimpleName doff
channel SimpleName MethodInvocation MethodInvocation SimpleName buf len
read SimpleName MethodInvocation MethodInvocation SimpleName byte buffer
read SimpleName MethodInvocation MethodInvocation SimpleName wrap
read SimpleName MethodInvocation MethodInvocation SimpleName data
read SimpleName MethodInvocation MethodInvocation SimpleName doff
read SimpleName MethodInvocation MethodInvocation SimpleName buf len
long PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType long
long PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType long
long PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
long PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType long
long PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
long PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName read
public Modifier MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName data
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName doff
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName length
int PrimitiveType MethodDeclaration SimpleName read
int PrimitiveType MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName data
int PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName doff
int PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName length
int PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType long
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName offset
read SimpleName MethodDeclaration SingleVariableDeclaration ArrayType PrimitiveType byte
read SimpleName MethodDeclaration SingleVariableDeclaration SimpleName data
read SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
read SimpleName MethodDeclaration SingleVariableDeclaration SimpleName doff
read SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
read SimpleName MethodDeclaration SingleVariableDeclaration SimpleName length
read SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType long
read SimpleName MethodDeclaration SingleVariableDeclaration SimpleName offset
read SimpleName MethodDeclaration SimpleType SimpleName io exception
data SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
data SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName doff
data SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
data SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName length
data SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
data SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
data SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName length
doff SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
doff SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName length
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
doff SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
doff SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
doff SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
length SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
length SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
length SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
long PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
offset SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName read
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName doff
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName length
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName read
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName data
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName doff
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName length
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType long
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName offset
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
