client session SimpleName SimpleType SingleVariableDeclaration SimpleName s
string SimpleName SimpleType SingleVariableDeclaration SimpleName user
key pair SimpleName SimpleType SingleVariableDeclaration SimpleName pair
s SimpleName MethodInvocation SimpleName set username
s SimpleName MethodInvocation SimpleName user
set username SimpleName MethodInvocation SimpleName user
s SimpleName MethodInvocation SimpleName add public key identity
s SimpleName MethodInvocation SimpleName pair
add public key identity SimpleName MethodInvocation SimpleName pair
s SimpleName MethodInvocation SimpleName auth
private Modifier MethodDeclaration Modifier static
private Modifier MethodDeclaration SimpleType SimpleName auth future
private Modifier MethodDeclaration SimpleName auth public key
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName client session
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName s
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName user
static Modifier MethodDeclaration SimpleType SimpleName auth future
static Modifier MethodDeclaration SimpleName auth public key
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName client session
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName s
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName user
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName key pair
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName pair
auth future SimpleName SimpleType MethodDeclaration SimpleName auth public key
auth future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName s
auth future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName user
auth future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName pair
auth future SimpleName SimpleType MethodDeclaration SimpleType SimpleName io exception
auth public key SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName client session
auth public key SimpleName MethodDeclaration SingleVariableDeclaration SimpleName s
auth public key SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
auth public key SimpleName MethodDeclaration SingleVariableDeclaration SimpleName user
auth public key SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName key pair
auth public key SimpleName MethodDeclaration SingleVariableDeclaration SimpleName pair
auth public key SimpleName MethodDeclaration SimpleType SimpleName io exception
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user
s SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName pair
s SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
user SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName pair
user SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
pair SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName auth future
public Modifier TypeDeclaration MethodDeclaration SimpleName auth public key
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName pair
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName auth future
test SimpleName TypeDeclaration MethodDeclaration SimpleName auth public key
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName s
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName pair
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
