string SimpleName SimpleType SingleVariableDeclaration SimpleName value
. . - StringLiteral InfixExpression MethodInvocation SimpleName get current test name
. . StringLiteral ArrayInitializer InfixExpression StringLiteral . . -
. . StringLiteral ArrayInitializer InfixExpression MethodInvocation SimpleName get current test name
os utils SimpleName MethodInvocation SimpleName set java version
system SimpleName MethodInvocation SimpleName set property
system SimpleName MethodInvocation QualifiedName os utilsjava version override prop
system SimpleName MethodInvocation SimpleName value
set property SimpleName MethodInvocation QualifiedName os utilsjava version override prop
set property SimpleName MethodInvocation SimpleName value
os utilsjava version override prop QualifiedName MethodInvocation SimpleName value
value SimpleName MethodInvocation SimpleName replace
value SimpleName MethodInvocation CharacterLiteral empty
value SimpleName MethodInvocation CharacterLiteral .
replace SimpleName MethodInvocation CharacterLiteral empty
replace SimpleName MethodInvocation CharacterLiteral .
empty CharacterLiteral MethodInvocation CharacterLiteral .
expected SimpleName VariableDeclarationFragment MethodInvocation SimpleName value
expected SimpleName VariableDeclarationFragment MethodInvocation SimpleName replace
expected SimpleName VariableDeclarationFragment MethodInvocation CharacterLiteral empty
expected SimpleName VariableDeclarationFragment MethodInvocation CharacterLiteral .
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName expected
os utils SimpleName MethodInvocation SimpleName get java version
objects SimpleName MethodInvocation SimpleName to string
objects SimpleName MethodInvocation MethodInvocation SimpleName os utils
objects SimpleName MethodInvocation MethodInvocation SimpleName get java version
to string SimpleName MethodInvocation MethodInvocation SimpleName os utils
to string SimpleName MethodInvocation MethodInvocation SimpleName get java version
actual SimpleName VariableDeclarationFragment MethodInvocation SimpleName objects
actual SimpleName VariableDeclarationFragment MethodInvocation SimpleName to string
actual SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName os utils
actual SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get java version
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName actual
mismatched reported version value StringLiteral InfixExpression SimpleName actual
expected SimpleName MethodInvocation SimpleName starts with
expected SimpleName MethodInvocation SimpleName actual
starts with SimpleName MethodInvocation SimpleName actual
assert true SimpleName MethodInvocation InfixExpression StringLiteral mismatched reported version value
assert true SimpleName MethodInvocation InfixExpression SimpleName actual
assert true SimpleName MethodInvocation MethodInvocation SimpleName expected
assert true SimpleName MethodInvocation MethodInvocation SimpleName starts with
assert true SimpleName MethodInvocation MethodInvocation SimpleName actual
mismatched reported version value StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName expected
mismatched reported version value StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName starts with
mismatched reported version value StringLiteral InfixExpression MethodInvocation MethodInvocation SimpleName actual
actual SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName expected
actual SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName starts with
actual SimpleName InfixExpression MethodInvocation MethodInvocation SimpleName actual
system SimpleName MethodInvocation SimpleName clear property
system SimpleName MethodInvocation QualifiedName os utilsjava version override prop
clear property SimpleName MethodInvocation QualifiedName os utilsjava version override prop
os utils SimpleName MethodInvocation SimpleName set java version
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName test set java version by property
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName test set java version by property
void PrimitiveType MethodDeclaration SimpleName test set java version by property
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName test set java version by property
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName test set java version by property
