version info SimpleName SimpleType SingleVariableDeclaration SimpleName o
o SimpleName MethodInvocation SimpleName get major version
integer SimpleName MethodInvocation SimpleName compare
integer SimpleName MethodInvocation MethodInvocation SimpleName get major version
integer SimpleName MethodInvocation MethodInvocation SimpleName o
integer SimpleName MethodInvocation MethodInvocation SimpleName get major version
compare SimpleName MethodInvocation MethodInvocation SimpleName get major version
compare SimpleName MethodInvocation MethodInvocation SimpleName o
compare SimpleName MethodInvocation MethodInvocation SimpleName get major version
get major version SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName o
get major version SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get major version
n res SimpleName VariableDeclarationFragment MethodInvocation SimpleName integer
n res SimpleName VariableDeclarationFragment MethodInvocation SimpleName compare
n res SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get major version
n res SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName o
n res SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get major version
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName n res
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName integer
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment MethodInvocation SimpleName compare
n res SimpleName InfixExpression NumberLiteral empty
o SimpleName MethodInvocation SimpleName get minor version
integer SimpleName MethodInvocation SimpleName compare
integer SimpleName MethodInvocation MethodInvocation SimpleName get minor version
integer SimpleName MethodInvocation MethodInvocation SimpleName o
integer SimpleName MethodInvocation MethodInvocation SimpleName get minor version
compare SimpleName MethodInvocation MethodInvocation SimpleName get minor version
compare SimpleName MethodInvocation MethodInvocation SimpleName o
compare SimpleName MethodInvocation MethodInvocation SimpleName get minor version
get minor version SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName o
get minor version SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get minor version
n res SimpleName Assignment MethodInvocation SimpleName integer
n res SimpleName Assignment MethodInvocation SimpleName compare
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName get minor version
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName o
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName get minor version
n res SimpleName InfixExpression NumberLiteral empty
o SimpleName MethodInvocation SimpleName get release
integer SimpleName MethodInvocation SimpleName compare
integer SimpleName MethodInvocation MethodInvocation SimpleName get release
integer SimpleName MethodInvocation MethodInvocation SimpleName o
integer SimpleName MethodInvocation MethodInvocation SimpleName get release
compare SimpleName MethodInvocation MethodInvocation SimpleName get release
compare SimpleName MethodInvocation MethodInvocation SimpleName o
compare SimpleName MethodInvocation MethodInvocation SimpleName get release
get release SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName o
get release SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get release
n res SimpleName Assignment MethodInvocation SimpleName integer
n res SimpleName Assignment MethodInvocation SimpleName compare
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName get release
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName o
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName get release
n res SimpleName InfixExpression NumberLiteral empty
o SimpleName MethodInvocation SimpleName get build number
integer SimpleName MethodInvocation SimpleName compare
integer SimpleName MethodInvocation MethodInvocation SimpleName get build number
integer SimpleName MethodInvocation MethodInvocation SimpleName o
integer SimpleName MethodInvocation MethodInvocation SimpleName get build number
compare SimpleName MethodInvocation MethodInvocation SimpleName get build number
compare SimpleName MethodInvocation MethodInvocation SimpleName o
compare SimpleName MethodInvocation MethodInvocation SimpleName get build number
get build number SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName o
get build number SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get build number
n res SimpleName Assignment MethodInvocation SimpleName integer
n res SimpleName Assignment MethodInvocation SimpleName compare
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName get build number
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName o
n res SimpleName Assignment MethodInvocation MethodInvocation SimpleName get build number
int PrimitiveType VariableDeclarationStatement Block ReturnStatement SimpleName n res
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType int
override SimpleName MarkerAnnotation MethodDeclaration SimpleName compare to
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName compare to
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName version info
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block ReturnStatement SimpleName n res
int PrimitiveType MethodDeclaration SimpleName compare to
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName version info
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName o
int PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType MethodDeclaration Block ReturnStatement SimpleName n res
compare to SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName version info
compare to SimpleName MethodDeclaration SingleVariableDeclaration SimpleName o
compare to SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
compare to SimpleName MethodDeclaration Block ReturnStatement SimpleName n res
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName compare to
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName compare to
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
