int PrimitiveType SingleVariableDeclaration SimpleName id
string SimpleName SimpleType SingleVariableDeclaration SimpleName handle
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
map SimpleName SimpleType ParameterizedType WildcardType ?
string SimpleName SimpleType ParameterizedType WildcardType ?
map SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName attrs
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName attrs
? WildcardType ParameterizedType SingleVariableDeclaration SimpleName attrs
handles SimpleName MethodInvocation SimpleName get
handles SimpleName MethodInvocation SimpleName handle
get SimpleName MethodInvocation SimpleName handle
h SimpleName VariableDeclarationFragment MethodInvocation SimpleName handles
h SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
h SimpleName VariableDeclarationFragment MethodInvocation SimpleName handle
handle SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName h
log SimpleName MethodInvocation SimpleName is debug enabled
log SimpleName MethodInvocation SimpleName debug
log SimpleName MethodInvocation StringLiteral do fset statid ssh fxp fsetstat handle attrs
log SimpleName MethodInvocation MethodInvocation SimpleName get server session
log SimpleName MethodInvocation SimpleName id
log SimpleName MethodInvocation SimpleName handle
debug SimpleName MethodInvocation StringLiteral do fset statid ssh fxp fsetstat handle attrs
debug SimpleName MethodInvocation MethodInvocation SimpleName get server session
debug SimpleName MethodInvocation SimpleName id
debug SimpleName MethodInvocation SimpleName handle
debug SimpleName MethodInvocation SimpleName h
do fset statid ssh fxp fsetstat handle attrs StringLiteral MethodInvocation MethodInvocation SimpleName get server session
do fset statid ssh fxp fsetstat handle attrs StringLiteral MethodInvocation SimpleName id
do fset statid ssh fxp fsetstat handle attrs StringLiteral MethodInvocation SimpleName handle
do fset statid ssh fxp fsetstat handle attrs StringLiteral MethodInvocation SimpleName h
do fset statid ssh fxp fsetstat handle attrs StringLiteral MethodInvocation SimpleName attrs
get server session SimpleName MethodInvocation MethodInvocation SimpleName id
get server session SimpleName MethodInvocation MethodInvocation SimpleName handle
get server session SimpleName MethodInvocation MethodInvocation SimpleName h
get server session SimpleName MethodInvocation MethodInvocation SimpleName attrs
id SimpleName MethodInvocation SimpleName handle
id SimpleName MethodInvocation SimpleName h
id SimpleName MethodInvocation SimpleName attrs
handle SimpleName MethodInvocation SimpleName h
handle SimpleName MethodInvocation SimpleName attrs
h SimpleName MethodInvocation SimpleName attrs
validate handle SimpleName MethodInvocation SimpleName handle
validate handle SimpleName MethodInvocation SimpleName h
validate handle SimpleName MethodInvocation TypeLiteral SimpleType SimpleName handle
handle SimpleName MethodInvocation SimpleName h
handle SimpleName MethodInvocation TypeLiteral SimpleType SimpleName handle
h SimpleName MethodInvocation TypeLiteral SimpleType SimpleName handle
validate handle SimpleName MethodInvocation MethodInvocation SimpleName get file
handle SimpleName MethodInvocation MethodInvocation SimpleName get file
h SimpleName MethodInvocation MethodInvocation SimpleName get file
do set attributes SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName validate handle
do set attributes SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName handle
do set attributes SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName h
do set attributes SimpleName MethodInvocation MethodInvocation SimpleName get file
do set attributes SimpleName MethodInvocation SimpleName attrs
validate handle SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName attrs
handle SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName attrs
h SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName attrs
get file SimpleName MethodInvocation MethodInvocation SimpleName attrs
protected Modifier MethodDeclaration PrimitiveType void
protected Modifier MethodDeclaration SimpleName do f set stat
protected Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName id
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName handle
protected Modifier MethodDeclaration SingleVariableDeclaration ParameterizedType WildcardType ?
protected Modifier MethodDeclaration SingleVariableDeclaration SimpleName attrs
void PrimitiveType MethodDeclaration SimpleName do f set stat
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType int
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName id
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName handle
void PrimitiveType MethodDeclaration SingleVariableDeclaration ParameterizedType WildcardType ?
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName attrs
void PrimitiveType MethodDeclaration SimpleType SimpleName io exception
do f set stat SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
do f set stat SimpleName MethodDeclaration SingleVariableDeclaration SimpleName id
do f set stat SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
do f set stat SimpleName MethodDeclaration SingleVariableDeclaration SimpleName handle
do f set stat SimpleName MethodDeclaration SingleVariableDeclaration ParameterizedType WildcardType ?
do f set stat SimpleName MethodDeclaration SingleVariableDeclaration SimpleName attrs
do f set stat SimpleName MethodDeclaration SimpleType SimpleName io exception
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attrs
id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attrs
int PrimitiveType SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
handle SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attrs
handle SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
attrs SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName io exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier protected
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName do f set stat
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attrs
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
test SimpleName TypeDeclaration MethodDeclaration Modifier protected
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName do f set stat
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName handle
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName attrs
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName io exception
