string SimpleName SimpleType SingleVariableDeclaration SimpleName file name
system SimpleName MethodInvocation SimpleName get property
system SimpleName MethodInvocation SimpleName atlas configuration directory property
get property SimpleName MethodInvocation SimpleName atlas configuration directory property
conf location SimpleName VariableDeclarationFragment MethodInvocation SimpleName system
conf location SimpleName VariableDeclarationFragment MethodInvocation SimpleName get property
conf location SimpleName VariableDeclarationFragment MethodInvocation SimpleName atlas configuration directory property
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName conf location
url SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName url
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation StringLiteral looking for {} in classpath
log SimpleName MethodInvocation SimpleName file name
info SimpleName MethodInvocation StringLiteral looking for {} in classpath
info SimpleName MethodInvocation SimpleName file name
looking for {} in classpath StringLiteral MethodInvocation SimpleName file name
application properties SimpleName SimpleType TypeLiteral MethodInvocation SimpleName get class loader
get class loader SimpleName MethodInvocation MethodInvocation SimpleName get resource
get class loader SimpleName MethodInvocation MethodInvocation SimpleName file name
get resource SimpleName MethodInvocation SimpleName file name
url SimpleName Assignment MethodInvocation MethodInvocation SimpleName get class loader
url SimpleName Assignment MethodInvocation SimpleName get resource
url SimpleName Assignment MethodInvocation SimpleName file name
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation StringLiteral looking for /{} in classpath
log SimpleName MethodInvocation SimpleName file name
info SimpleName MethodInvocation StringLiteral looking for /{} in classpath
info SimpleName MethodInvocation SimpleName file name
looking for /{} in classpath StringLiteral MethodInvocation SimpleName file name
application properties SimpleName SimpleType TypeLiteral MethodInvocation SimpleName get class loader
/ StringLiteral InfixExpression SimpleName file name
get class loader SimpleName MethodInvocation MethodInvocation SimpleName get resource
get class loader SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral /
get class loader SimpleName MethodInvocation MethodInvocation InfixExpression SimpleName file name
get resource SimpleName MethodInvocation InfixExpression StringLiteral /
get resource SimpleName MethodInvocation InfixExpression SimpleName file name
url SimpleName Assignment MethodInvocation MethodInvocation SimpleName get class loader
url SimpleName Assignment MethodInvocation SimpleName get resource
url SimpleName Assignment MethodInvocation InfixExpression StringLiteral /
url SimpleName Assignment MethodInvocation InfixExpression SimpleName file name
file SimpleName SimpleType ClassInstanceCreation SimpleName conf location
file SimpleName SimpleType ClassInstanceCreation SimpleName file name
conf location SimpleName ClassInstanceCreation SimpleName file name
file SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName to uri
conf location SimpleName ClassInstanceCreation MethodInvocation SimpleName to uri
file name SimpleName ClassInstanceCreation MethodInvocation SimpleName to uri
conf location SimpleName ClassInstanceCreation MethodInvocation MethodInvocation SimpleName to url
file name SimpleName ClassInstanceCreation MethodInvocation MethodInvocation SimpleName to url
to uri SimpleName MethodInvocation MethodInvocation SimpleName to url
url SimpleName Assignment MethodInvocation MethodInvocation SimpleName to uri
url SimpleName Assignment MethodInvocation SimpleName to url
log SimpleName MethodInvocation SimpleName info
log SimpleName MethodInvocation StringLiteral loading {} from {}
log SimpleName MethodInvocation SimpleName file name
log SimpleName MethodInvocation SimpleName url
info SimpleName MethodInvocation StringLiteral loading {} from {}
info SimpleName MethodInvocation SimpleName file name
info SimpleName MethodInvocation SimpleName url
loading {} from {} StringLiteral MethodInvocation SimpleName file name
loading {} from {} StringLiteral MethodInvocation SimpleName url
file name SimpleName MethodInvocation SimpleName url
application properties SimpleName SimpleType ClassInstanceCreation SimpleName url
app properties SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName application properties
app properties SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName url
application properties SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName app properties
app properties SimpleName MethodInvocation SimpleName set defaults
app properties SimpleName MethodInvocation SimpleName interpolated configuration
configuration SimpleName VariableDeclarationFragment MethodInvocation SimpleName app properties
configuration SimpleName VariableDeclarationFragment MethodInvocation SimpleName interpolated configuration
configuration SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName configuration
log configuration SimpleName MethodInvocation SimpleName configuration
exception SimpleName SimpleType SingleVariableDeclaration SimpleName e
atlas exception SimpleName SimpleType ClassInstanceCreation StringLiteral failed to load application properties
atlas exception SimpleName SimpleType ClassInstanceCreation SimpleName e
failed to load application properties StringLiteral ClassInstanceCreation SimpleName e
public Modifier MethodDeclaration Modifier static
public Modifier MethodDeclaration SimpleType SimpleName configuration
public Modifier MethodDeclaration SimpleName get
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName file name
public Modifier MethodDeclaration SimpleType SimpleName atlas exception
static Modifier MethodDeclaration SimpleType SimpleName configuration
static Modifier MethodDeclaration SimpleName get
static Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName file name
static Modifier MethodDeclaration SimpleType SimpleName atlas exception
configuration SimpleName SimpleType MethodDeclaration SimpleName get
configuration SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName file name
configuration SimpleName SimpleType MethodDeclaration SimpleType SimpleName atlas exception
get SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get SimpleName MethodDeclaration SingleVariableDeclaration SimpleName file name
get SimpleName MethodDeclaration SimpleType SimpleName atlas exception
file name SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName configuration
public Modifier TypeDeclaration MethodDeclaration SimpleName get
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file name
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName configuration
test SimpleName TypeDeclaration MethodDeclaration SimpleName get
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName file name
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
