list SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas classification
atlas vertex SimpleName SimpleType SingleVariableDeclaration SimpleName instance vertex
string SimpleName SimpleType SingleVariableDeclaration SimpleName classification name filter
list SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas classification
list SimpleName SimpleType ParameterizedType SimpleType SimpleName string
get propagated trait names SimpleName MethodInvocation SimpleName instance vertex
classification names SimpleName VariableDeclarationFragment MethodInvocation SimpleName get propagated trait names
classification names SimpleName VariableDeclarationFragment MethodInvocation SimpleName instance vertex
collection utils SimpleName MethodInvocation SimpleName is not empty
collection utils SimpleName MethodInvocation SimpleName classification names
is not empty SimpleName MethodInvocation SimpleName classification names
string utils SimpleName MethodInvocation SimpleName is not empty
string utils SimpleName MethodInvocation SimpleName classification name filter
is not empty SimpleName MethodInvocation SimpleName classification name filter
classification names SimpleName MethodInvocation SimpleName contains
classification names SimpleName MethodInvocation SimpleName classification name filter
contains SimpleName MethodInvocation SimpleName classification name filter
get all propagated classifications SimpleName MethodInvocation SimpleName instance vertex
get all propagated classifications SimpleName MethodInvocation SimpleName classification name filter
instance vertex SimpleName MethodInvocation SimpleName classification name filter
ret SimpleName MethodInvocation SimpleName add all
ret SimpleName MethodInvocation MethodInvocation SimpleName get all propagated classifications
ret SimpleName MethodInvocation MethodInvocation SimpleName instance vertex
ret SimpleName MethodInvocation MethodInvocation SimpleName classification name filter
add all SimpleName MethodInvocation MethodInvocation SimpleName get all propagated classifications
add all SimpleName MethodInvocation MethodInvocation SimpleName instance vertex
add all SimpleName MethodInvocation MethodInvocation SimpleName classification name filter
string SimpleName SimpleType SingleVariableDeclaration SimpleName classification name
hash set SimpleName SimpleType ParameterizedType ClassInstanceCreation SimpleName classification names
get all propagated classifications SimpleName MethodInvocation SimpleName instance vertex
get all propagated classifications SimpleName MethodInvocation SimpleName classification name
instance vertex SimpleName MethodInvocation SimpleName classification name
ret SimpleName MethodInvocation SimpleName add all
ret SimpleName MethodInvocation MethodInvocation SimpleName get all propagated classifications
ret SimpleName MethodInvocation MethodInvocation SimpleName instance vertex
ret SimpleName MethodInvocation MethodInvocation SimpleName classification name
add all SimpleName MethodInvocation MethodInvocation SimpleName get all propagated classifications
add all SimpleName MethodInvocation MethodInvocation SimpleName instance vertex
add all SimpleName MethodInvocation MethodInvocation SimpleName classification name
classification name SimpleName SingleVariableDeclaration EnhancedForStatement ClassInstanceCreation SimpleName classification names
ret SimpleName MethodInvocation SimpleName is empty
string utils SimpleName MethodInvocation SimpleName is not empty
string utils SimpleName MethodInvocation SimpleName classification name filter
is not empty SimpleName MethodInvocation SimpleName classification name filter
ret SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName string utils
ret SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName is not empty
ret SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification name filter
is empty SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName string utils
is empty SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName is not empty
is empty SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification name filter
atlas base exception SimpleName SimpleType ClassInstanceCreation QualifiedName atlas error codeclassification not found
atlas base exception SimpleName SimpleType ClassInstanceCreation SimpleName classification name filter
atlas error codeclassification not found QualifiedName ClassInstanceCreation SimpleName classification name filter
private Modifier MethodDeclaration ParameterizedType SimpleType SimpleName list
private Modifier MethodDeclaration ParameterizedType SimpleType SimpleName atlas classification
private Modifier MethodDeclaration SimpleName get propagated classifications
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName classification name filter
private Modifier MethodDeclaration SimpleType SimpleName atlas base exception
list SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get propagated classifications
atlas classification SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get propagated classifications
get propagated classifications SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
get propagated classifications SimpleName MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
get propagated classifications SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
get propagated classifications SimpleName MethodDeclaration SingleVariableDeclaration SimpleName classification name filter
get propagated classifications SimpleName MethodDeclaration SimpleType SimpleName atlas base exception
get propagated classifications SimpleName MethodDeclaration Block ReturnStatement SimpleName ret
instance vertex SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classification name filter
instance vertex SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
classification name filter SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleName get propagated classifications
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classification name filter
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleName get propagated classifications
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classification name filter
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
