iterator environment SimpleName SimpleType SingleVariableDeclaration SimpleName env
reg ex iterator SimpleName SimpleType ClassInstanceCreation SimpleName env
public Modifier MethodDeclaration SimpleType SimpleName reg ex iterator
public Modifier MethodDeclaration SimpleName deep copy
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName iterator environment
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName env
reg ex iterator SimpleName SimpleType MethodDeclaration SimpleName deep copy
reg ex iterator SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName env
deep copy SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName iterator environment
deep copy SimpleName MethodDeclaration SingleVariableDeclaration SimpleName env
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName reg ex iterator
public Modifier TypeDeclaration MethodDeclaration SimpleName deep copy
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName env
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName reg ex iterator
test SimpleName TypeDeclaration MethodDeclaration SimpleName deep copy
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName env
