string SimpleName SimpleType SingleVariableDeclaration SimpleName full command
command line SimpleName SimpleType SingleVariableDeclaration SimpleName cl
shell SimpleName SimpleType SingleVariableDeclaration SimpleName shell state
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName table name
table opt SimpleName MethodInvocation SimpleName get opt
cl SimpleName MethodInvocation SimpleName has option
cl SimpleName MethodInvocation MethodInvocation SimpleName table opt
cl SimpleName MethodInvocation MethodInvocation SimpleName get opt
has option SimpleName MethodInvocation MethodInvocation SimpleName table opt
has option SimpleName MethodInvocation MethodInvocation SimpleName get opt
table opt SimpleName MethodInvocation SimpleName get opt
cl SimpleName MethodInvocation SimpleName get option value
cl SimpleName MethodInvocation MethodInvocation SimpleName table opt
cl SimpleName MethodInvocation MethodInvocation SimpleName get opt
get option value SimpleName MethodInvocation MethodInvocation SimpleName table opt
get option value SimpleName MethodInvocation MethodInvocation SimpleName get opt
table name SimpleName Assignment MethodInvocation SimpleName cl
table name SimpleName Assignment MethodInvocation SimpleName get option value
table name SimpleName Assignment MethodInvocation MethodInvocation SimpleName table opt
table name SimpleName Assignment MethodInvocation MethodInvocation SimpleName get opt
shell state SimpleName MethodInvocation SimpleName get connector
shell state SimpleName MethodInvocation MethodInvocation SimpleName table operations
get connector SimpleName MethodInvocation MethodInvocation SimpleName table operations
shell state SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName exists
get connector SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName exists
table operations SimpleName MethodInvocation MethodInvocation SimpleName exists
shell state SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName table name
get connector SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName table name
table operations SimpleName MethodInvocation MethodInvocation SimpleName table name
exists SimpleName MethodInvocation SimpleName table name
table not found exception SimpleName SimpleType ClassInstanceCreation SimpleName table name
shell state SimpleName MethodInvocation SimpleName check table state
shell state SimpleName MethodInvocation SimpleName get table name
table name SimpleName Assignment MethodInvocation SimpleName shell state
table name SimpleName Assignment MethodInvocation SimpleName get table name
all opt SimpleName MethodInvocation SimpleName get opt
cl SimpleName MethodInvocation SimpleName has option
cl SimpleName MethodInvocation MethodInvocation SimpleName all opt
cl SimpleName MethodInvocation MethodInvocation SimpleName get opt
has option SimpleName MethodInvocation MethodInvocation SimpleName all opt
has option SimpleName MethodInvocation MethodInvocation SimpleName get opt
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
string SimpleName SimpleType ParameterizedType SimpleType SimpleName string
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
shell statescan iterator options QualifiedName MethodInvocation SimpleName remove
shell statescan iterator options QualifiedName MethodInvocation SimpleName table name
remove SimpleName MethodInvocation SimpleName table name
table iterators SimpleName VariableDeclarationFragment MethodInvocation QualifiedName shell statescan iterator options
table iterators SimpleName VariableDeclarationFragment MethodInvocation SimpleName remove
table iterators SimpleName VariableDeclarationFragment MethodInvocation SimpleName table name
no scan iterators set on table StringLiteral InfixExpression SimpleName table name
shelllog QualifiedName MethodInvocation SimpleName info
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral no scan iterators set on table
shelllog QualifiedName MethodInvocation InfixExpression SimpleName table name
info SimpleName MethodInvocation InfixExpression StringLiteral no scan iterators set on table
info SimpleName MethodInvocation InfixExpression SimpleName table name
table iterators SimpleName MethodInvocation SimpleName key set
removed the following scan iterators from table StringLiteral InfixExpression SimpleName table name
removed the following scan iterators from table StringLiteral InfixExpression StringLiteral :
removed the following scan iterators from table StringLiteral InfixExpression MethodInvocation SimpleName table iterators
removed the following scan iterators from table StringLiteral InfixExpression MethodInvocation SimpleName key set
table name SimpleName InfixExpression StringLiteral :
table name SimpleName InfixExpression MethodInvocation SimpleName table iterators
table name SimpleName InfixExpression MethodInvocation SimpleName key set
: StringLiteral InfixExpression MethodInvocation SimpleName table iterators
: StringLiteral InfixExpression MethodInvocation SimpleName key set
shelllog QualifiedName MethodInvocation SimpleName info
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral removed the following scan iterators from table
shelllog QualifiedName MethodInvocation InfixExpression SimpleName table name
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral :
shelllog QualifiedName MethodInvocation InfixExpression MethodInvocation SimpleName table iterators
shelllog QualifiedName MethodInvocation InfixExpression MethodInvocation SimpleName key set
info SimpleName MethodInvocation InfixExpression StringLiteral removed the following scan iterators from table
info SimpleName MethodInvocation InfixExpression SimpleName table name
info SimpleName MethodInvocation InfixExpression StringLiteral :
info SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName table iterators
info SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName key set
name opt SimpleName MethodInvocation SimpleName get opt
cl SimpleName MethodInvocation SimpleName has option
cl SimpleName MethodInvocation MethodInvocation SimpleName name opt
cl SimpleName MethodInvocation MethodInvocation SimpleName get opt
has option SimpleName MethodInvocation MethodInvocation SimpleName name opt
has option SimpleName MethodInvocation MethodInvocation SimpleName get opt
name opt SimpleName MethodInvocation SimpleName get opt
cl SimpleName MethodInvocation SimpleName get option value
cl SimpleName MethodInvocation MethodInvocation SimpleName name opt
cl SimpleName MethodInvocation MethodInvocation SimpleName get opt
get option value SimpleName MethodInvocation MethodInvocation SimpleName name opt
get option value SimpleName MethodInvocation MethodInvocation SimpleName get opt
name SimpleName VariableDeclarationFragment MethodInvocation SimpleName cl
name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get option value
name SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName name opt
name SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get opt
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName name
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
string SimpleName SimpleType ParameterizedType SimpleType SimpleName string
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
shell statescan iterator options QualifiedName MethodInvocation SimpleName get
shell statescan iterator options QualifiedName MethodInvocation SimpleName table name
get SimpleName MethodInvocation SimpleName table name
table iterators SimpleName VariableDeclarationFragment MethodInvocation QualifiedName shell statescan iterator options
table iterators SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
table iterators SimpleName VariableDeclarationFragment MethodInvocation SimpleName table name
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
map SimpleName SimpleType ParameterizedType SimpleType SimpleName string
string SimpleName SimpleType ParameterizedType SimpleType SimpleName string
table iterators SimpleName MethodInvocation SimpleName remove
table iterators SimpleName MethodInvocation SimpleName name
remove SimpleName MethodInvocation SimpleName name
options SimpleName VariableDeclarationFragment MethodInvocation SimpleName table iterators
options SimpleName VariableDeclarationFragment MethodInvocation SimpleName remove
options SimpleName VariableDeclarationFragment MethodInvocation SimpleName name
no iterator named StringLiteral InfixExpression SimpleName name
no iterator named StringLiteral InfixExpression StringLiteral found for table
no iterator named StringLiteral InfixExpression SimpleName table name
name SimpleName InfixExpression StringLiteral found for table
name SimpleName InfixExpression SimpleName table name
found for table StringLiteral InfixExpression SimpleName table name
shelllog QualifiedName MethodInvocation SimpleName info
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral no iterator named
shelllog QualifiedName MethodInvocation InfixExpression SimpleName name
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral found for table
shelllog QualifiedName MethodInvocation InfixExpression SimpleName table name
info SimpleName MethodInvocation InfixExpression StringLiteral no iterator named
info SimpleName MethodInvocation InfixExpression SimpleName name
info SimpleName MethodInvocation InfixExpression StringLiteral found for table
info SimpleName MethodInvocation InfixExpression SimpleName table name
removed scan iterator StringLiteral InfixExpression SimpleName name
removed scan iterator StringLiteral InfixExpression StringLiteral from table
removed scan iterator StringLiteral InfixExpression SimpleName table name
name SimpleName InfixExpression StringLiteral from table
name SimpleName InfixExpression SimpleName table name
from table StringLiteral InfixExpression SimpleName table name
shelllog QualifiedName MethodInvocation SimpleName info
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral removed scan iterator
shelllog QualifiedName MethodInvocation InfixExpression SimpleName name
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral from table
shelllog QualifiedName MethodInvocation InfixExpression SimpleName table name
info SimpleName MethodInvocation InfixExpression StringLiteral removed scan iterator
info SimpleName MethodInvocation InfixExpression SimpleName name
info SimpleName MethodInvocation InfixExpression StringLiteral from table
info SimpleName MethodInvocation InfixExpression SimpleName table name
no iterator named StringLiteral InfixExpression SimpleName name
no iterator named StringLiteral InfixExpression StringLiteral found for table
no iterator named StringLiteral InfixExpression SimpleName table name
name SimpleName InfixExpression StringLiteral found for table
name SimpleName InfixExpression SimpleName table name
found for table StringLiteral InfixExpression SimpleName table name
shelllog QualifiedName MethodInvocation SimpleName info
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral no iterator named
shelllog QualifiedName MethodInvocation InfixExpression SimpleName name
shelllog QualifiedName MethodInvocation InfixExpression StringLiteral found for table
shelllog QualifiedName MethodInvocation InfixExpression SimpleName table name
info SimpleName MethodInvocation InfixExpression StringLiteral no iterator named
info SimpleName MethodInvocation InfixExpression SimpleName name
info SimpleName MethodInvocation InfixExpression StringLiteral found for table
info SimpleName MethodInvocation InfixExpression SimpleName table name
name opt SimpleName MethodInvocation SimpleName get arg name
all opt SimpleName MethodInvocation SimpleName get arg name
must specify one of StringLiteral InfixExpression MethodInvocation SimpleName name opt
must specify one of StringLiteral InfixExpression MethodInvocation SimpleName get arg name
must specify one of StringLiteral InfixExpression StringLiteral or
must specify one of StringLiteral InfixExpression MethodInvocation SimpleName all opt
must specify one of StringLiteral InfixExpression MethodInvocation SimpleName get arg name
name opt SimpleName MethodInvocation InfixExpression StringLiteral or
get arg name SimpleName MethodInvocation InfixExpression StringLiteral or
name opt SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName all opt
name opt SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get arg name
get arg name SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName all opt
get arg name SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get arg name
or StringLiteral InfixExpression MethodInvocation SimpleName all opt
or StringLiteral InfixExpression MethodInvocation SimpleName get arg name
illegal argument exception SimpleName SimpleType ClassInstanceCreation InfixExpression StringLiteral must specify one of
illegal argument exception SimpleName SimpleType ClassInstanceCreation InfixExpression StringLiteral or
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType int
override SimpleName MarkerAnnotation MethodDeclaration SimpleName execute
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName full command
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName cl
public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName execute
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName full command
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName command line
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName cl
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName shell
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName shell state
int PrimitiveType MethodDeclaration SimpleName execute
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName full command
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName command line
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName cl
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName shell
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName shell state
int PrimitiveType MethodDeclaration SimpleType SimpleName exception
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleName full command
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName command line
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleName cl
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName shell
execute SimpleName MethodDeclaration SingleVariableDeclaration SimpleName shell state
execute SimpleName MethodDeclaration SimpleType SimpleName exception
execute SimpleName MethodDeclaration Block ReturnStatement NumberLiteral empty
full command SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cl
full command SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName shell state
full command SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
cl SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName shell state
cl SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
shell state SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName execute
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName full command
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cl
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName shell state
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName execute
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName full command
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cl
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName shell state
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName exception
