logger user SimpleName SimpleType SingleVariableDeclaration SimpleName o
o SimpleName InstanceofExpression SimpleType SimpleName t server uses loggers
t server uses loggers SimpleName SimpleType CastExpression SimpleName o
o SimpleName CastExpression ParenthesizedExpression FieldAccess SimpleName instance
instance SimpleName MethodInvocation SimpleName compare to
instance SimpleName MethodInvocation FieldAccess SimpleName instance
compare to SimpleName MethodInvocation FieldAccess SimpleName instance
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType int
override SimpleName MarkerAnnotation MethodDeclaration SimpleName compare to
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName compare to
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName logger user
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName o
int PrimitiveType MethodDeclaration SimpleName compare to
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName logger user
int PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName o
compare to SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName logger user
compare to SimpleName MethodDeclaration SingleVariableDeclaration SimpleName o
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName compare to
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName compare to
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName o
