public Modifier MethodDeclaration PrimitiveType long
public Modifier MethodDeclaration SimpleName total size
public Modifier MethodDeclaration Block ReturnStatement SimpleName total size
long PrimitiveType MethodDeclaration SimpleName total size
long PrimitiveType MethodDeclaration Block ReturnStatement SimpleName total size
total size SimpleName MethodDeclaration Block ReturnStatement SimpleName total size
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType long
public Modifier TypeDeclaration MethodDeclaration SimpleName total size
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType long
test SimpleName TypeDeclaration MethodDeclaration SimpleName total size
