set SimpleName SimpleType ParameterizedType SimpleType SimpleName string
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName set
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName get command names
public Modifier MethodDeclaration Block ReturnStatement SimpleName command
set SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get command names
string SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get command names
get command names SimpleName MethodDeclaration Block ReturnStatement SimpleName command
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleName get command names
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleName get command names
