string SimpleName SimpleType ArrayType SingleVariableDeclaration SimpleName args
just security SimpleName VariableDeclarationFragment BooleanLiteral false
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName just security
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment BooleanLiteral false
string SimpleName SimpleType SingleVariableDeclaration SimpleName arg
arg SimpleName MethodInvocation SimpleName equals
arg SimpleName MethodInvocation StringLiteral resetsecurity
equals SimpleName MethodInvocation StringLiteral resetsecurity
just security SimpleName Assignment BooleanLiteral true
arg SimpleName MethodInvocation SimpleName equals
arg SimpleName MethodInvocation StringLiteral clearinstancename
equals SimpleName MethodInvocation StringLiteral clearinstancename
clear instance name SimpleName Assignment BooleanLiteral true
e SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName runtime exception
runtime exception SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName e
bad argument StringLiteral InfixExpression SimpleName arg
log SimpleName MethodInvocation SimpleName fatal
log SimpleName MethodInvocation InfixExpression StringLiteral bad argument
log SimpleName MethodInvocation InfixExpression SimpleName arg
log SimpleName MethodInvocation SimpleName e
fatal SimpleName MethodInvocation InfixExpression StringLiteral bad argument
fatal SimpleName MethodInvocation InfixExpression SimpleName arg
fatal SimpleName MethodInvocation SimpleName e
bad argument StringLiteral InfixExpression MethodInvocation SimpleName e
arg SimpleName InfixExpression MethodInvocation SimpleName e
string SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName args
arg SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName args
cached configuration SimpleName MethodInvocation SimpleName get instance
conf SimpleName VariableDeclarationFragment MethodInvocation SimpleName cached configuration
conf SimpleName VariableDeclarationFragment MethodInvocation SimpleName get instance
configuration SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName conf
server configuration SimpleName MethodInvocation SimpleName get site configuration
file util SimpleName MethodInvocation SimpleName get file system
file util SimpleName MethodInvocation SimpleName conf
file util SimpleName MethodInvocation MethodInvocation SimpleName server configuration
file util SimpleName MethodInvocation MethodInvocation SimpleName get site configuration
get file system SimpleName MethodInvocation SimpleName conf
get file system SimpleName MethodInvocation MethodInvocation SimpleName server configuration
get file system SimpleName MethodInvocation MethodInvocation SimpleName get site configuration
conf SimpleName MethodInvocation MethodInvocation SimpleName server configuration
conf SimpleName MethodInvocation MethodInvocation SimpleName get site configuration
fs SimpleName VariableDeclarationFragment MethodInvocation SimpleName file util
fs SimpleName VariableDeclarationFragment MethodInvocation SimpleName get file system
fs SimpleName VariableDeclarationFragment MethodInvocation SimpleName conf
fs SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName server configuration
fs SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get site configuration
file system SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName fs
is initialized SimpleName MethodInvocation SimpleName fs
hdfs zoo instance SimpleName MethodInvocation SimpleName get instance
hdfs zoo instance SimpleName MethodInvocation MethodInvocation SimpleName get instance id
get instance SimpleName MethodInvocation MethodInvocation SimpleName get instance id
init security SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName hdfs zoo instance
init security SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get instance
init security SimpleName MethodInvocation MethodInvocation SimpleName get instance id
init security SimpleName MethodInvocation MethodInvocation SimpleName get root password
get instance id SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get root password
log SimpleName MethodInvocation SimpleName fatal
log SimpleName MethodInvocation StringLiteral attempted to reset security on accumulo before it was initialized
fatal SimpleName MethodInvocation StringLiteral attempted to reset security on accumulo before it was initialized
do init SimpleName MethodInvocation SimpleName conf
do init SimpleName MethodInvocation SimpleName fs
conf SimpleName MethodInvocation SimpleName fs
system SimpleName MethodInvocation SimpleName exit
system SimpleName MethodInvocation PrefixExpression NumberLiteral empty
exit SimpleName MethodInvocation PrefixExpression NumberLiteral empty
exception SimpleName SimpleType SingleVariableDeclaration SimpleName e
log SimpleName MethodInvocation SimpleName fatal
log SimpleName MethodInvocation SimpleName e
log SimpleName MethodInvocation SimpleName e
fatal SimpleName MethodInvocation SimpleName e
fatal SimpleName MethodInvocation SimpleName e
e SimpleName MethodInvocation SimpleName e
runtime exception SimpleName SimpleType ClassInstanceCreation SimpleName e
boolean PrimitiveType VariableDeclarationStatement Block EnhancedForStatement SimpleName args
public Modifier MethodDeclaration Modifier static
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName main
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName args
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
public Modifier MethodDeclaration Block EnhancedForStatement SimpleName args
static Modifier MethodDeclaration PrimitiveType void
static Modifier MethodDeclaration SimpleName main
static Modifier MethodDeclaration SingleVariableDeclaration SimpleName args
static Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
static Modifier MethodDeclaration Block EnhancedForStatement SimpleName args
void PrimitiveType MethodDeclaration SimpleName main
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName args
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
void PrimitiveType MethodDeclaration Block EnhancedForStatement SimpleName args
main SimpleName MethodDeclaration SingleVariableDeclaration SimpleName args
main SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
main SimpleName MethodDeclaration Block EnhancedForStatement SimpleName args
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration Modifier static
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName main
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName args
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration Modifier static
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName main
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName args
