public Modifier MethodDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SimpleName get server
public Modifier MethodDeclaration Block ReturnStatement SimpleName server
string SimpleName SimpleType MethodDeclaration SimpleName get server
get server SimpleName MethodDeclaration Block ReturnStatement SimpleName server
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName string
public Modifier TypeDeclaration MethodDeclaration SimpleName get server
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName string
test SimpleName TypeDeclaration MethodDeclaration SimpleName get server
