value SimpleName SimpleType SingleVariableDeclaration SimpleName value
value SimpleName MethodInvocation SimpleName get
string SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName value
string SimpleName SimpleType ClassInstanceCreation MethodInvocation SimpleName get
long SimpleName MethodInvocation SimpleName parse long
long SimpleName MethodInvocation ClassInstanceCreation SimpleType SimpleName string
long SimpleName MethodInvocation ClassInstanceCreation MethodInvocation SimpleName value
long SimpleName MethodInvocation ClassInstanceCreation MethodInvocation SimpleName get
parse long SimpleName MethodInvocation ClassInstanceCreation SimpleType SimpleName string
parse long SimpleName MethodInvocation ClassInstanceCreation MethodInvocation SimpleName value
parse long SimpleName MethodInvocation ClassInstanceCreation MethodInvocation SimpleName get
sum SimpleName Assignment MethodInvocation SimpleName long
sum SimpleName Assignment MethodInvocation SimpleName parse long
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName collect
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName value
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName value
void PrimitiveType MethodDeclaration SimpleName collect
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName value
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName value
collect SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName value
collect SimpleName MethodDeclaration SingleVariableDeclaration SimpleName value
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName collect
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName value
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName collect
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName value
