boolean PrimitiveType SingleVariableDeclaration SimpleName b
has next SimpleName FieldAccess Assignment SimpleName b
void PrimitiveType MethodDeclaration SimpleName set has next
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName b
set has next SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
set has next SimpleName MethodDeclaration SingleVariableDeclaration SimpleName b
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set has next
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName b
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set has next
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName b
