string SimpleName SimpleType SingleVariableDeclaration SimpleName principal
string SimpleName SimpleType SingleVariableDeclaration SimpleName namespace
namespace permission SimpleName SimpleType SingleVariableDeclaration SimpleName permission
acuusers QualifiedName MethodInvocation SimpleName get
acuusers QualifiedName MethodInvocation SimpleName principal
get SimpleName MethodInvocation SimpleName principal
accumulo security exception SimpleName SimpleType ClassInstanceCreation SimpleName principal
accumulo security exception SimpleName SimpleType ClassInstanceCreation QualifiedName security error codeuser doesnt exist
principal SimpleName ClassInstanceCreation QualifiedName security error codeuser doesnt exist
acunamespaces QualifiedName MethodInvocation SimpleName get
acunamespaces QualifiedName MethodInvocation SimpleName namespace
get SimpleName MethodInvocation SimpleName namespace
mock namespace SimpleName VariableDeclarationFragment MethodInvocation QualifiedName acunamespaces
mock namespace SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
mock namespace SimpleName VariableDeclarationFragment MethodInvocation SimpleName namespace
mock namespace SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName mock namespace
accumulo security exception SimpleName SimpleType ClassInstanceCreation SimpleName namespace
accumulo security exception SimpleName SimpleType ClassInstanceCreation QualifiedName security error codenamespace doesnt exist
namespace SimpleName ClassInstanceCreation QualifiedName security error codenamespace doesnt exist
enum set SimpleName SimpleType ParameterizedType SimpleType SimpleName namespace permission
mock namespaceuser permissions QualifiedName MethodInvocation SimpleName get
mock namespaceuser permissions QualifiedName MethodInvocation SimpleName principal
get SimpleName MethodInvocation SimpleName principal
perms SimpleName VariableDeclarationFragment MethodInvocation QualifiedName mock namespaceuser permissions
perms SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
perms SimpleName VariableDeclarationFragment MethodInvocation SimpleName principal
perms SimpleName MethodInvocation SimpleName remove
perms SimpleName MethodInvocation SimpleName permission
remove SimpleName MethodInvocation SimpleName permission
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName revoke namespace permission
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName principal
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName namespace
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName revoke namespace permission
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName principal
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName namespace
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName namespace permission
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName permission
void PrimitiveType MethodDeclaration SimpleName revoke namespace permission
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName principal
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName namespace
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName namespace permission
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName permission
void PrimitiveType MethodDeclaration SimpleType SimpleName accumulo exception
revoke namespace permission SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
revoke namespace permission SimpleName MethodDeclaration SingleVariableDeclaration SimpleName principal
revoke namespace permission SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
revoke namespace permission SimpleName MethodDeclaration SingleVariableDeclaration SimpleName namespace
revoke namespace permission SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName namespace permission
revoke namespace permission SimpleName MethodDeclaration SingleVariableDeclaration SimpleName permission
revoke namespace permission SimpleName MethodDeclaration SimpleType SimpleName accumulo exception
revoke namespace permission SimpleName MethodDeclaration SimpleType SimpleName accumulo security exception
principal SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
principal SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName permission
principal SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName accumulo exception
principal SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName accumulo security exception
namespace SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName permission
namespace SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName accumulo exception
namespace SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName accumulo security exception
permission SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName accumulo exception
permission SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName accumulo security exception
accumulo exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName accumulo security exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName revoke namespace permission
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName principal
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName permission
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName accumulo exception
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName accumulo security exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName revoke namespace permission
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName principal
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName namespace
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName permission
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName accumulo exception
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName accumulo security exception
