list SimpleName SimpleType ParameterizedType SimpleType SimpleName cohort config
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName cohort config list
cohort config SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName cohort config list
array list SimpleName SimpleType ParameterizedType ClassInstanceCreation SimpleName cohort config list
cohort config list SimpleName FieldAccess Assignment ClassInstanceCreation SimpleName cohort config list
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set cohort config list
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName cohort config list
void PrimitiveType MethodDeclaration SimpleName set cohort config list
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName cohort config list
set cohort config list SimpleName MethodDeclaration SingleVariableDeclaration SimpleName cohort config list
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set cohort config list
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cohort config list
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set cohort config list
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName cohort config list
