guid SimpleName VariableDeclarationFragment StringLiteral - - c ae - a e b b a
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral - - c ae - a e b b a
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral - - c ae - a e b b a
name SimpleName VariableDeclarationFragment StringLiteral server asset use
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral server asset use
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral server asset use
description SimpleName VariableDeclarationFragment StringLiteral defines how a server capability may use an asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral defines how a server capability may use an asset
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral defines how a server capability may use an asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName description guid
archive helper SimpleName MethodInvocation SimpleName get empty enum def
archive helper SimpleName MethodInvocation SimpleName guid
archive helper SimpleName MethodInvocation SimpleName name
archive helper SimpleName MethodInvocation SimpleName description
archive helper SimpleName MethodInvocation SimpleName description guid
get empty enum def SimpleName MethodInvocation SimpleName guid
get empty enum def SimpleName MethodInvocation SimpleName name
get empty enum def SimpleName MethodInvocation SimpleName description
get empty enum def SimpleName MethodInvocation SimpleName description guid
guid SimpleName MethodInvocation SimpleName name
guid SimpleName MethodInvocation SimpleName description
guid SimpleName MethodInvocation SimpleName description guid
name SimpleName MethodInvocation SimpleName description
name SimpleName MethodInvocation SimpleName description guid
description SimpleName MethodInvocation SimpleName description guid
enum def SimpleName VariableDeclarationFragment MethodInvocation SimpleName archive helper
enum def SimpleName VariableDeclarationFragment MethodInvocation SimpleName get empty enum def
enum def SimpleName VariableDeclarationFragment MethodInvocation SimpleName guid
enum def SimpleName VariableDeclarationFragment MethodInvocation SimpleName name
enum def SimpleName VariableDeclarationFragment MethodInvocation SimpleName description
enum def SimpleName VariableDeclarationFragment MethodInvocation SimpleName description guid
enum def SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName enum def
array list SimpleName SimpleType ParameterizedType SimpleType SimpleName enum element def
enum element def SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element def
element ordinal SimpleName VariableDeclarationFragment NumberLiteral empty
final Modifier VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
final Modifier VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
element value SimpleName VariableDeclarationFragment StringLiteral owns
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral owns
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral owns
element description SimpleName VariableDeclarationFragment StringLiteral the server capability is accountable for the maintenance and protection of the asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability is accountable for the maintenance and protection of the asset
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability is accountable for the maintenance and protection of the asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
archive helper SimpleName MethodInvocation SimpleName get enum element def
archive helper SimpleName MethodInvocation SimpleName element ordinal
archive helper SimpleName MethodInvocation SimpleName element value
archive helper SimpleName MethodInvocation SimpleName element description
archive helper SimpleName MethodInvocation SimpleName element description guid
get enum element def SimpleName MethodInvocation SimpleName element ordinal
get enum element def SimpleName MethodInvocation SimpleName element value
get enum element def SimpleName MethodInvocation SimpleName element description
get enum element def SimpleName MethodInvocation SimpleName element description guid
element ordinal SimpleName MethodInvocation SimpleName element value
element ordinal SimpleName MethodInvocation SimpleName element description
element ordinal SimpleName MethodInvocation SimpleName element description guid
element value SimpleName MethodInvocation SimpleName element description
element value SimpleName MethodInvocation SimpleName element description guid
element description SimpleName MethodInvocation SimpleName element description guid
element def SimpleName Assignment MethodInvocation SimpleName archive helper
element def SimpleName Assignment MethodInvocation SimpleName get enum element def
element def SimpleName Assignment MethodInvocation SimpleName element ordinal
element def SimpleName Assignment MethodInvocation SimpleName element value
element def SimpleName Assignment MethodInvocation SimpleName element description
element def SimpleName Assignment MethodInvocation SimpleName element description guid
element defs SimpleName MethodInvocation SimpleName add
element defs SimpleName MethodInvocation SimpleName element def
add SimpleName MethodInvocation SimpleName element def
element ordinal SimpleName VariableDeclarationFragment NumberLiteral empty
final Modifier VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
final Modifier VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
element value SimpleName VariableDeclarationFragment StringLiteral governs
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral governs
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral governs
element description SimpleName VariableDeclarationFragment StringLiteral the server capability provides management or oversight of the asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability provides management or oversight of the asset
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability provides management or oversight of the asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
archive helper SimpleName MethodInvocation SimpleName get enum element def
archive helper SimpleName MethodInvocation SimpleName element ordinal
archive helper SimpleName MethodInvocation SimpleName element value
archive helper SimpleName MethodInvocation SimpleName element description
archive helper SimpleName MethodInvocation SimpleName element description guid
get enum element def SimpleName MethodInvocation SimpleName element ordinal
get enum element def SimpleName MethodInvocation SimpleName element value
get enum element def SimpleName MethodInvocation SimpleName element description
get enum element def SimpleName MethodInvocation SimpleName element description guid
element ordinal SimpleName MethodInvocation SimpleName element value
element ordinal SimpleName MethodInvocation SimpleName element description
element ordinal SimpleName MethodInvocation SimpleName element description guid
element value SimpleName MethodInvocation SimpleName element description
element value SimpleName MethodInvocation SimpleName element description guid
element description SimpleName MethodInvocation SimpleName element description guid
element def SimpleName Assignment MethodInvocation SimpleName archive helper
element def SimpleName Assignment MethodInvocation SimpleName get enum element def
element def SimpleName Assignment MethodInvocation SimpleName element ordinal
element def SimpleName Assignment MethodInvocation SimpleName element value
element def SimpleName Assignment MethodInvocation SimpleName element description
element def SimpleName Assignment MethodInvocation SimpleName element description guid
element defs SimpleName MethodInvocation SimpleName add
element defs SimpleName MethodInvocation SimpleName element def
add SimpleName MethodInvocation SimpleName element def
element ordinal SimpleName VariableDeclarationFragment NumberLiteral empty
final Modifier VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
final Modifier VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
element value SimpleName VariableDeclarationFragment StringLiteral maintains
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral maintains
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral maintains
element description SimpleName VariableDeclarationFragment StringLiteral the server capability keeps the asset uptodate
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability keeps the asset uptodate
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability keeps the asset uptodate
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
archive helper SimpleName MethodInvocation SimpleName get enum element def
archive helper SimpleName MethodInvocation SimpleName element ordinal
archive helper SimpleName MethodInvocation SimpleName element value
archive helper SimpleName MethodInvocation SimpleName element description
archive helper SimpleName MethodInvocation SimpleName element description guid
get enum element def SimpleName MethodInvocation SimpleName element ordinal
get enum element def SimpleName MethodInvocation SimpleName element value
get enum element def SimpleName MethodInvocation SimpleName element description
get enum element def SimpleName MethodInvocation SimpleName element description guid
element ordinal SimpleName MethodInvocation SimpleName element value
element ordinal SimpleName MethodInvocation SimpleName element description
element ordinal SimpleName MethodInvocation SimpleName element description guid
element value SimpleName MethodInvocation SimpleName element description
element value SimpleName MethodInvocation SimpleName element description guid
element description SimpleName MethodInvocation SimpleName element description guid
element def SimpleName Assignment MethodInvocation SimpleName archive helper
element def SimpleName Assignment MethodInvocation SimpleName get enum element def
element def SimpleName Assignment MethodInvocation SimpleName element ordinal
element def SimpleName Assignment MethodInvocation SimpleName element value
element def SimpleName Assignment MethodInvocation SimpleName element description
element def SimpleName Assignment MethodInvocation SimpleName element description guid
element defs SimpleName MethodInvocation SimpleName add
element defs SimpleName MethodInvocation SimpleName element def
add SimpleName MethodInvocation SimpleName element def
element ordinal SimpleName VariableDeclarationFragment NumberLiteral empty
final Modifier VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
final Modifier VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
element value SimpleName VariableDeclarationFragment StringLiteral uses
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral uses
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral uses
element description SimpleName VariableDeclarationFragment StringLiteral the server capability consumes the content of the asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability consumes the content of the asset
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral the server capability consumes the content of the asset
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
archive helper SimpleName MethodInvocation SimpleName get enum element def
archive helper SimpleName MethodInvocation SimpleName element ordinal
archive helper SimpleName MethodInvocation SimpleName element value
archive helper SimpleName MethodInvocation SimpleName element description
archive helper SimpleName MethodInvocation SimpleName element description guid
get enum element def SimpleName MethodInvocation SimpleName element ordinal
get enum element def SimpleName MethodInvocation SimpleName element value
get enum element def SimpleName MethodInvocation SimpleName element description
get enum element def SimpleName MethodInvocation SimpleName element description guid
element ordinal SimpleName MethodInvocation SimpleName element value
element ordinal SimpleName MethodInvocation SimpleName element description
element ordinal SimpleName MethodInvocation SimpleName element description guid
element value SimpleName MethodInvocation SimpleName element description
element value SimpleName MethodInvocation SimpleName element description guid
element description SimpleName MethodInvocation SimpleName element description guid
element def SimpleName Assignment MethodInvocation SimpleName archive helper
element def SimpleName Assignment MethodInvocation SimpleName get enum element def
element def SimpleName Assignment MethodInvocation SimpleName element ordinal
element def SimpleName Assignment MethodInvocation SimpleName element value
element def SimpleName Assignment MethodInvocation SimpleName element description
element def SimpleName Assignment MethodInvocation SimpleName element description guid
element defs SimpleName MethodInvocation SimpleName add
element defs SimpleName MethodInvocation SimpleName element def
add SimpleName MethodInvocation SimpleName element def
element ordinal SimpleName VariableDeclarationFragment NumberLiteral empty
final Modifier VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
final Modifier VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName element ordinal
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
element value SimpleName VariableDeclarationFragment StringLiteral other
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral other
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element value
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral other
element description SimpleName VariableDeclarationFragment StringLiteral another usage
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral another usage
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral another usage
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName element description guid
archive helper SimpleName MethodInvocation SimpleName get enum element def
archive helper SimpleName MethodInvocation SimpleName element ordinal
archive helper SimpleName MethodInvocation SimpleName element value
archive helper SimpleName MethodInvocation SimpleName element description
archive helper SimpleName MethodInvocation SimpleName element description guid
get enum element def SimpleName MethodInvocation SimpleName element ordinal
get enum element def SimpleName MethodInvocation SimpleName element value
get enum element def SimpleName MethodInvocation SimpleName element description
get enum element def SimpleName MethodInvocation SimpleName element description guid
element ordinal SimpleName MethodInvocation SimpleName element value
element ordinal SimpleName MethodInvocation SimpleName element description
element ordinal SimpleName MethodInvocation SimpleName element description guid
element value SimpleName MethodInvocation SimpleName element description
element value SimpleName MethodInvocation SimpleName element description guid
element description SimpleName MethodInvocation SimpleName element description guid
element def SimpleName Assignment MethodInvocation SimpleName archive helper
element def SimpleName Assignment MethodInvocation SimpleName get enum element def
element def SimpleName Assignment MethodInvocation SimpleName element ordinal
element def SimpleName Assignment MethodInvocation SimpleName element value
element def SimpleName Assignment MethodInvocation SimpleName element description
element def SimpleName Assignment MethodInvocation SimpleName element description guid
element defs SimpleName MethodInvocation SimpleName add
element defs SimpleName MethodInvocation SimpleName element def
add SimpleName MethodInvocation SimpleName element def
enum def SimpleName MethodInvocation SimpleName set element defs
enum def SimpleName MethodInvocation SimpleName element defs
set element defs SimpleName MethodInvocation SimpleName element defs
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName enum def
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName enum def
private Modifier MethodDeclaration SimpleType SimpleName enum def
private Modifier MethodDeclaration SimpleName get server asset use type enum
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block ReturnStatement SimpleName enum def
enum def SimpleName SimpleType MethodDeclaration SimpleName get server asset use type enum
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get server asset use type enum SimpleName MethodDeclaration Block ReturnStatement SimpleName enum def
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName enum def
public Modifier TypeDeclaration MethodDeclaration SimpleName get server asset use type enum
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName enum def
test SimpleName TypeDeclaration MethodDeclaration SimpleName get server asset use type enum
