string SimpleName SimpleType SingleVariableDeclaration SimpleName user id
string SimpleName SimpleType SingleVariableDeclaration SimpleName entity guid
instance status SimpleName SimpleType SingleVariableDeclaration SimpleName new status
method name SimpleName VariableDeclarationFragment StringLiteral update entity status
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral update entity status
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral update entity status
validate repository SimpleName MethodInvocation SimpleName method name
repository validator SimpleName MethodInvocation SimpleName validate user id
repository validator SimpleName MethodInvocation SimpleName repository name
repository validator SimpleName MethodInvocation SimpleName user id
repository validator SimpleName MethodInvocation SimpleName method name
validate user id SimpleName MethodInvocation SimpleName repository name
validate user id SimpleName MethodInvocation SimpleName user id
validate user id SimpleName MethodInvocation SimpleName method name
repository name SimpleName MethodInvocation SimpleName user id
repository name SimpleName MethodInvocation SimpleName method name
user id SimpleName MethodInvocation SimpleName method name
real metadata collection SimpleName MethodInvocation SimpleName update entity status
real metadata collection SimpleName MethodInvocation SimpleName user id
real metadata collection SimpleName MethodInvocation SimpleName entity guid
real metadata collection SimpleName MethodInvocation SimpleName new status
update entity status SimpleName MethodInvocation SimpleName user id
update entity status SimpleName MethodInvocation SimpleName entity guid
update entity status SimpleName MethodInvocation SimpleName new status
user id SimpleName MethodInvocation SimpleName entity guid
user id SimpleName MethodInvocation SimpleName new status
entity guid SimpleName MethodInvocation SimpleName new status
entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName real metadata collection
entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName update entity status
entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName user id
entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName entity guid
entity SimpleName VariableDeclarationFragment MethodInvocation SimpleName new status
entity detail SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity
notify of updated entity SimpleName MethodInvocation SimpleName entity
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName entity
public Modifier MethodDeclaration SimpleType SimpleName entity detail
public Modifier MethodDeclaration SimpleName update entity status
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName user id
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity guid
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName instance status
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName new status
entity detail SimpleName SimpleType MethodDeclaration SimpleName update entity status
entity detail SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName user id
entity detail SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName entity guid
entity detail SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName new status
entity detail SimpleName SimpleType MethodDeclaration SimpleType SimpleName invalid parameter exception
update entity status SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
update entity status SimpleName MethodDeclaration SingleVariableDeclaration SimpleName user id
update entity status SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
update entity status SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity guid
update entity status SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName instance status
update entity status SimpleName MethodDeclaration SingleVariableDeclaration SimpleName new status
update entity status SimpleName MethodDeclaration SimpleType SimpleName invalid parameter exception
update entity status SimpleName MethodDeclaration SimpleType SimpleName repository error exception
user id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity guid
user id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new status
user id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName invalid parameter exception
user id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName repository error exception
user id SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName entity not known exception
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new status
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName invalid parameter exception
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName repository error exception
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName entity not known exception
entity guid SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName status not supported exception
new status SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName invalid parameter exception
new status SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName repository error exception
new status SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName entity not known exception
new status SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName status not supported exception
new status SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName user not authorized exception
invalid parameter exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName repository error exception
invalid parameter exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName entity not known exception
invalid parameter exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName status not supported exception
invalid parameter exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName user not authorized exception
repository error exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName entity not known exception
repository error exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName status not supported exception
repository error exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName user not authorized exception
entity not known exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName status not supported exception
entity not known exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName user not authorized exception
status not supported exception SimpleName SimpleType MethodDeclaration SimpleType SimpleName user not authorized exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail
public Modifier TypeDeclaration MethodDeclaration SimpleName update entity status
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity guid
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new status
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName invalid parameter exception
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName repository error exception
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity not known exception
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName status not supported exception
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName user not authorized exception
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail
test SimpleName TypeDeclaration MethodDeclaration SimpleName update entity status
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity guid
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName new status
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName invalid parameter exception
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName repository error exception
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity not known exception
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName status not supported exception
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName user not authorized exception
