string SimpleName SimpleType SingleVariableDeclaration SimpleName source name
string SimpleName SimpleType SingleVariableDeclaration SimpleName metadata collection id
entity detail SimpleName SimpleType SingleVariableDeclaration SimpleName entity
entity detail SimpleName SimpleType ClassInstanceCreation SimpleName entity
processed entity SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName entity detail
processed entity SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleName entity
entity detail SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName processed entity
processed entity SimpleName MethodInvocation SimpleName set metadata collection id
processed entity SimpleName MethodInvocation SimpleName metadata collection id
set metadata collection id SimpleName MethodInvocation SimpleName metadata collection id
method name SimpleName VariableDeclarationFragment StringLiteral process retrieved entity
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral process retrieved entity
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral process retrieved entity
entity parameter name SimpleName VariableDeclarationFragment StringLiteral entity
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName entity parameter name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral entity
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity parameter name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral entity
update reference entity SimpleName MethodInvocation SimpleName source name
update reference entity SimpleName MethodInvocation SimpleName method name
update reference entity SimpleName MethodInvocation SimpleName entity parameter name
update reference entity SimpleName MethodInvocation SimpleName metadata collection id
update reference entity SimpleName MethodInvocation SimpleName local server name
source name SimpleName MethodInvocation SimpleName method name
source name SimpleName MethodInvocation SimpleName entity parameter name
source name SimpleName MethodInvocation SimpleName metadata collection id
source name SimpleName MethodInvocation SimpleName local server name
source name SimpleName MethodInvocation SimpleName entity
method name SimpleName MethodInvocation SimpleName entity parameter name
method name SimpleName MethodInvocation SimpleName metadata collection id
method name SimpleName MethodInvocation SimpleName local server name
method name SimpleName MethodInvocation SimpleName entity
entity parameter name SimpleName MethodInvocation SimpleName metadata collection id
entity parameter name SimpleName MethodInvocation SimpleName local server name
entity parameter name SimpleName MethodInvocation SimpleName entity
metadata collection id SimpleName MethodInvocation SimpleName local server name
metadata collection id SimpleName MethodInvocation SimpleName entity
local server name SimpleName MethodInvocation SimpleName entity
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName entity
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName entity
public Modifier MethodDeclaration SimpleType SimpleName entity detail
public Modifier MethodDeclaration SimpleName process retrieved entity
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName source name
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName metadata collection id
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName entity detail
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity
entity detail SimpleName SimpleType MethodDeclaration SimpleName process retrieved entity
entity detail SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName source name
entity detail SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName metadata collection id
entity detail SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName entity
process retrieved entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
process retrieved entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName source name
process retrieved entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
process retrieved entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName metadata collection id
process retrieved entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName entity detail
process retrieved entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity
process retrieved entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
process retrieved entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
process retrieved entity SimpleName MethodDeclaration Block ReturnStatement SimpleName entity
source name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName metadata collection id
source name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity
metadata collection id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail
public Modifier TypeDeclaration MethodDeclaration SimpleName process retrieved entity
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName source name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName metadata collection id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail
test SimpleName TypeDeclaration MethodDeclaration SimpleName process retrieved entity
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName source name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName metadata collection id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity
