objects SimpleName MethodInvocation SimpleName hash
objects SimpleName MethodInvocation SimpleName array count
objects SimpleName MethodInvocation SimpleName array values
hash SimpleName MethodInvocation SimpleName array count
hash SimpleName MethodInvocation SimpleName array values
array count SimpleName MethodInvocation SimpleName array values
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType int
override SimpleName MarkerAnnotation MethodDeclaration SimpleName hash code
public Modifier MethodDeclaration PrimitiveType int
public Modifier MethodDeclaration SimpleName hash code
int PrimitiveType MethodDeclaration SimpleName hash code
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SimpleName hash code
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SimpleName hash code
