guid SimpleName VariableDeclarationFragment StringLiteral ba a b - bf b ceca a
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral ba a b - bf b ceca a
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral ba a b - bf b ceca a
name SimpleName VariableDeclarationFragment StringLiteral informal tag
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral informal tag
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral informal tag
description SimpleName VariableDeclarationFragment StringLiteral an descriptive tag for an item
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral an descriptive tag for an item
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral an descriptive tag for an item
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName description guid
archive helper SimpleName MethodInvocation SimpleName get default entity def
archive helper SimpleName MethodInvocation SimpleName guid
archive helper SimpleName MethodInvocation SimpleName name
archive helper SimpleName MethodInvocation SimpleName description
get default entity def SimpleName MethodInvocation SimpleName guid
get default entity def SimpleName MethodInvocation SimpleName name
get default entity def SimpleName MethodInvocation SimpleName description
get default entity def SimpleName MethodInvocation SimpleName description guid
guid SimpleName MethodInvocation SimpleName name
guid SimpleName MethodInvocation SimpleName description
guid SimpleName MethodInvocation SimpleName description guid
name SimpleName MethodInvocation SimpleName description
name SimpleName MethodInvocation SimpleName description guid
description SimpleName MethodInvocation SimpleName description guid
entity def SimpleName VariableDeclarationFragment MethodInvocation SimpleName archive helper
entity def SimpleName VariableDeclarationFragment MethodInvocation SimpleName get default entity def
entity def SimpleName VariableDeclarationFragment MethodInvocation SimpleName guid
entity def SimpleName VariableDeclarationFragment MethodInvocation SimpleName name
entity def SimpleName VariableDeclarationFragment MethodInvocation SimpleName description
entity def SimpleName VariableDeclarationFragment MethodInvocation SimpleName description guid
entity def SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity def
array list SimpleName SimpleType ParameterizedType SimpleType SimpleName type def attribute
type def attribute SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName property
attribute name SimpleName VariableDeclarationFragment StringLiteral tag name
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral tag name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral tag name
attribute description SimpleName VariableDeclarationFragment StringLiteral descriptive name of the tag
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral descriptive name of the tag
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral descriptive name of the tag
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description guid
attribute name SimpleName VariableDeclarationFragment StringLiteral tag description
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral tag description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral tag description
attribute description SimpleName VariableDeclarationFragment StringLiteral more detail on the meaning of the tag
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral more detail on the meaning of the tag
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral more detail on the meaning of the tag
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute description guid
archive helper SimpleName MethodInvocation SimpleName get string type def attribute
archive helper SimpleName MethodInvocation SimpleName attribute name
archive helper SimpleName MethodInvocation SimpleName attribute description
archive helper SimpleName MethodInvocation SimpleName attribute description guid
get string type def attribute SimpleName MethodInvocation SimpleName attribute name
get string type def attribute SimpleName MethodInvocation SimpleName attribute description
get string type def attribute SimpleName MethodInvocation SimpleName attribute description guid
attribute name SimpleName MethodInvocation SimpleName attribute description
attribute name SimpleName MethodInvocation SimpleName attribute description guid
attribute description SimpleName MethodInvocation SimpleName attribute description guid
property SimpleName Assignment MethodInvocation SimpleName archive helper
property SimpleName Assignment MethodInvocation SimpleName get string type def attribute
property SimpleName Assignment MethodInvocation SimpleName attribute name
property SimpleName Assignment MethodInvocation SimpleName attribute description
property SimpleName Assignment MethodInvocation SimpleName attribute description guid
properties SimpleName MethodInvocation SimpleName add
properties SimpleName MethodInvocation SimpleName property
add SimpleName MethodInvocation SimpleName property
archive helper SimpleName MethodInvocation SimpleName get string type def attribute
archive helper SimpleName MethodInvocation SimpleName attribute name
archive helper SimpleName MethodInvocation SimpleName attribute description
archive helper SimpleName MethodInvocation SimpleName attribute description guid
get string type def attribute SimpleName MethodInvocation SimpleName attribute name
get string type def attribute SimpleName MethodInvocation SimpleName attribute description
get string type def attribute SimpleName MethodInvocation SimpleName attribute description guid
attribute name SimpleName MethodInvocation SimpleName attribute description
attribute name SimpleName MethodInvocation SimpleName attribute description guid
attribute description SimpleName MethodInvocation SimpleName attribute description guid
property SimpleName Assignment MethodInvocation SimpleName archive helper
property SimpleName Assignment MethodInvocation SimpleName get string type def attribute
property SimpleName Assignment MethodInvocation SimpleName attribute name
property SimpleName Assignment MethodInvocation SimpleName attribute description
property SimpleName Assignment MethodInvocation SimpleName attribute description guid
properties SimpleName MethodInvocation SimpleName add
properties SimpleName MethodInvocation SimpleName property
add SimpleName MethodInvocation SimpleName property
entity def SimpleName MethodInvocation SimpleName set properties definition
entity def SimpleName MethodInvocation SimpleName properties
set properties definition SimpleName MethodInvocation SimpleName properties
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration SimpleType SimpleName entity def
private Modifier MethodDeclaration SimpleName get informal tag entity
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block ReturnStatement SimpleName entity def
entity def SimpleName SimpleType MethodDeclaration SimpleName get informal tag entity
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get informal tag entity SimpleName MethodDeclaration Block ReturnStatement SimpleName entity def
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity def
public Modifier TypeDeclaration MethodDeclaration SimpleName get informal tag entity
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity def
test SimpleName TypeDeclaration MethodDeclaration SimpleName get informal tag entity
