string SimpleName SimpleType SingleVariableDeclaration SimpleName user action
user action SimpleName FieldAccess Assignment SimpleName user action
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set user action
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName user action
void PrimitiveType MethodDeclaration SimpleName set user action
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName user action
set user action SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
set user action SimpleName MethodDeclaration SingleVariableDeclaration SimpleName user action
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set user action
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user action
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set user action
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user action
