archive builder SimpleName FieldAccess MethodInvocation SimpleName add relationship def
archive builder SimpleName FieldAccess MethodInvocation MethodInvocation SimpleName get asset schema type relationship
add relationship def SimpleName MethodInvocation MethodInvocation SimpleName get asset schema type relationship
private Modifier MethodDeclaration PrimitiveType void
private Modifier MethodDeclaration SimpleName add asset schemas
void PrimitiveType MethodDeclaration SimpleName add asset schemas
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName add asset schemas
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName add asset schemas
