object SimpleName SimpleType SingleVariableDeclaration SimpleName obj
string SimpleName SimpleType SingleVariableDeclaration SimpleName obj name
list SimpleName SimpleType ParameterizedType SimpleType SimpleName string
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName messages
string SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName messages
ret SimpleName VariableDeclarationFragment BooleanLiteral true
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName ret
boolean PrimitiveType VariableDeclarationStatement VariableDeclarationFragment BooleanLiteral true
map utils SimpleName MethodInvocation SimpleName is not empty
map utils SimpleName MethodInvocation SimpleName relationship attributes
is not empty SimpleName MethodInvocation SimpleName relationship attributes
obj SimpleName InfixExpression InfixExpression MethodInvocation SimpleName map utils
obj SimpleName InfixExpression InfixExpression MethodInvocation SimpleName is not empty
obj SimpleName InfixExpression InfixExpression MethodInvocation SimpleName relationship attributes
obj SimpleName InstanceofExpression SimpleType SimpleName atlas entity
atlas entity SimpleName SimpleType CastExpression SimpleName obj
entity obj SimpleName VariableDeclarationFragment CastExpression SimpleType SimpleName atlas entity
entity obj SimpleName VariableDeclarationFragment CastExpression SimpleName obj
atlas entity SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity obj
atlas attribute SimpleName SimpleType SingleVariableDeclaration SimpleName attribute
relationship attributes SimpleName MethodInvocation SimpleName values
attribute SimpleName MethodInvocation SimpleName get name
attribute name SimpleName VariableDeclarationFragment MethodInvocation SimpleName attribute
attribute name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute name
attribute SimpleName MethodInvocation SimpleName get attribute type
data type SimpleName VariableDeclarationFragment MethodInvocation SimpleName attribute
data type SimpleName VariableDeclarationFragment MethodInvocation SimpleName get attribute type
atlas type SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName data type
entity obj SimpleName MethodInvocation SimpleName get attribute
entity obj SimpleName MethodInvocation SimpleName attribute name
get attribute SimpleName MethodInvocation SimpleName attribute name
value SimpleName VariableDeclarationFragment MethodInvocation SimpleName entity obj
value SimpleName VariableDeclarationFragment MethodInvocation SimpleName get attribute
value SimpleName VariableDeclarationFragment MethodInvocation SimpleName attribute name
object SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName value
obj name SimpleName InfixExpression StringLiteral .
obj name SimpleName InfixExpression SimpleName attribute name
. StringLiteral InfixExpression SimpleName attribute name
field name SimpleName VariableDeclarationFragment InfixExpression SimpleName obj name
field name SimpleName VariableDeclarationFragment InfixExpression StringLiteral .
field name SimpleName VariableDeclarationFragment InfixExpression SimpleName attribute name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName field name
is valid relationship type SimpleName MethodInvocation SimpleName data type
is valid relationship type SimpleName MethodInvocation InfixExpression InfixExpression SimpleName value
data type SimpleName MethodInvocation InfixExpression InfixExpression SimpleName value
data type SimpleName MethodInvocation SimpleName validate value
data type SimpleName MethodInvocation SimpleName value
data type SimpleName MethodInvocation SimpleName field name
data type SimpleName MethodInvocation SimpleName messages
validate value SimpleName MethodInvocation SimpleName value
validate value SimpleName MethodInvocation SimpleName field name
validate value SimpleName MethodInvocation SimpleName messages
value SimpleName MethodInvocation SimpleName field name
value SimpleName MethodInvocation SimpleName messages
field name SimpleName MethodInvocation SimpleName messages
data type SimpleName MethodInvocation InfixExpression SimpleName ret
validate value SimpleName MethodInvocation InfixExpression SimpleName ret
value SimpleName MethodInvocation InfixExpression SimpleName ret
field name SimpleName MethodInvocation InfixExpression SimpleName ret
messages SimpleName MethodInvocation InfixExpression SimpleName ret
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName data type
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName validate value
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName value
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName field name
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName messages
ret SimpleName Assignment InfixExpression SimpleName ret
attribute SimpleName SingleVariableDeclaration EnhancedForStatement MethodInvocation SimpleName relationship attributes
attribute SimpleName SingleVariableDeclaration EnhancedForStatement MethodInvocation SimpleName values
obj SimpleName InstanceofExpression SimpleType SimpleName map
map SimpleName SimpleType CastExpression SimpleName obj
atlas type util SimpleName MethodInvocation SimpleName to struct attributes
atlas type util SimpleName MethodInvocation CastExpression SimpleType SimpleName map
atlas type util SimpleName MethodInvocation CastExpression SimpleName obj
to struct attributes SimpleName MethodInvocation CastExpression SimpleType SimpleName map
to struct attributes SimpleName MethodInvocation CastExpression SimpleName obj
attributes SimpleName VariableDeclarationFragment MethodInvocation SimpleName atlas type util
attributes SimpleName VariableDeclarationFragment MethodInvocation SimpleName to struct attributes
attributes SimpleName VariableDeclarationFragment MethodInvocation CastExpression SimpleName obj
map SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attributes
atlas attribute SimpleName SimpleType SingleVariableDeclaration SimpleName attribute
relationship attributes SimpleName MethodInvocation SimpleName values
attribute SimpleName MethodInvocation SimpleName get name
attribute name SimpleName VariableDeclarationFragment MethodInvocation SimpleName attribute
attribute name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName attribute name
attribute SimpleName MethodInvocation SimpleName get attribute type
data type SimpleName VariableDeclarationFragment MethodInvocation SimpleName attribute
data type SimpleName VariableDeclarationFragment MethodInvocation SimpleName get attribute type
atlas type SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName data type
attributes SimpleName MethodInvocation SimpleName get
attributes SimpleName MethodInvocation SimpleName attribute name
get SimpleName MethodInvocation SimpleName attribute name
value SimpleName VariableDeclarationFragment MethodInvocation SimpleName attributes
value SimpleName VariableDeclarationFragment MethodInvocation SimpleName get
value SimpleName VariableDeclarationFragment MethodInvocation SimpleName attribute name
object SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName value
obj name SimpleName InfixExpression StringLiteral .
obj name SimpleName InfixExpression SimpleName attribute name
. StringLiteral InfixExpression SimpleName attribute name
field name SimpleName VariableDeclarationFragment InfixExpression SimpleName obj name
field name SimpleName VariableDeclarationFragment InfixExpression StringLiteral .
field name SimpleName VariableDeclarationFragment InfixExpression SimpleName attribute name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName field name
is valid relationship type SimpleName MethodInvocation SimpleName data type
is valid relationship type SimpleName MethodInvocation InfixExpression InfixExpression SimpleName value
data type SimpleName MethodInvocation InfixExpression InfixExpression SimpleName value
data type SimpleName MethodInvocation SimpleName validate value
data type SimpleName MethodInvocation SimpleName value
data type SimpleName MethodInvocation SimpleName field name
data type SimpleName MethodInvocation SimpleName messages
validate value SimpleName MethodInvocation SimpleName value
validate value SimpleName MethodInvocation SimpleName field name
validate value SimpleName MethodInvocation SimpleName messages
value SimpleName MethodInvocation SimpleName field name
value SimpleName MethodInvocation SimpleName messages
field name SimpleName MethodInvocation SimpleName messages
data type SimpleName MethodInvocation InfixExpression SimpleName ret
validate value SimpleName MethodInvocation InfixExpression SimpleName ret
value SimpleName MethodInvocation InfixExpression SimpleName ret
field name SimpleName MethodInvocation InfixExpression SimpleName ret
messages SimpleName MethodInvocation InfixExpression SimpleName ret
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName data type
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName validate value
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName value
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName field name
ret SimpleName Assignment InfixExpression MethodInvocation SimpleName messages
ret SimpleName Assignment InfixExpression SimpleName ret
attribute SimpleName SingleVariableDeclaration EnhancedForStatement MethodInvocation SimpleName relationship attributes
attribute SimpleName SingleVariableDeclaration EnhancedForStatement MethodInvocation SimpleName values
ret SimpleName Assignment BooleanLiteral false
obj name SimpleName InfixExpression StringLiteral =
obj name SimpleName InfixExpression SimpleName obj
obj name SimpleName InfixExpression StringLiteral : invalid value for type
obj name SimpleName InfixExpression MethodInvocation SimpleName get type name
= StringLiteral InfixExpression SimpleName obj
= StringLiteral InfixExpression StringLiteral : invalid value for type
= StringLiteral InfixExpression MethodInvocation SimpleName get type name
obj SimpleName InfixExpression StringLiteral : invalid value for type
obj SimpleName InfixExpression MethodInvocation SimpleName get type name
: invalid value for type StringLiteral InfixExpression MethodInvocation SimpleName get type name
messages SimpleName MethodInvocation SimpleName add
messages SimpleName MethodInvocation InfixExpression SimpleName obj name
messages SimpleName MethodInvocation InfixExpression StringLiteral =
messages SimpleName MethodInvocation InfixExpression SimpleName obj
messages SimpleName MethodInvocation InfixExpression StringLiteral : invalid value for type
messages SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get type name
add SimpleName MethodInvocation InfixExpression SimpleName obj name
add SimpleName MethodInvocation InfixExpression StringLiteral =
add SimpleName MethodInvocation InfixExpression SimpleName obj
add SimpleName MethodInvocation InfixExpression StringLiteral : invalid value for type
add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName get type name
boolean PrimitiveType VariableDeclarationStatement Block ReturnStatement SimpleName ret
private Modifier MethodDeclaration PrimitiveType boolean
private Modifier MethodDeclaration SimpleName validate relationship attributes
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName obj
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName obj name
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName messages
boolean PrimitiveType MethodDeclaration SimpleName validate relationship attributes
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName obj
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName obj name
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName messages
boolean PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
boolean PrimitiveType MethodDeclaration Block ReturnStatement SimpleName ret
validate relationship attributes SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName object
validate relationship attributes SimpleName MethodDeclaration SingleVariableDeclaration SimpleName obj
validate relationship attributes SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
validate relationship attributes SimpleName MethodDeclaration SingleVariableDeclaration SimpleName obj name
validate relationship attributes SimpleName MethodDeclaration SingleVariableDeclaration SimpleName messages
validate relationship attributes SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType boolean
validate relationship attributes SimpleName MethodDeclaration Block ReturnStatement SimpleName ret
obj SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName obj name
obj SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName messages
obj name SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName messages
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName validate relationship attributes
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName obj
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName obj name
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName messages
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName validate relationship attributes
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName obj
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName obj name
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName messages
