final Modifier SingleVariableDeclaration SimpleType SimpleName atlas vertex
final Modifier SingleVariableDeclaration SimpleName instance vertex
atlas vertex SimpleName SimpleType SingleVariableDeclaration SimpleName instance vertex
graph helper SimpleName MethodInvocation SimpleName get type name
graph helper SimpleName MethodInvocation SimpleName instance vertex
get type name SimpleName MethodInvocation SimpleName instance vertex
type registry SimpleName MethodInvocation SimpleName get entity type by name
type registry SimpleName MethodInvocation MethodInvocation SimpleName graph helper
type registry SimpleName MethodInvocation MethodInvocation SimpleName get type name
type registry SimpleName MethodInvocation MethodInvocation SimpleName instance vertex
get entity type by name SimpleName MethodInvocation MethodInvocation SimpleName graph helper
get entity type by name SimpleName MethodInvocation MethodInvocation SimpleName get type name
get entity type by name SimpleName MethodInvocation MethodInvocation SimpleName instance vertex
entity type SimpleName VariableDeclarationFragment MethodInvocation SimpleName type registry
entity type SimpleName VariableDeclarationFragment MethodInvocation SimpleName get entity type by name
entity type SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName graph helper
entity type SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get type name
entity type SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName instance vertex
atlas entity type SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName entity type
objects SimpleName MethodInvocation SimpleName non null
objects SimpleName MethodInvocation SimpleName entity type
non null SimpleName MethodInvocation SimpleName entity type
entity type SimpleName MethodInvocation SimpleName is internal type
objects SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName entity type
objects SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName is internal type
non null SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName entity type
non null SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName is internal type
entity type SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName entity type
entity type SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName is internal type
private Modifier MethodDeclaration PrimitiveType boolean
private Modifier MethodDeclaration SimpleName is internal type
private Modifier MethodDeclaration SingleVariableDeclaration Modifier final
private Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
private Modifier MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
boolean PrimitiveType MethodDeclaration SimpleName is internal type
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration Modifier final
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
boolean PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
is internal type SimpleName MethodDeclaration SingleVariableDeclaration Modifier final
is internal type SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas vertex
is internal type SimpleName MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SimpleName is internal type
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SimpleName is internal type
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration Modifier final
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName instance vertex
