list SimpleName SimpleType ParameterizedType SimpleType SimpleName rating
array list SimpleName SimpleType ParameterizedType ClassInstanceCreation SimpleName ratings
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName list
public Modifier MethodDeclaration ParameterizedType SimpleType SimpleName rating
public Modifier MethodDeclaration SimpleName get ratings
list SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get ratings
rating SimpleName SimpleType ParameterizedType MethodDeclaration SimpleName get ratings
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleName get ratings
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleName get ratings
