boolean PrimitiveType SingleVariableDeclaration SimpleName private tag
is private tag SimpleName Assignment SimpleName private tag
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set private tag
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName private tag
void PrimitiveType MethodDeclaration SimpleName set private tag
void PrimitiveType MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName private tag
set private tag SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
set private tag SimpleName MethodDeclaration SingleVariableDeclaration SimpleName private tag
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set private tag
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName private tag
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set private tag
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType boolean
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName private tag
