method SimpleName MemberValuePair QualifiedName request methodget
path SimpleName MemberValuePair StringLiteral user idinstancesentityguidexistence
request mapping SimpleName NormalAnnotation MemberValuePair SimpleName method
request mapping SimpleName NormalAnnotation MemberValuePair QualifiedName request methodget
request mapping SimpleName NormalAnnotation MemberValuePair SimpleName path
request mapping SimpleName NormalAnnotation MemberValuePair StringLiteral user idinstancesentityguidexistence
method SimpleName MemberValuePair NormalAnnotation MemberValuePair SimpleName path
method SimpleName MemberValuePair NormalAnnotation MemberValuePair StringLiteral user idinstancesentityguidexistence
request methodget QualifiedName MemberValuePair NormalAnnotation MemberValuePair SimpleName path
request methodget QualifiedName MemberValuePair NormalAnnotation MemberValuePair StringLiteral user idinstancesentityguidexistence
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleType SimpleName string
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleName user id
string SimpleName SimpleType SingleVariableDeclaration SimpleName user id
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleType SimpleName string
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleName guid
string SimpleName SimpleType SingleVariableDeclaration SimpleName guid
method name SimpleName VariableDeclarationFragment StringLiteral is entity known
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral is entity known
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral is entity known
response SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName entity detail response
entity detail response SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName response
validate local repository SimpleName MethodInvocation SimpleName method name
local metadata collection SimpleName MethodInvocation SimpleName is entity known
local metadata collection SimpleName MethodInvocation SimpleName user id
local metadata collection SimpleName MethodInvocation SimpleName guid
is entity known SimpleName MethodInvocation SimpleName user id
is entity known SimpleName MethodInvocation SimpleName guid
user id SimpleName MethodInvocation SimpleName guid
response SimpleName MethodInvocation SimpleName set entity
response SimpleName MethodInvocation MethodInvocation SimpleName local metadata collection
response SimpleName MethodInvocation MethodInvocation SimpleName is entity known
response SimpleName MethodInvocation MethodInvocation SimpleName user id
response SimpleName MethodInvocation MethodInvocation SimpleName guid
set entity SimpleName MethodInvocation MethodInvocation SimpleName local metadata collection
set entity SimpleName MethodInvocation MethodInvocation SimpleName is entity known
set entity SimpleName MethodInvocation MethodInvocation SimpleName user id
set entity SimpleName MethodInvocation MethodInvocation SimpleName guid
repository error exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture repository error exception SimpleName MethodInvocation SimpleName response
capture repository error exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
user not authorized exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture user not authorized exception SimpleName MethodInvocation SimpleName response
capture user not authorized exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
invalid parameter exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture invalid parameter exception SimpleName MethodInvocation SimpleName response
capture invalid parameter exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName response
request mapping SimpleName NormalAnnotation MethodDeclaration Modifier public
method SimpleName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
request methodget QualifiedName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
path SimpleName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
user idinstancesentityguidexistence StringLiteral MemberValuePair NormalAnnotation MethodDeclaration Modifier public
request mapping SimpleName NormalAnnotation MethodDeclaration SimpleType SimpleName entity detail response
request mapping SimpleName NormalAnnotation MethodDeclaration SimpleName is entity known
method SimpleName MemberValuePair NormalAnnotation MethodDeclaration SimpleName is entity known
request methodget QualifiedName MemberValuePair NormalAnnotation MethodDeclaration SimpleName is entity known
path SimpleName MemberValuePair NormalAnnotation MethodDeclaration SimpleName is entity known
user idinstancesentityguidexistence StringLiteral MemberValuePair NormalAnnotation MethodDeclaration SimpleName is entity known
request mapping SimpleName NormalAnnotation MethodDeclaration SingleVariableDeclaration SimpleName user id
request mapping SimpleName NormalAnnotation MethodDeclaration SingleVariableDeclaration SimpleName guid
public Modifier MethodDeclaration SimpleType SimpleName entity detail response
public Modifier MethodDeclaration SimpleName is entity known
public Modifier MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName user id
public Modifier MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName guid
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier MethodDeclaration Block ReturnStatement SimpleName response
entity detail response SimpleName SimpleType MethodDeclaration SimpleName is entity known
entity detail response SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName user id
entity detail response SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName guid
is entity known SimpleName MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
is entity known SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
is entity known SimpleName MethodDeclaration SingleVariableDeclaration SimpleName user id
is entity known SimpleName MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
is entity known SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
is entity known SimpleName MethodDeclaration SingleVariableDeclaration SimpleName guid
is entity known SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
is entity known SimpleName MethodDeclaration Block ReturnStatement SimpleName response
user id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName guid
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration NormalAnnotation SimpleName request mapping
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail response
public Modifier TypeDeclaration MethodDeclaration SimpleName is entity known
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName guid
test SimpleName TypeDeclaration MethodDeclaration NormalAnnotation SimpleName request mapping
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail response
test SimpleName TypeDeclaration MethodDeclaration SimpleName is entity known
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName guid
