guid SimpleName VariableDeclarationFragment StringLiteral f f f - afb c - a - d a
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral f f f - afb c - a - d a
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral f f f - afb c - a - d a
name SimpleName VariableDeclarationFragment StringLiteral relational db schema type
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral relational db schema type
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral relational db schema type
description SimpleName VariableDeclarationFragment StringLiteral a schema type for a relational database
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName description
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral a schema type for a relational database
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName description
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral a schema type for a relational database
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName description guid
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName description guid
super type name SimpleName VariableDeclarationFragment StringLiteral complex schema type
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName super type name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral complex schema type
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName super type name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral complex schema type
archive builder SimpleName FieldAccess MethodInvocation SimpleName get entity def
archive builder SimpleName FieldAccess MethodInvocation SimpleName super type name
get entity def SimpleName MethodInvocation SimpleName super type name
archive helper SimpleName MethodInvocation SimpleName get default entity def
archive helper SimpleName MethodInvocation SimpleName guid
archive helper SimpleName MethodInvocation SimpleName name
archive helper SimpleName MethodInvocation MethodInvocation FieldAccess SimpleName archive builder
archive helper SimpleName MethodInvocation MethodInvocation SimpleName get entity def
archive helper SimpleName MethodInvocation MethodInvocation SimpleName super type name
archive helper SimpleName MethodInvocation SimpleName description
get default entity def SimpleName MethodInvocation SimpleName guid
get default entity def SimpleName MethodInvocation SimpleName name
get default entity def SimpleName MethodInvocation MethodInvocation FieldAccess SimpleName archive builder
get default entity def SimpleName MethodInvocation MethodInvocation SimpleName get entity def
get default entity def SimpleName MethodInvocation MethodInvocation SimpleName super type name
get default entity def SimpleName MethodInvocation SimpleName description
get default entity def SimpleName MethodInvocation SimpleName description guid
guid SimpleName MethodInvocation SimpleName name
guid SimpleName MethodInvocation MethodInvocation FieldAccess SimpleName archive builder
guid SimpleName MethodInvocation MethodInvocation SimpleName get entity def
guid SimpleName MethodInvocation MethodInvocation SimpleName super type name
guid SimpleName MethodInvocation SimpleName description
guid SimpleName MethodInvocation SimpleName description guid
name SimpleName MethodInvocation MethodInvocation FieldAccess SimpleName archive builder
name SimpleName MethodInvocation MethodInvocation SimpleName get entity def
name SimpleName MethodInvocation MethodInvocation SimpleName super type name
name SimpleName MethodInvocation SimpleName description
name SimpleName MethodInvocation SimpleName description guid
archive builder SimpleName FieldAccess MethodInvocation MethodInvocation SimpleName description
get entity def SimpleName MethodInvocation MethodInvocation SimpleName description
super type name SimpleName MethodInvocation MethodInvocation SimpleName description
archive builder SimpleName FieldAccess MethodInvocation MethodInvocation SimpleName description guid
get entity def SimpleName MethodInvocation MethodInvocation SimpleName description guid
super type name SimpleName MethodInvocation MethodInvocation SimpleName description guid
description SimpleName MethodInvocation SimpleName description guid
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
final Modifier VariableDeclarationStatement Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration SimpleType SimpleName entity def
private Modifier MethodDeclaration SimpleName get relational db schema type entity
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
private Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
entity def SimpleName SimpleType MethodDeclaration SimpleName get relational db schema type entity
get relational db schema type entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get relational db schema type entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get relational db schema type entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get relational db schema type entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
get relational db schema type entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier private
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity def
public Modifier TypeDeclaration MethodDeclaration SimpleName get relational db schema type entity
test SimpleName TypeDeclaration MethodDeclaration Modifier private
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity def
test SimpleName TypeDeclaration MethodDeclaration SimpleName get relational db schema type entity
