list SimpleName SimpleType ParameterizedType SimpleType SimpleName external identifier
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName external identifiers
external identifier SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName external identifiers
external identifiers SimpleName FieldAccess Assignment SimpleName external identifiers
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName set external identifiers
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName external identifiers
void PrimitiveType MethodDeclaration SimpleName set external identifiers
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName external identifiers
set external identifiers SimpleName MethodDeclaration SingleVariableDeclaration SimpleName external identifiers
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName set external identifiers
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName external identifiers
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName set external identifiers
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName external identifiers
