method SimpleName MemberValuePair QualifiedName request methodpatch
path SimpleName MemberValuePair StringLiteral user idinstancesentitydeleted entity guidrestore
request mapping SimpleName NormalAnnotation MemberValuePair SimpleName method
request mapping SimpleName NormalAnnotation MemberValuePair QualifiedName request methodpatch
request mapping SimpleName NormalAnnotation MemberValuePair SimpleName path
request mapping SimpleName NormalAnnotation MemberValuePair StringLiteral user idinstancesentitydeleted entity guidrestore
method SimpleName MemberValuePair NormalAnnotation MemberValuePair SimpleName path
method SimpleName MemberValuePair NormalAnnotation MemberValuePair StringLiteral user idinstancesentitydeleted entity guidrestore
request methodpatch QualifiedName MemberValuePair NormalAnnotation MemberValuePair SimpleName path
request methodpatch QualifiedName MemberValuePair NormalAnnotation MemberValuePair StringLiteral user idinstancesentitydeleted entity guidrestore
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleType SimpleName string
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleName user id
string SimpleName SimpleType SingleVariableDeclaration SimpleName user id
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleType SimpleName string
path variable SimpleName MarkerAnnotation SingleVariableDeclaration SimpleName deleted entity guid
string SimpleName SimpleType SingleVariableDeclaration SimpleName deleted entity guid
method name SimpleName VariableDeclarationFragment StringLiteral restore entity
final Modifier VariableDeclarationStatement SimpleType SimpleName string
final Modifier VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
final Modifier VariableDeclarationStatement VariableDeclarationFragment StringLiteral restore entity
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName method name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment StringLiteral restore entity
response SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName entity detail response
entity detail response SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName response
validate local repository SimpleName MethodInvocation SimpleName method name
local metadata collection SimpleName MethodInvocation SimpleName restore entity
local metadata collection SimpleName MethodInvocation SimpleName user id
local metadata collection SimpleName MethodInvocation SimpleName deleted entity guid
restore entity SimpleName MethodInvocation SimpleName user id
restore entity SimpleName MethodInvocation SimpleName deleted entity guid
user id SimpleName MethodInvocation SimpleName deleted entity guid
response SimpleName MethodInvocation SimpleName set entity
response SimpleName MethodInvocation MethodInvocation SimpleName local metadata collection
response SimpleName MethodInvocation MethodInvocation SimpleName restore entity
response SimpleName MethodInvocation MethodInvocation SimpleName user id
response SimpleName MethodInvocation MethodInvocation SimpleName deleted entity guid
set entity SimpleName MethodInvocation MethodInvocation SimpleName local metadata collection
set entity SimpleName MethodInvocation MethodInvocation SimpleName restore entity
set entity SimpleName MethodInvocation MethodInvocation SimpleName user id
set entity SimpleName MethodInvocation MethodInvocation SimpleName deleted entity guid
repository error exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture repository error exception SimpleName MethodInvocation SimpleName response
capture repository error exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
function not supported exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture function not supported exception SimpleName MethodInvocation SimpleName response
capture function not supported exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
user not authorized exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture user not authorized exception SimpleName MethodInvocation SimpleName response
capture user not authorized exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
invalid parameter exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture invalid parameter exception SimpleName MethodInvocation SimpleName response
capture invalid parameter exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
entity not known exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture entity not known exception SimpleName MethodInvocation SimpleName response
capture entity not known exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
entity not deleted exception SimpleName SimpleType SingleVariableDeclaration SimpleName error
capture entity not deleted exception SimpleName MethodInvocation SimpleName response
capture entity not deleted exception SimpleName MethodInvocation SimpleName error
response SimpleName MethodInvocation SimpleName error
final Modifier VariableDeclarationStatement Block ReturnStatement SimpleName response
request mapping SimpleName NormalAnnotation MethodDeclaration Modifier public
method SimpleName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
request methodpatch QualifiedName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
path SimpleName MemberValuePair NormalAnnotation MethodDeclaration Modifier public
user idinstancesentitydeleted entity guidrestore StringLiteral MemberValuePair NormalAnnotation MethodDeclaration Modifier public
request mapping SimpleName NormalAnnotation MethodDeclaration SimpleType SimpleName entity detail response
request mapping SimpleName NormalAnnotation MethodDeclaration SimpleName restore entity
method SimpleName MemberValuePair NormalAnnotation MethodDeclaration SimpleName restore entity
request methodpatch QualifiedName MemberValuePair NormalAnnotation MethodDeclaration SimpleName restore entity
path SimpleName MemberValuePair NormalAnnotation MethodDeclaration SimpleName restore entity
user idinstancesentitydeleted entity guidrestore StringLiteral MemberValuePair NormalAnnotation MethodDeclaration SimpleName restore entity
request mapping SimpleName NormalAnnotation MethodDeclaration SingleVariableDeclaration SimpleName user id
request mapping SimpleName NormalAnnotation MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
public Modifier MethodDeclaration SimpleType SimpleName entity detail response
public Modifier MethodDeclaration SimpleName restore entity
public Modifier MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName user id
public Modifier MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
public Modifier MethodDeclaration Block VariableDeclarationStatement Modifier final
public Modifier MethodDeclaration Block ReturnStatement SimpleName response
entity detail response SimpleName SimpleType MethodDeclaration SimpleName restore entity
entity detail response SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName user id
entity detail response SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
restore entity SimpleName MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
restore entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
restore entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName user id
restore entity SimpleName MethodDeclaration SingleVariableDeclaration MarkerAnnotation SimpleName path variable
restore entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName string
restore entity SimpleName MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
restore entity SimpleName MethodDeclaration Block VariableDeclarationStatement Modifier final
restore entity SimpleName MethodDeclaration Block ReturnStatement SimpleName response
user id SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration NormalAnnotation SimpleName request mapping
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail response
public Modifier TypeDeclaration MethodDeclaration SimpleName restore entity
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user id
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
test SimpleName TypeDeclaration MethodDeclaration NormalAnnotation SimpleName request mapping
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName entity detail response
test SimpleName TypeDeclaration MethodDeclaration SimpleName restore entity
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName user id
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName deleted entity guid
