int PrimitiveType SingleVariableDeclaration SimpleName recipient
int PrimitiveType SingleVariableDeclaration SimpleName rw size
int PrimitiveType SingleVariableDeclaration SimpleName packet size
buffer SimpleName SimpleType SingleVariableDeclaration SimpleName buffer
recipient SimpleName FieldAccess Assignment SimpleName recipient
session SimpleName MethodInvocation SimpleName get factory manager
session SimpleName MethodInvocation MethodInvocation SimpleName get properties
get factory manager SimpleName MethodInvocation MethodInvocation SimpleName get properties
remote window SimpleName FieldAccess MethodInvocation SimpleName init
remote window SimpleName FieldAccess MethodInvocation SimpleName rw size
remote window SimpleName FieldAccess MethodInvocation SimpleName packet size
remote window SimpleName FieldAccess MethodInvocation MethodInvocation SimpleName get properties
init SimpleName MethodInvocation SimpleName rw size
init SimpleName MethodInvocation SimpleName packet size
init SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName session
init SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get factory manager
init SimpleName MethodInvocation MethodInvocation SimpleName get properties
rw size SimpleName MethodInvocation SimpleName packet size
rw size SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName session
rw size SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get factory manager
rw size SimpleName MethodInvocation MethodInvocation SimpleName get properties
packet size SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName session
packet size SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get factory manager
packet size SimpleName MethodInvocation MethodInvocation SimpleName get properties
do init SimpleName MethodInvocation SimpleName buffer
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration SimpleType SimpleName open future
override SimpleName MarkerAnnotation MethodDeclaration SimpleName open
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration PrimitiveType int
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName recipient
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration PrimitiveType int
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName rw size
public Modifier MethodDeclaration SimpleType SimpleName open future
public Modifier MethodDeclaration SimpleName open
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName recipient
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName rw size
public Modifier MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName packet size
open future SimpleName SimpleType MethodDeclaration SimpleName open
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName recipient
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName rw size
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration PrimitiveType int
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName packet size
open future SimpleName SimpleType MethodDeclaration SingleVariableDeclaration SimpleName buffer
open SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
open SimpleName MethodDeclaration SingleVariableDeclaration SimpleName recipient
open SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
open SimpleName MethodDeclaration SingleVariableDeclaration SimpleName rw size
open SimpleName MethodDeclaration SingleVariableDeclaration PrimitiveType int
open SimpleName MethodDeclaration SingleVariableDeclaration SimpleName packet size
open SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName buffer
open SimpleName MethodDeclaration SingleVariableDeclaration SimpleName buffer
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName rw size
recipient SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
recipient SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName rw size
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName packet size
recipient SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
recipient SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName packet size
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
recipient SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName packet size
rw size SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
rw size SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName packet size
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
rw size SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
int PrimitiveType SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
packet size SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName open future
public Modifier TypeDeclaration MethodDeclaration SimpleName open
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName recipient
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName rw size
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName packet size
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName open future
test SimpleName TypeDeclaration MethodDeclaration SimpleName open
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName recipient
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName rw size
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration PrimitiveType int
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName packet size
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName buffer
