collection SimpleName SimpleType ParameterizedType SimpleType SimpleName referenceable
collection SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName entities
referenceable SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName entities
atlas glossary term SimpleName SimpleType SingleVariableDeclaration SimpleName term
void PrimitiveType MethodDeclaration SimpleName on term deleted
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName entities
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas glossary term
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName term
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas exception
on term deleted SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entities
on term deleted SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas glossary term
on term deleted SimpleName MethodDeclaration SingleVariableDeclaration SimpleName term
on term deleted SimpleName MethodDeclaration SimpleType SimpleName atlas exception
entities SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName term
entities SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
term SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName on term deleted
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entities
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName term
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName on term deleted
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entities
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName term
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas exception
