types def scrubber SimpleName VariableDeclarationFragment ClassInstanceCreation SimpleType SimpleName types def scrubber
types def scrubber SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName types def scrubber
get types def from file SimpleName MethodInvocation SimpleName legacy typesdef json
td SimpleName VariableDeclarationFragment MethodInvocation SimpleName get types def from file
td SimpleName VariableDeclarationFragment MethodInvocation SimpleName legacy typesdef json
atlas types def SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName td
trait pray index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName trait pray index
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
vendor pii index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName vendor pii index
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
finance index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName finance index
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
classification trait pray index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName classification trait pray index
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
classification vendor pii index SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName classification vendor pii index
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
classification financendex SimpleName VariableDeclarationFragment NumberLiteral empty
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment SimpleName classification financendex
int PrimitiveType VariableDeclarationStatement VariableDeclarationFragment NumberLiteral empty
td SimpleName MethodInvocation SimpleName get classification defs
td SimpleName MethodInvocation MethodInvocation SimpleName get
get classification defs SimpleName MethodInvocation MethodInvocation SimpleName get
td SimpleName MethodInvocation MethodInvocation SimpleName classification trait pray index
get classification defs SimpleName MethodInvocation MethodInvocation SimpleName classification trait pray index
get SimpleName MethodInvocation SimpleName classification trait pray index
td SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
get classification defs SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
get SimpleName MethodInvocation MethodInvocation SimpleName get name
classification trait pray index SimpleName MethodInvocation MethodInvocation SimpleName get name
types def scrubber SimpleName MethodInvocation SimpleName get legacy type name for struct def
types def scrubber SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
types def scrubber SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification trait pray index
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName get name
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification trait pray index
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation SimpleName get name
expected trait pray struct name SimpleName VariableDeclarationFragment MethodInvocation SimpleName types def scrubber
expected trait pray struct name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get legacy type name for struct def
expected trait pray struct name SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName expected trait pray struct name
td SimpleName MethodInvocation SimpleName get classification defs
td SimpleName MethodInvocation MethodInvocation SimpleName get
get classification defs SimpleName MethodInvocation MethodInvocation SimpleName get
td SimpleName MethodInvocation MethodInvocation SimpleName classification vendor pii index
get classification defs SimpleName MethodInvocation MethodInvocation SimpleName classification vendor pii index
get SimpleName MethodInvocation SimpleName classification vendor pii index
td SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
get classification defs SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
get SimpleName MethodInvocation MethodInvocation SimpleName get name
classification vendor pii index SimpleName MethodInvocation MethodInvocation SimpleName get name
types def scrubber SimpleName MethodInvocation SimpleName get legacy type name for struct def
types def scrubber SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
types def scrubber SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification vendor pii index
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName get name
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification vendor pii index
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation SimpleName get name
expected vendor pii struct name SimpleName VariableDeclarationFragment MethodInvocation SimpleName types def scrubber
expected vendor pii struct name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get legacy type name for struct def
expected vendor pii struct name SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName expected vendor pii struct name
td SimpleName MethodInvocation SimpleName get classification defs
td SimpleName MethodInvocation MethodInvocation SimpleName get
get classification defs SimpleName MethodInvocation MethodInvocation SimpleName get
td SimpleName MethodInvocation MethodInvocation SimpleName classification financendex
get classification defs SimpleName MethodInvocation MethodInvocation SimpleName classification financendex
get SimpleName MethodInvocation SimpleName classification financendex
td SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
get classification defs SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get name
get SimpleName MethodInvocation MethodInvocation SimpleName get name
classification financendex SimpleName MethodInvocation MethodInvocation SimpleName get name
types def scrubber SimpleName MethodInvocation SimpleName get legacy type name for struct def
types def scrubber SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
types def scrubber SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification financendex
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName get name
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification financendex
get legacy type name for struct def SimpleName MethodInvocation MethodInvocation SimpleName get name
expected finance struct name SimpleName VariableDeclarationFragment MethodInvocation SimpleName types def scrubber
expected finance struct name SimpleName VariableDeclarationFragment MethodInvocation SimpleName get legacy type name for struct def
expected finance struct name SimpleName VariableDeclarationFragment MethodInvocation MethodInvocation SimpleName get name
string SimpleName SimpleType VariableDeclarationStatement VariableDeclarationFragment SimpleName expected finance struct name
types def scrubber SimpleName MethodInvocation SimpleName scrub
types def scrubber SimpleName MethodInvocation SimpleName td
scrub SimpleName MethodInvocation SimpleName td
assert new types def SimpleName MethodInvocation MethodInvocation SimpleName types def scrubber
assert new types def SimpleName MethodInvocation MethodInvocation SimpleName scrub
assert new types def SimpleName MethodInvocation MethodInvocation SimpleName td
assert new types def SimpleName MethodInvocation SimpleName trait pray index
assert new types def SimpleName MethodInvocation SimpleName vendor pii index
assert new types def SimpleName MethodInvocation SimpleName finance index
assert new types def SimpleName MethodInvocation SimpleName expected trait pray struct name
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName trait pray index
scrub SimpleName MethodInvocation MethodInvocation SimpleName trait pray index
td SimpleName MethodInvocation MethodInvocation SimpleName trait pray index
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName vendor pii index
scrub SimpleName MethodInvocation MethodInvocation SimpleName vendor pii index
td SimpleName MethodInvocation MethodInvocation SimpleName vendor pii index
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName finance index
scrub SimpleName MethodInvocation MethodInvocation SimpleName finance index
td SimpleName MethodInvocation MethodInvocation SimpleName finance index
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName expected trait pray struct name
scrub SimpleName MethodInvocation MethodInvocation SimpleName expected trait pray struct name
td SimpleName MethodInvocation MethodInvocation SimpleName expected trait pray struct name
types def scrubber SimpleName MethodInvocation MethodInvocation SimpleName expected vendor pii struct name
scrub SimpleName MethodInvocation MethodInvocation SimpleName expected vendor pii struct name
td SimpleName MethodInvocation MethodInvocation SimpleName expected vendor pii struct name
trait pray index SimpleName MethodInvocation SimpleName vendor pii index
trait pray index SimpleName MethodInvocation SimpleName finance index
trait pray index SimpleName MethodInvocation SimpleName expected trait pray struct name
trait pray index SimpleName MethodInvocation SimpleName expected vendor pii struct name
trait pray index SimpleName MethodInvocation SimpleName expected finance struct name
vendor pii index SimpleName MethodInvocation SimpleName finance index
vendor pii index SimpleName MethodInvocation SimpleName expected trait pray struct name
vendor pii index SimpleName MethodInvocation SimpleName expected vendor pii struct name
vendor pii index SimpleName MethodInvocation SimpleName expected finance struct name
finance index SimpleName MethodInvocation SimpleName expected trait pray struct name
finance index SimpleName MethodInvocation SimpleName expected vendor pii struct name
finance index SimpleName MethodInvocation SimpleName expected finance struct name
expected trait pray struct name SimpleName MethodInvocation SimpleName expected vendor pii struct name
expected trait pray struct name SimpleName MethodInvocation SimpleName expected finance struct name
expected vendor pii struct name SimpleName MethodInvocation SimpleName expected finance struct name
assert trait map SimpleName MethodInvocation SimpleName types def scrubber
assert trait map SimpleName MethodInvocation SimpleName td
assert trait map SimpleName MethodInvocation SimpleName classification trait pray index
assert trait map SimpleName MethodInvocation SimpleName expected trait pray struct name
assert trait map SimpleName MethodInvocation NumberLiteral empty
types def scrubber SimpleName MethodInvocation SimpleName td
types def scrubber SimpleName MethodInvocation SimpleName classification trait pray index
types def scrubber SimpleName MethodInvocation SimpleName expected trait pray struct name
types def scrubber SimpleName MethodInvocation NumberLiteral empty
td SimpleName MethodInvocation SimpleName classification trait pray index
td SimpleName MethodInvocation SimpleName expected trait pray struct name
td SimpleName MethodInvocation NumberLiteral empty
classification trait pray index SimpleName MethodInvocation SimpleName expected trait pray struct name
classification trait pray index SimpleName MethodInvocation NumberLiteral empty
expected trait pray struct name SimpleName MethodInvocation NumberLiteral empty
assert trait map SimpleName MethodInvocation SimpleName types def scrubber
assert trait map SimpleName MethodInvocation SimpleName td
assert trait map SimpleName MethodInvocation SimpleName classification vendor pii index
assert trait map SimpleName MethodInvocation SimpleName expected vendor pii struct name
assert trait map SimpleName MethodInvocation NumberLiteral empty
types def scrubber SimpleName MethodInvocation SimpleName td
types def scrubber SimpleName MethodInvocation SimpleName classification vendor pii index
types def scrubber SimpleName MethodInvocation SimpleName expected vendor pii struct name
types def scrubber SimpleName MethodInvocation NumberLiteral empty
td SimpleName MethodInvocation SimpleName classification vendor pii index
td SimpleName MethodInvocation SimpleName expected vendor pii struct name
td SimpleName MethodInvocation NumberLiteral empty
classification vendor pii index SimpleName MethodInvocation SimpleName expected vendor pii struct name
classification vendor pii index SimpleName MethodInvocation NumberLiteral empty
expected vendor pii struct name SimpleName MethodInvocation NumberLiteral empty
assert trait map SimpleName MethodInvocation SimpleName types def scrubber
assert trait map SimpleName MethodInvocation SimpleName td
assert trait map SimpleName MethodInvocation SimpleName classification financendex
assert trait map SimpleName MethodInvocation SimpleName expected finance struct name
assert trait map SimpleName MethodInvocation NumberLiteral empty
types def scrubber SimpleName MethodInvocation SimpleName td
types def scrubber SimpleName MethodInvocation SimpleName classification financendex
types def scrubber SimpleName MethodInvocation SimpleName expected finance struct name
types def scrubber SimpleName MethodInvocation NumberLiteral empty
td SimpleName MethodInvocation SimpleName classification financendex
td SimpleName MethodInvocation SimpleName expected finance struct name
td SimpleName MethodInvocation NumberLiteral empty
classification financendex SimpleName MethodInvocation SimpleName expected finance struct name
classification financendex SimpleName MethodInvocation NumberLiteral empty
expected finance struct name SimpleName MethodInvocation NumberLiteral empty
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
int PrimitiveType VariableDeclarationStatement Block VariableDeclarationStatement PrimitiveType int
test SimpleName MarkerAnnotation MethodDeclaration Modifier public
test SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
test SimpleName MarkerAnnotation MethodDeclaration SimpleName perform scrub
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName perform scrub
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration SimpleName perform scrub
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
void PrimitiveType MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
perform scrub SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
perform scrub SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
perform scrub SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
perform scrub SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
perform scrub SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
perform scrub SimpleName MethodDeclaration Block VariableDeclarationStatement PrimitiveType int
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName perform scrub
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName test
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName perform scrub
