atlas entity SimpleName SimpleType SingleVariableDeclaration SimpleName entity
list SimpleName SimpleType ParameterizedType SimpleType SimpleName atlas classification
list SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName classifications
atlas classification SimpleName SimpleType ParameterizedType SingleVariableDeclaration SimpleName classifications
collection utils SimpleName MethodInvocation SimpleName is not empty
collection utils SimpleName MethodInvocation SimpleName classifications
is not empty SimpleName MethodInvocation SimpleName classifications
list SimpleName SimpleType ParameterizedType SimpleType SimpleName entity audit event v
atlas classification SimpleName SimpleType SingleVariableDeclaration SimpleName classification
entity SimpleName MethodInvocation SimpleName get guid
classification SimpleName MethodInvocation SimpleName get entity guid
entity SimpleName MethodInvocation MethodInvocation SimpleName equals
get guid SimpleName MethodInvocation MethodInvocation SimpleName equals
entity SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification
entity SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get entity guid
get guid SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName classification
get guid SimpleName MethodInvocation MethodInvocation MethodInvocation SimpleName get entity guid
equals SimpleName MethodInvocation MethodInvocation SimpleName classification
equals SimpleName MethodInvocation MethodInvocation SimpleName get entity guid
atlas type SimpleName MethodInvocation SimpleName to json
atlas type SimpleName MethodInvocation SimpleName classification
to json SimpleName MethodInvocation SimpleName classification
added classification StringLiteral InfixExpression MethodInvocation SimpleName atlas type
added classification StringLiteral InfixExpression MethodInvocation SimpleName to json
added classification StringLiteral InfixExpression MethodInvocation SimpleName classification
create event SimpleName MethodInvocation SimpleName entity
create event SimpleName MethodInvocation SimpleName classification add
create event SimpleName MethodInvocation InfixExpression StringLiteral added classification
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName atlas type
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification
entity SimpleName MethodInvocation SimpleName classification add
entity SimpleName MethodInvocation InfixExpression StringLiteral added classification
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName atlas type
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification
classification add SimpleName MethodInvocation InfixExpression StringLiteral added classification
classification add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName atlas type
classification add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
classification add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification
events SimpleName MethodInvocation SimpleName add
events SimpleName MethodInvocation MethodInvocation SimpleName create event
events SimpleName MethodInvocation MethodInvocation SimpleName entity
events SimpleName MethodInvocation MethodInvocation SimpleName classification add
events SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral added classification
add SimpleName MethodInvocation MethodInvocation SimpleName create event
add SimpleName MethodInvocation MethodInvocation SimpleName entity
add SimpleName MethodInvocation MethodInvocation SimpleName classification add
add SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral added classification
atlas type SimpleName MethodInvocation SimpleName to json
atlas type SimpleName MethodInvocation SimpleName classification
to json SimpleName MethodInvocation SimpleName classification
added propagated classification StringLiteral InfixExpression MethodInvocation SimpleName atlas type
added propagated classification StringLiteral InfixExpression MethodInvocation SimpleName to json
added propagated classification StringLiteral InfixExpression MethodInvocation SimpleName classification
create event SimpleName MethodInvocation SimpleName entity
create event SimpleName MethodInvocation SimpleName propagated classification add
create event SimpleName MethodInvocation InfixExpression StringLiteral added propagated classification
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName atlas type
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
create event SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification
entity SimpleName MethodInvocation SimpleName propagated classification add
entity SimpleName MethodInvocation InfixExpression StringLiteral added propagated classification
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName atlas type
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
entity SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification
propagated classification add SimpleName MethodInvocation InfixExpression StringLiteral added propagated classification
propagated classification add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName atlas type
propagated classification add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName to json
propagated classification add SimpleName MethodInvocation InfixExpression MethodInvocation SimpleName classification
events SimpleName MethodInvocation SimpleName add
events SimpleName MethodInvocation MethodInvocation SimpleName create event
events SimpleName MethodInvocation MethodInvocation SimpleName entity
events SimpleName MethodInvocation MethodInvocation SimpleName propagated classification add
events SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral added propagated classification
add SimpleName MethodInvocation MethodInvocation SimpleName create event
add SimpleName MethodInvocation MethodInvocation SimpleName entity
add SimpleName MethodInvocation MethodInvocation SimpleName propagated classification add
add SimpleName MethodInvocation MethodInvocation InfixExpression StringLiteral added propagated classification
atlas classification SimpleName SimpleType SingleVariableDeclaration EnhancedForStatement SimpleName classifications
classification SimpleName SingleVariableDeclaration EnhancedForStatement SimpleName classifications
audit repository SimpleName MethodInvocation SimpleName put events v
audit repository SimpleName MethodInvocation SimpleName events
put events v SimpleName MethodInvocation SimpleName events
override SimpleName MarkerAnnotation MethodDeclaration Modifier public
override SimpleName MarkerAnnotation MethodDeclaration PrimitiveType void
override SimpleName MarkerAnnotation MethodDeclaration SimpleName on classifications added
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName entity
override SimpleName MarkerAnnotation MethodDeclaration SingleVariableDeclaration SimpleName classifications
public Modifier MethodDeclaration PrimitiveType void
public Modifier MethodDeclaration SimpleName on classifications added
public Modifier MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas entity
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName entity
public Modifier MethodDeclaration SingleVariableDeclaration SimpleName classifications
public Modifier MethodDeclaration SimpleType SimpleName atlas base exception
void PrimitiveType MethodDeclaration SimpleName on classifications added
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas entity
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName entity
void PrimitiveType MethodDeclaration SingleVariableDeclaration SimpleName classifications
void PrimitiveType MethodDeclaration SimpleType SimpleName atlas base exception
on classifications added SimpleName MethodDeclaration SingleVariableDeclaration SimpleType SimpleName atlas entity
on classifications added SimpleName MethodDeclaration SingleVariableDeclaration SimpleName entity
on classifications added SimpleName MethodDeclaration SingleVariableDeclaration SimpleName classifications
on classifications added SimpleName MethodDeclaration SimpleType SimpleName atlas base exception
entity SimpleName SingleVariableDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classifications
entity SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
classifications SimpleName SingleVariableDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
public Modifier TypeDeclaration SimpleName test
public Modifier TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
public Modifier TypeDeclaration MethodDeclaration Modifier public
public Modifier TypeDeclaration MethodDeclaration PrimitiveType void
public Modifier TypeDeclaration MethodDeclaration SimpleName on classifications added
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity
public Modifier TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classifications
public Modifier TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
test SimpleName TypeDeclaration MethodDeclaration MarkerAnnotation SimpleName override
test SimpleName TypeDeclaration MethodDeclaration Modifier public
test SimpleName TypeDeclaration MethodDeclaration PrimitiveType void
test SimpleName TypeDeclaration MethodDeclaration SimpleName on classifications added
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName entity
test SimpleName TypeDeclaration MethodDeclaration SingleVariableDeclaration SimpleName classifications
test SimpleName TypeDeclaration MethodDeclaration SimpleType SimpleName atlas base exception
